version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    target-branch: acceptatie
    open-pull-requests-limit: 10
    groups:
      dotnet-microsoft:
        patterns:
          - "Microsoft.*"
          - "System.*"
      dotnet-other:
        patterns:
          - "*"
        exclude-patterns:
          - "Microsoft.*"
          - "System.*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    target-branch: acceptatie
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
