namespace Jobsy.Core.Rules;

/// <summary>150 unique workplace DISC items (37–38 per style) with reverse-keyed stems.</summary>
internal static class DeepAnalysisDiscItems
{
    public const int ItemsPerDomainMin = 37;

    public static IReadOnlyList<(string Domain, bool Reverse, string Prompt)> All { get; } =
    [
(DiscTestCatalog.Dominant, true, "Ik wacht tot een ander het besluit neemt als het druk wordt in de kas."),
        (DiscTestCatalog.Dominant, true, "Ik blijf aan de kant als de magazijnploeg zonder sturing staat."),
        (DiscTestCatalog.Dominant, true, "Ik laat anderen het tempo bepalen als de winkelavond piekt."),
        (DiscTestCatalog.Dominant, true, "Ik schuif een lastige keuze door als de keuken vastloopt."),
        (DiscTestCatalog.Dominant, true, "Ik vermijd de leiding als de laadperron-chaos begint."),
        (DiscTestCatalog.Dominant, true, "Ik houd me afzijdig als twee werkwijzen op de bouw botsen."),
        (DiscTestCatalog.Dominant, true, "Ik laat een seizoensploeg zelf maar uitzoeken hoe het moet."),
        (DiscTestCatalog.Dominant, true, "Ik stel een knoop uit als de kwekerij tussen orders moet kiezen."),
        (DiscTestCatalog.Dominant, false, "Ik neem het voortouw als de planning in de kas vastloopt."),
        (DiscTestCatalog.Dominant, false, "Ik zeg duidelijk wat er moet gebeuren als de rit in het magazijn stokt."),
        (DiscTestCatalog.Dominant, false, "Ik durf een knoop door te hakken als de winkelvloer te druk wordt."),
        (DiscTestCatalog.Dominant, false, "Ik stuur bij als de ploeg in de keuken achterloopt."),
        (DiscTestCatalog.Dominant, false, "Ik zet tempo als de laadperron-wachtrij oploopt."),
        (DiscTestCatalog.Dominant, false, "Ik kies een richting als twee werkwijzen botsen op de bouwplaats."),
        (DiscTestCatalog.Dominant, false, "Ik pak de leiding als een seizoensploeg zonder plan staat."),
        (DiscTestCatalog.Dominant, false, "Ik maak een keuze als de kwekerij tussen twee orders moet kiezen."),
        (DiscTestCatalog.Dominant, false, "Ik duw door als de koelcel-deadline krap is."),
        (DiscTestCatalog.Dominant, false, "Ik zeg stop als een werkwijze te langzaam is op de orderstraat."),
        (DiscTestCatalog.Dominant, false, "Ik neem verantwoordelijkheid als de groothandel een spoedklus krijgt."),
        (DiscTestCatalog.Dominant, false, "Ik geef richting als het tuincentrum een piekdag heeft."),
        (DiscTestCatalog.Dominant, false, "Ik stuur bij als de kaspad-rondgang te laat start."),
        (DiscTestCatalog.Dominant, false, "Ik zet een target als de verkoop op de markt inzakt."),
        (DiscTestCatalog.Dominant, false, "Ik kies een kortere route als de rit naar het Westland vastzit."),
        (DiscTestCatalog.Dominant, false, "Ik maak tempo als de oogstwagen te vol raakt."),
        (DiscTestCatalog.Dominant, false, "Ik zeg wat er eerst moet als de keuken en de zaal ruzie hebben over volgorde."),
        (DiscTestCatalog.Dominant, false, "Ik pak door als een collega twijfelt bij een lastige klant op de markt."),
        (DiscTestCatalog.Dominant, false, "Ik besluit snel als de weersomslag de teeltplanning raakt."),
        (DiscTestCatalog.Dominant, false, "Ik stuur de groep als een storing de lijn in het magazijn stillegt."),
        (DiscTestCatalog.Dominant, false, "Ik dwing een keuze af als de shift twee kanten op wil."),
        (DiscTestCatalog.Dominant, false, "Ik zet de toon als een nieuwe dagploeg nog zoekt hoe te starten."),
        (DiscTestCatalog.Dominant, false, "Ik neem het woord als de briefing te vaag blijft."),
        (DiscTestCatalog.Dominant, false, "Ik duw het werk over de streep als iedereen wacht tot een ander begint."),
        (DiscTestCatalog.Dominant, false, "Ik kies resultaat boven overleg als de vrachtwagen al klaarstaat."),
        (DiscTestCatalog.Dominant, false, "Ik maak een harde afspraak als de leverancier uitloopt."),
        (DiscTestCatalog.Dominant, false, "Ik zeg nee tegen uitstel als de winkelavond al volgeboekt is."),
        (DiscTestCatalog.Dominant, false, "Ik stuur bij als de kasploeg te veel praat en te weinig plukt."),
        (DiscTestCatalog.Dominant, false, "Ik zet druk als een offerte voor de tuinbouw stilvalt."),
        (DiscTestCatalog.Dominant, false, "Ik neem de leiding als er een onveilige situatie op het erf is."),
        (DiscTestCatalog.Invloed, true, "Ik werk het liefst zonder kletsen als de winkelavond piekt."),
        (DiscTestCatalog.Invloed, true, "Ik houd afstand tot gasten als de horecabalance volloopt."),
        (DiscTestCatalog.Invloed, true, "Ik laat anderen het woord doen in de ploegbespreking."),
        (DiscTestCatalog.Invloed, true, "Ik vermijd extra praatjes op het laadperron."),
        (DiscTestCatalog.Invloed, true, "Ik trek me terug als de sfeer in de kas hangt."),
        (DiscTestCatalog.Invloed, true, "Ik vind een volle zaterdagwinkel vooral vermoeiend."),
        (DiscTestCatalog.Invloed, true, "Ik houd liever mijn mond in de toolbox."),
        (DiscTestCatalog.Invloed, true, "Ik laat nieuwe seizoenskrachten zelf maar aanklampen."),
        (DiscTestCatalog.Invloed, false, "Ik krijg energie van kletsen met klanten op de winkelvloer."),
        (DiscTestCatalog.Invloed, false, "Ik neem mensen mee in een verhaal als de briefing droog is."),
        (DiscTestCatalog.Invloed, false, "Ik maak contact als een nieuwe seizoenskracht verloren kijkt."),
        (DiscTestCatalog.Invloed, false, "Ik steek een team aan als de sfeer in de kas hangt."),
        (DiscTestCatalog.Invloed, false, "Ik praat makkelijk met gasten als de horecabalance volloopt."),
        (DiscTestCatalog.Invloed, false, "Ik vertel enthousiast over het product op de markt."),
        (DiscTestCatalog.Invloed, false, "Ik betrek stillere collega’s als de ploegbespreking start."),
        (DiscTestCatalog.Invloed, false, "Ik houd de sfeer luchtig als de winkelavond lang duurt."),
        (DiscTestCatalog.Invloed, false, "Ik overtuig een twijfelende klant in het tuincentrum."),
        (DiscTestCatalog.Invloed, false, "Ik maak een praatje dat de sfeer op het laadperron lichter maakt."),
        (DiscTestCatalog.Invloed, false, "Ik stel mensen voor als twee ploegen elkaar nog niet kennen."),
        (DiscTestCatalog.Invloed, false, "Ik deel een succes als de oogstwagen vol is."),
        (DiscTestCatalog.Invloed, false, "Ik neem het woord om anderen mee te krijgen bij een nieuwe werkwijze."),
        (DiscTestCatalog.Invloed, false, "Ik houd contact met de zaal als de keuken onder druk staat."),
        (DiscTestCatalog.Invloed, false, "Ik maak een grap die de spanning in de koelcel breekt."),
        (DiscTestCatalog.Invloed, false, "Ik nodig iemand uit om mee te denken als de planning schuift."),
        (DiscTestCatalog.Invloed, false, "Ik vertel de klant waarom dit product uit het Westland bijzonder is."),
        (DiscTestCatalog.Invloed, false, "Ik haal energie uit een volle winkel op zaterdag."),
        (DiscTestCatalog.Invloed, false, "Ik steek de hand uit naar een collega die zich terugtrekt."),
        (DiscTestCatalog.Invloed, false, "Ik presenteer het dagdoel zo dat mensen er zin in krijgen."),
        (DiscTestCatalog.Invloed, false, "Ik houd de groep erbij als de toolbox saai dreigt te worden."),
        (DiscTestCatalog.Invloed, false, "Ik maak verbinding tussen kas en kantoor als er ruis is."),
        (DiscTestCatalog.Invloed, false, "Ik praat een boze gast rustig als de rij bij de kassa groeit."),
        (DiscTestCatalog.Invloed, false, "Ik vier klein resultaat zodat de ploeg zich gezien voelt."),
        (DiscTestCatalog.Invloed, false, "Ik nodig een stille collega uit om ook iets te zeggen."),
        (DiscTestCatalog.Invloed, false, "Ik breng sfeer als de nachtdienst in het magazijn lang duurt."),
        (DiscTestCatalog.Invloed, false, "Ik overtuig een team om een nieuwe aanpak te proberen."),
        (DiscTestCatalog.Invloed, false, "Ik houd de energie vast als de middagdip in de kas komt."),
        (DiscTestCatalog.Invloed, false, "Ik maak een warm welkom als seizoenskrachten de eerste dag starten."),
        (DiscTestCatalog.Invloed, false, "Ik vertel verhalen die het werk op de markt leuker maken."),
        (DiscTestCatalog.Stabiel, true, "Ik wissel graag steeds van taak als de kasploeg een vaste ronde heeft."),
        (DiscTestCatalog.Stabiel, true, "Ik raak ongeduldig van dezelfde magazijnronde elke nacht."),
        (DiscTestCatalog.Stabiel, true, "Ik spring van klus naar klus als de winkel een vaste flow heeft."),
        (DiscTestCatalog.Stabiel, true, "Ik breek liever het ritme als de kwekerij voorspelbaar is."),
        (DiscTestCatalog.Stabiel, true, "Ik zoek afwisseling in plaats van een vaste overdracht."),
        (DiscTestCatalog.Stabiel, true, "Ik haak af als het werk wekenlang hetzelfde blijft op het perceel."),
        (DiscTestCatalog.Stabiel, true, "Ik verander midden in de shift van plan zonder overleg."),
        (DiscTestCatalog.Stabiel, true, "Ik laat de overdracht schieten als ik eerder weg wil."),
        (DiscTestCatalog.Stabiel, false, "Ik houd van een vast ritme in de kas van week tot week."),
        (DiscTestCatalog.Stabiel, false, "Ik blijf rustig dezelfde stappen doen als de orderstraat loopt."),
        (DiscTestCatalog.Stabiel, false, "Ik zorg dat collega’s op mij kunnen rekenen in de nachtdienst."),
        (DiscTestCatalog.Stabiel, false, "Ik werk het liefst met duidelijke ronden in het magazijn."),
        (DiscTestCatalog.Stabiel, false, "Ik houd de sfeer gelijkmatig als de winkelavond druk is."),
        (DiscTestCatalog.Stabiel, false, "Ik blijf beschikbaar voor het team als het seizoen piekt."),
        (DiscTestCatalog.Stabiel, false, "Ik doe mijn ronde op dezelfde manier zodat niets wordt overgeslagen."),
        (DiscTestCatalog.Stabiel, false, "Ik steun een collega als de keuken onverwacht extra gasten krijgt."),
        (DiscTestCatalog.Stabiel, false, "Ik houd vol tot het einde van de shift in de koelcel."),
        (DiscTestCatalog.Stabiel, false, "Ik werk graag in een vaste ploeg in de kwekerij."),
        (DiscTestCatalog.Stabiel, false, "Ik blijf kalm en gestaag als de oogstwagen langzaam voller wordt."),
        (DiscTestCatalog.Stabiel, false, "Ik zorg voor continuïteit als een nieuwe kracht moet inwerken."),
        (DiscTestCatalog.Stabiel, false, "Ik houd van voorspelbare taken op het perceel."),
        (DiscTestCatalog.Stabiel, false, "Ik blijf trouw aan afgesproken tijden op het laadperron."),
        (DiscTestCatalog.Stabiel, false, "Ik maak de dag af zoals beloofd in de groothandel."),
        (DiscTestCatalog.Stabiel, false, "Ik hou het tempo gelijkmatig als anderen gaan racen in de kas."),
        (DiscTestCatalog.Stabiel, false, "Ik bied rust als de winkelploeg zenuwachtig wordt."),
        (DiscTestCatalog.Stabiel, false, "Ik blijf de standaardronde doen als er extra druk bijkomt."),
        (DiscTestCatalog.Stabiel, false, "Ik werk liever gestaag door dan in pieken en dalen op de markt."),
        (DiscTestCatalog.Stabiel, false, "Ik houd de groep bij elkaar als de seizoensploeg wisselt."),
        (DiscTestCatalog.Stabiel, false, "Ik zorg dat de overdracht naar de volgende shift klopt."),
        (DiscTestCatalog.Stabiel, false, "Ik blijf vriendelijk en gelijkmatig bij de kassa."),
        (DiscTestCatalog.Stabiel, false, "Ik steun vaste werkwijzen in de teeltregistratie."),
        (DiscTestCatalog.Stabiel, false, "Ik houd vol als de nachtelijke ronde in het magazijn saai wordt."),
        (DiscTestCatalog.Stabiel, false, "Ik maak het werk voorspelbaar voor wie na mij komt."),
        (DiscTestCatalog.Stabiel, false, "Ik blijf beschikbaar als een collega uitvalt in de kas."),
        (DiscTestCatalog.Stabiel, false, "Ik kies rust boven drama als de keuken een piek heeft."),
        (DiscTestCatalog.Stabiel, false, "Ik houd de lijn stabiel als er een kleine storing is."),
        (DiscTestCatalog.Stabiel, false, "Ik werk het liefst met dezelfde taken elke ochtend in de kwekerij."),
        (DiscTestCatalog.Nauwkeurig, true, "Ik sla stappen over als de orderstraat haast heeft."),
        (DiscTestCatalog.Nauwkeurig, true, "Ik vul de teeltregistratie later wel in, als het druk is."),
        (DiscTestCatalog.Nauwkeurig, true, "Ik kijk niet na of de laadlijst klopt als we moeten rijden."),
        (DiscTestCatalog.Nauwkeurig, true, "Ik doe de kassa op gevoel dicht als de winkelavond lang was."),
        (DiscTestCatalog.Nauwkeurig, true, "Ik laat details liggen als de oogstwagen vol raakt."),
        (DiscTestCatalog.Nauwkeurig, true, "Ik werk liever snel dan volgens de checklist op het erf."),
        (DiscTestCatalog.Nauwkeurig, true, "Ik sla de temperatuurlog over in de koelketen."),
        (DiscTestCatalog.Nauwkeurig, true, "Ik rond de telling af zonder na te tellen."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik controleer de cijfers voordat de vracht de koelcel in gaat."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik werk netjes volgens de lijst op de orderstraat."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik vink elke stap af in de teeltregistratie."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik let op details bij het inpakken in de groothandel."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik houd me aan de veiligheidsregels op het erf."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik maak de administratie van de shift kloppend voordat ik ga."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik meet na of de kwaliteit van de oogst aan de norm voldoet."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik volg het protocol in de keuken ook als het druk is."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik zet de kassa volgens de procedure dicht."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik check de temperatuurlog in de koelketen."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik houd de documenten bij voor de winkelavond-telling."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik werk precies af volgens de plukinstructie in de kas."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik controleer of de laadlijst klopt voor de rit naar het Westland."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik let op hygiëne bij de verwerking in de kwekerij."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik maak fouten in de orderpicking zichtbaar in plaats van weg te moffelen."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik volg de checklist op de bouwplaats ook bij tempo."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik zet de voorraadcijfers recht voordat de winkel opent."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik houd me aan de dosering in de teelt."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik kijk of etiketten kloppen voordat de doos dichtgaat."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik rond de kwaliteitsronde volledig af in het magazijn."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik werk volgens de HACCP-stappen in de keuken."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik check ritpapieren voordat we vertrekken."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik maak een nette overdracht met getallen, niet uit het hoofd."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik volg de sproeiregels in de kas zonder af te wijken."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik tel na of de kratten op het laadperron compleet zijn."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik houd de urenregistratie van de seizoensploeg kloppend."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik werk volgens de plukhoogte-afspraak tot de laatste plant."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik controleer of de winkelpresentatie volgens plan staat."),
        (DiscTestCatalog.Nauwkeurig, false, "Ik maak de keukenlijst af in de juiste volgorde."),
    ];
}
