namespace Jobsy.Core.Rules;

/// <summary>
/// 150 unique RIASEC Likert items: 25 per Holland type, reverse-keyed items mixed in.
/// Occupational interest wording for Den Haag / Westland matching.
/// </summary>
internal static class DeepAnalysisCareerItems
{
    public static IReadOnlyList<(string Domain, bool Reverse, string Prompt)> All { get; } =
    [
        // Realistic — 25
        (CareerTestCatalog.Realistic, false, "Ik werk graag met mijn handen, gereedschap of machines."),
        (CareerTestCatalog.Realistic, false, "Ik vind het prettig om buiten of in een kas, magazijn of werkplaats te zijn."),
        (CareerTestCatalog.Realistic, false, "Ik zie graag een tastbaar resultaat aan het eind van de dienst."),
        (CareerTestCatalog.Realistic, true, "Ik vermijd werk waarbij ik vies, nat of stoffig kan worden."),
        (CareerTestCatalog.Realistic, false, "Ik snap snel hoe een apparaat of installatie in elkaar steekt."),
        (CareerTestCatalog.Realistic, false, "Ik houd van tillen, sjouwen of fysiek doorwerken als het veilig kan."),
        (CareerTestCatalog.Realistic, false, "Het repareren of bijstellen van iets dat hapert geeft me voldoening."),
        (CareerTestCatalog.Realistic, true, "Praktisch klussen voelt als tijdverlies; ik wil vooral achter een scherm zitten."),
        (CareerTestCatalog.Realistic, false, "Ik oriënteer me makkelijk in een grote ruimte, tuin of magazijn."),
        (CareerTestCatalog.Realistic, false, "Ik volg technische instructies en pas ze toe zonder veel uitleg."),
        (CareerTestCatalog.Realistic, true, "Ik voel me onzeker bij machines, hekwerken of zwaar materieel."),
        (CareerTestCatalog.Realistic, false, "Ik kweek, plant, oogst of verwerk producten liever dan ik erover praat."),
        (CareerTestCatalog.Realistic, false, "Ik let op veiligheid: looppaden, scherpe randen, natte vloeren."),
        (CareerTestCatalog.Realistic, false, "Ik kan een hele dienst op de been blijven zonder dat ik afhaak."),
        (CareerTestCatalog.Realistic, true, "Ik kies werk waarin ik zo min mogelijk fysiek hoef te doen."),
        (CareerTestCatalog.Realistic, false, "Ik meet, weeg of tel liever in het echt dan in een spreadsheet."),
        (CareerTestCatalog.Realistic, false, "Ik vind het fijn om met seizoen, weer of teelt mee te werken."),
        (CareerTestCatalog.Realistic, true, "Technische storingen laat ik het liefst helemaal aan een ander."),
        (CareerTestCatalog.Realistic, false, "Ik bouw, monteer of zet iets in elkaar volgens een tekening of voorbeeld."),
        (CareerTestCatalog.Realistic, false, "Ik houd van ritme: herhalen, tempo maken, afvinken."),
        (CareerTestCatalog.Realistic, true, "Buitenwerk of productieomgevingen putten me mentaal uit."),
        (CareerTestCatalog.Realistic, false, "Ik check kwaliteit met ogen en handen, niet alleen op papier."),
        (CareerTestCatalog.Realistic, false, "Ik kan een voertuig, steekwagen of heftruck-achtige taak aanleren."),
        (CareerTestCatalog.Realistic, true, "Ik vermijd werkplaatsen, kassen en keukens als ik de keuze heb."),
        (CareerTestCatalog.Realistic, false, "Ik krijg energie van doen, niet van eindeloos overleggen over doen."),

        // Investigative — 25
        (CareerTestCatalog.Investigative, false, "Ik onderzoek graag waarom iets niet werkt zoals het hoort."),
        (CareerTestCatalog.Investigative, false, "Ik zoek uit hoe een proces, teelt of systeem in elkaar zit."),
        (CareerTestCatalog.Investigative, false, "Ik vergelijk cijfers of metingen voordat ik een conclusie trek."),
        (CareerTestCatalog.Investigative, true, "Diep nadenken over oorzaken vind ik saai; zeg me gewoon de truc."),
        (CareerTestCatalog.Investigative, false, "Ik stel ‘waarom’-vragen tot ik het mechanisme begrijp."),
        (CareerTestCatalog.Investigative, false, "Ik lees handleidingen of specificaties liever zelf na."),
        (CareerTestCatalog.Investigative, false, "Ik test een aanname klein voordat we hem overal doorvoeren."),
        (CareerTestCatalog.Investigative, true, "Ik vertrouw op gevoel en sla controles of data over."),
        (CareerTestCatalog.Investigative, false, "Ik vind het leuk om een foutpatroon te ontdekken."),
        (CareerTestCatalog.Investigative, false, "Ik kan me lang concentreren op een inhoudelijk vraagstuk."),
        (CareerTestCatalog.Investigative, true, "Onderzoeken voelt als treuzelen; ik wil meteen doen."),
        (CareerTestCatalog.Investigative, false, "Ik gebruik tabellen, logs of keuringslijsten om te sturen."),
        (CareerTestCatalog.Investigative, false, "Ik wil de oorzaak van klachten kennen, niet alleen de symptomen."),
        (CareerTestCatalog.Investigative, false, "Ik leer graag hoe wetgeving, kwaliteit of voedselveiligheid werkt."),
        (CareerTestCatalog.Investigative, true, "Technische of inhoudelijke diepgang schrik ik van af."),
        (CareerTestCatalog.Investigative, false, "Ik splits een vaag probleem op in meetbare stukjes."),
        (CareerTestCatalog.Investigative, false, "Ik houd van werk waarin ik mag uitzoeken en verbeteren."),
        (CareerTestCatalog.Investigative, true, "Ik accepteer ‘dat doen we altijd zo’ zonder door te vragen."),
        (CareerTestCatalog.Investigative, false, "Ik zoek bronnen of collega-experts als ik iets niet weet."),
        (CareerTestCatalog.Investigative, false, "Ik zie graag het verband tussen weer, seizoen, vraag en voorraad."),
        (CareerTestCatalog.Investigative, true, "Cijfers en analyses laat ik liever volledig aan een ander."),
        (CareerTestCatalog.Investigative, false, "Ik documenteer wat ik heb gevonden zodat we ervan leren."),
        (CareerTestCatalog.Investigative, false, "Ik blijf nuchter bij een hype of een snelle ‘oplossing’."),
        (CareerTestCatalog.Investigative, true, "Ik word ongeduldig van uitzoekwerk zonder directe actie."),
        (CareerTestCatalog.Investigative, false, "Ik krijg energie van puzzelen tot het klopt."),

        // Artistic — 25
        (CareerTestCatalog.Artistic, false, "Ik bedenk graag een eigen draai aan hoe iets eruitziet of overkomt."),
        (CareerTestCatalog.Artistic, false, "Ik let op kleur, geur, presentatie of sfeer in het werk."),
        (CareerTestCatalog.Artistic, false, "Ik maak van een saaie taak iets dat er verzorgd uitziet."),
        (CareerTestCatalog.Artistic, true, "Vormgeving en uitstraling interesseert me nauwelijks."),
        (CareerTestCatalog.Artistic, false, "Ik verzin een originele oplossing als het standaardplaatje niet past."),
        (CareerTestCatalog.Artistic, false, "Ik geniet van werk waarin smaak, stijl of verhaal meeweegt."),
        (CareerTestCatalog.Artistic, false, "Ik kan een etalage, bord, arrangement of gerecht aantrekkelijk maken."),
        (CareerTestCatalog.Artistic, true, "Creatieve vrijheid maakt me onrustig; geef me een vast sjabloon."),
        (CareerTestCatalog.Artistic, false, "Ik zie mogelijkheden in restmateriaal, seizoensproduct of restant."),
        (CareerTestCatalog.Artistic, false, "Ik experimenteer met combinaties (smaken, kleuren, indeling)."),
        (CareerTestCatalog.Artistic, true, "Ik vermijd taken waarin ik iets ‘mooi’ of ‘passend’ moet maken."),
        (CareerTestCatalog.Artistic, false, "Ik vertaal een vaag idee van een klant naar iets concreets."),
        (CareerTestCatalog.Artistic, false, "Ik houd van afwisseling in hoe een product of dienst wordt gebracht."),
        (CareerTestCatalog.Artistic, false, "Ik gebruik taal of beeld om iets helder en aantrekkelijk te maken."),
        (CareerTestCatalog.Artistic, true, "Ik vind creatieve input van anderen vooral gedoe."),
        (CareerTestCatalog.Artistic, false, "Ik merk disharmonie in indeling, muziek, licht of styling."),
        (CareerTestCatalog.Artistic, false, "Ik wil ruimte om zelf keuzes te maken in de uitvoering."),
        (CareerTestCatalog.Artistic, true, "Strakke, identieke herhaling zonder eigen inbreng is precies wat ik zoek."),
        (CareerTestCatalog.Artistic, false, "Ik inspireer collega’s met een frisse aanpak of presentatie."),
        (CareerTestCatalog.Artistic, false, "Ik kan een seizoensthema of actie visueel tot leven brengen."),
        (CareerTestCatalog.Artistic, true, "Ik sla over wat ‘er leuk uitziet’ als functioneel genoeg is."),
        (CareerTestCatalog.Artistic, false, "Ik schrijf, teken of formuleer liever zelf dan een standaardtekst te kopiëren."),
        (CareerTestCatalog.Artistic, false, "Ik haal voldoening uit iets unieks afleveren, niet alleen volume."),
        (CareerTestCatalog.Artistic, true, "Kunstzinnige of stylingtaken voelen als hobby, niet als werk."),
        (CareerTestCatalog.Artistic, false, "Ik zie werk ook als beleving voor de gast of klant."),

        // Social — 25
        (CareerTestCatalog.Social, false, "Ik help mensen graag verder, ook als het even duurt."),
        (CareerTestCatalog.Social, false, "Ik voel me op mijn plek in zorg, horeca, retail of begeleiding."),
        (CareerTestCatalog.Social, false, "Ik merk het als iemand zich onprettig voelt en doe er iets mee."),
        (CareerTestCatalog.Social, true, "Andermans problemen op het werk laat ik liever links liggen."),
        (CareerTestCatalog.Social, false, "Ik leg iets geduldig uit tot de ander het snapt."),
        (CareerTestCatalog.Social, false, "Ik werk graag in een team waarin we elkaar steunen."),
        (CareerTestCatalog.Social, false, "Ik kan omgaan met gasten of cliënten die extra aandacht nodig hebben."),
        (CareerTestCatalog.Social, true, "Ik vermijd werk waarin ik anderen moet begeleiden of opvangen."),
        (CareerTestCatalog.Social, false, "Ik bouw vertrouwen op door betrouwbaar en vriendelijk te blijven."),
        (CareerTestCatalog.Social, false, "Ik vind het belangrijk dat iedereen zich welkom voelt."),
        (CareerTestCatalog.Social, true, "Ik wil zo min mogelijk te maken hebben met de gevoelens van anderen."),
        (CareerTestCatalog.Social, false, "Ik kan een conflict tussen mensen sussen zonder partij te kiezen."),
        (CareerTestCatalog.Social, false, "Ik haal energie uit een tevreden klant, leerling of collega."),
        (CareerTestCatalog.Social, false, "Ik pas mijn uitleg aan op leeftijd, taal of ervaring van de ander."),
        (CareerTestCatalog.Social, true, "Service met een lach voelt gespeeld; liever puur transactie."),
        (CareerTestCatalog.Social, false, "Ik zie werk als samen iets voor elkaar krijgen."),
        (CareerTestCatalog.Social, false, "Ik houd rekening met toegankelijkheid en inclusie in de praktijk."),
        (CareerTestCatalog.Social, true, "Ik raak geïrriteerd als mensen extra uitleg of geduld vragen."),
        (CareerTestCatalog.Social, false, "Ik kan nieuws, slecht nieuws of een weigering respectvol brengen."),
        (CareerTestCatalog.Social, false, "Ik werk graag met publiek: gasten, patiënten, leerlingen, shoppers."),
        (CareerTestCatalog.Social, true, "Ik kies taken waarin ik zo min mogelijk met mensen hoef te praten."),
        (CareerTestCatalog.Social, false, "Ik coach een nieuwe collega liever zelf dan het af te schuiven."),
        (CareerTestCatalog.Social, false, "Ik merk groepsdruk en zorg dat niemand buitengesloten wordt."),
        (CareerTestCatalog.Social, true, "Zorg- of klantcontact put me uit; ik wil productiewerk zonder mensen."),
        (CareerTestCatalog.Social, false, "Ik krijg betekenis van werk dat anderen écht helpt."),

        // Enterprising — 25
        (CareerTestCatalog.Enterprising, false, "Ik neem graag het initiatief als niemand anders het doet."),
        (CareerTestCatalog.Enterprising, false, "Ik overtuig anderen van een aanpak, product of aanbieding."),
        (CareerTestCatalog.Enterprising, false, "Ik zie kansen om omzet, bezetting of tempo te verbeteren."),
        (CareerTestCatalog.Enterprising, true, "Leiding nemen of verkopen voelt ongemakkelijk; laat een ander het maar doen."),
        (CareerTestCatalog.Enterprising, false, "Ik stel doelen en trek het team daar naartoe."),
        (CareerTestCatalog.Enterprising, false, "Ik durf een prijs, planning of belofte te onderhandelen."),
        (CareerTestCatalog.Enterprising, false, "Ik blijf actie vragen tot er een besluit is."),
        (CareerTestCatalog.Enterprising, true, "Ik wacht tot ik opdracht krijg in plaats van zelf te starten."),
        (CareerTestCatalog.Enterprising, false, "Ik presenteer een idee kort en krachtig."),
        (CareerTestCatalog.Enterprising, false, "Ik houd van verantwoordelijkheid voor een resultaat, niet alleen een taak."),
        (CareerTestCatalog.Enterprising, true, "Ik vermijd gesprekken waarin ik iets moet ‘verkopen’."),
        (CareerTestCatalog.Enterprising, false, "Ik zet een actie, seizoenspiek of campagne om in concrete stappen."),
        (CareerTestCatalog.Enterprising, false, "Ik spreek mensen aan op afspraken als het resultaat achterblijft."),
        (CareerTestCatalog.Enterprising, false, "Ik zie concurrentie als prikkel, niet als dreiging."),
        (CareerTestCatalog.Enterprising, true, "Ik laat kansen lopen als er risico of afwijzing in zit."),
        (CareerTestCatalog.Enterprising, false, "Ik bouw een netwerk van vaste klanten, telers of leveranciers."),
        (CareerTestCatalog.Enterprising, false, "Ik kan een team opstarten als de leiding even weg is."),
        (CareerTestCatalog.Enterprising, true, "Ik schrik terug van targets, omzet of bezettingscijfers."),
        (CareerTestCatalog.Enterprising, false, "Ik maak een voorstel dat voor beide partijen werkt."),
        (CareerTestCatalog.Enterprising, false, "Ik houd van werk waarin ik mag sturen, werven of organiseren."),
        (CareerTestCatalog.Enterprising, true, "Ik wil geen zichtbare rol naar buiten; hou me op de achtergrond."),
        (CareerTestCatalog.Enterprising, false, "Ik zet teleurstelling om in een volgende pitch of poging."),
        (CareerTestCatalog.Enterprising, false, "Ik zie snel wie ik nodig heb om iets voor elkaar te krijgen."),
        (CareerTestCatalog.Enterprising, true, "Ondernemen in het klein (upsell, extra ronde, extra dienst) is niets voor mij."),
        (CareerTestCatalog.Enterprising, false, "Ik krijg energie van een deal, een volle zaal of een gehaald doel."),

        // Conventional — 25
        (CareerTestCatalog.Conventional, false, "Ik houd van duidelijke procedures, lijsten en vaste volgordes."),
        (CareerTestCatalog.Conventional, false, "Ik werk nauwkeurig met cijfers, codes, data of labels."),
        (CareerTestCatalog.Conventional, false, "Ik richt een administratie of voorraad zo in dat iedereen het terugvindt."),
        (CareerTestCatalog.Conventional, true, "Regels en vaste formats irriteren me; ik improviseer liever altijd."),
        (CareerTestCatalog.Conventional, false, "Ik check of een bestelling, factuur of planning klopt tot op het detail."),
        (CareerTestCatalog.Conventional, false, "Ik werk graag met roosters, slots en voorspelbare diensten."),
        (CareerTestCatalog.Conventional, false, "Ik archiveer of sluit af zodat er later geen chaos is."),
        (CareerTestCatalog.Conventional, true, "Papierwerk, scans en systemen laat ik zo lang mogelijk liggen."),
        (CareerTestCatalog.Conventional, false, "Ik volg een checklist ook als ik de klus al honderd keer deed."),
        (CareerTestCatalog.Conventional, false, "Ik houd van werk waarin structuur belangrijker is dan improvisatie."),
        (CareerTestCatalog.Conventional, true, "Vaste routines maken me rusteloos; ik wil elke dag iets totaal anders."),
        (CareerTestCatalog.Conventional, false, "Ik voer gegevens foutloos in en controleer ze nog een keer."),
        (CareerTestCatalog.Conventional, false, "Ik bewaak voorraadgrenzen, houdbaarheidsdata of minimumaantallen."),
        (CareerTestCatalog.Conventional, false, "Ik maak van een wirwar een overzichtelijke indeling."),
        (CareerTestCatalog.Conventional, true, "Ik vind het overbodig om hetzelfde op twee plekken vast te leggen."),
        (CareerTestCatalog.Conventional, false, "Ik werk prettig met kassa, planningsoftware of orderpicking-systemen."),
        (CareerTestCatalog.Conventional, false, "Ik houd me aan afgesproken formats, ook als ik zelf een andere layout zou kiezen."),
        (CareerTestCatalog.Conventional, true, "Ik gooi informatiestromen door elkaar als dat sneller voelt."),
        (CareerTestCatalog.Conventional, false, "Ik sluit de dag af met een kloppende telling of overdracht."),
        (CareerTestCatalog.Conventional, false, "Ik zie het als mijn taak dat wet- en regelgeving in de uitvoering klopt."),
        (CareerTestCatalog.Conventional, true, "Orde in mappen, bakken of systemen is voor mij bijzaak."),
        (CareerTestCatalog.Conventional, false, "Ik plan terug van deadline naar nu, in plaats van ad hoc te beginnen."),
        (CareerTestCatalog.Conventional, false, "Ik werk liever met vaste kwaliteitsnormen dan met ‘kijk maar’."),
        (CareerTestCatalog.Conventional, true, "Ik vermijd taken waarin ik nauwkeurig moet registreren."),
        (CareerTestCatalog.Conventional, false, "Ik krijg rust van een opgeruimd proces dat elke dienst hetzelfde loopt.")
    ];
}
