namespace Jobsy.Core.Rules;

/// <summary>
/// 150 unique Schwartz workplace value items: 30 per driver, with reverse-keyed items mixed in.
/// </summary>
internal static class DeepAnalysisValuesItems
{
    public const string Autonomy = SchwartzValuesCatalog.Autonomy;
    public const string Connection = SchwartzValuesCatalog.Connection;
    public const string Achievement = SchwartzValuesCatalog.Achievement;
    public const string Stability = SchwartzValuesCatalog.Stability;
    public const string Impact = SchwartzValuesCatalog.Impact;

    public static readonly string[] Domains = SchwartzValuesCatalog.CategoryCodes;

    public static IReadOnlyList<(string Domain, bool Reverse, string Prompt)> All { get; } =
    [
        // Autonomy (Self-Direction / Stimulation) — 30
        (Autonomy, false, "Ik bepaal het liefst zelf de volgorde van mijn taken op een dienst."),
        (Autonomy, false, "Ik zoek graag uitdagingen die me net buiten mijn comfortzone trekken."),
        (Autonomy, true, "Ik werk het best als iemand precies zegt wat ik stap voor stap moet doen."),
        (Autonomy, false, "Ik probeer nieuwe werkwijzen uit als de oude methode traag voelt."),
        (Autonomy, false, "Ik vind het belangrijk om eigen keuzes te maken over hoe ik een klus aanpak."),
        (Autonomy, true, "Vaste routines geven me meer rust dan steeds wisselende werkvormen."),
        (Autonomy, false, "Ik word gemotiveerd door afwisseling en nieuwe verantwoordelijkheden."),
        (Autonomy, false, "Ik durf af te wijken van het handboek als dat veilig en slimmer is."),
        (Autonomy, true, "Ik voel me ongemakkelijk als ik zelf moet beslissen zonder duidelijke leiding."),
        (Autonomy, false, "Ik leer sneller als ik een taak zelf mag inrichten."),
        (Autonomy, false, "Ik zoek actief naar manieren om mijn werk interessanter te maken."),
        (Autonomy, true, "Ik vermijd taken waarbij ik veel moet improviseren."),
        (Autonomy, false, "Ik stel voorstellen doen over hoe we processen kunnen verbeteren."),
        (Autonomy, false, "Ik houd van rollen waarin ik zelf prioriteiten mag stellen."),
        (Autonomy, true, "Te veel vrijheid maakt dat ik het overzicht verlies."),
        (Autonomy, false, "Ik raak onrustig als mijn werk te voorspelbaar wordt."),
        (Autonomy, false, "Ik pak graag een nieuw product, gereedschap of systeem zelf uit."),
        (Autonomy, true, "Ik wacht liever op goedkeuring dan dat ik zelf een besluit neem."),
        (Autonomy, false, "Ik vind het leuk om collega's te laten zien hoe ik iets anders aanpak."),
        (Autonomy, false, "Ik zoek werk waarin ik kan groeien naar meer eigen regie."),
        (Autonomy, true, "Ik vind het prima als mijn taken elk jaar hetzelfde blijven."),
        (Autonomy, false, "Ik combineer ideeën uit verschillende klussen tot een eigen aanpak."),
        (Autonomy, false, "Ik word energiek van een dag met onverwachte problemen om op te lossen."),
        (Autonomy, true, "Ik kies liever voor bekende taken dan voor iets dat ik nog nooit deed."),
        (Autonomy, true, "Ik neem weinig initiatief totdat iemand het expliciet vraagt."),
        (Autonomy, false, "Ik vind het belangrijk om mijn vakinhoudelijk te blijven ontwikkelen."),
        (Autonomy, true, "Ik raak geïrriteerd als de planning tussendoor verandert."),
        (Autonomy, true, "Ik start liever niet aan iets nieuws totdat iemand het heeft goedgekeurd."),
        (Autonomy, false, "Ik voel me thuis in een team dat vertrouwen geeft om zelf te handelen."),
        (Autonomy, true, "Ik volg liever de standaard dan dat ik tijd besteed aan verbeterideeën."),

        // Connection (Benevolence) — 30
        (Connection, false, "Ik help collega's ook als het niet strikt bij mijn eigen taak hoort."),
        (Connection, false, "Ik let op hoe het met mensen om me heen gaat, niet alleen op de klus."),
        (Connection, true, "Ik houd me liever afzijdig van persoonlijke gesprekken op het werk."),
        (Connection, false, "Ik zorg dat nieuwe collega's zich snel welkom voelen."),
        (Connection, false, "Ik geef eerlijk compliment als iemand het goed doet."),
        (Connection, true, "Ik vind teamgevoel minder belangrijk dan mijn eigen resultaat."),
        (Connection, false, "Ik bied aan om een zware dienst over te nemen als een collega het nodig heeft."),
        (Connection, false, "Ik luister rustig voordat ik oplossingen voorstel."),
        (Connection, true, "Ik geef weinig om de sfeer zolang het werk afkomt."),
        (Connection, false, "Ik los spanningen liever op met een gesprek dan met zwijgen."),
        (Connection, false, "Ik denk mee met klanten of gasten alsof het familie is."),
        (Connection, true, "Ik vind het lastig om empathie te tonen als iemand emotioneel is."),
        (Connection, false, "Ik deel kennis graag zodat het hele team beter wordt."),
        (Connection, false, "Ik check bij collega's of de werkdruk haalbaar is."),
        (Connection, true, "Ik werk het liefst alleen zonder veel contact."),
        (Connection, false, "Ik verdedig een collega als iemand onterecht kritiek geeft."),
        (Connection, true, "Ik zie liever niet wat er privé bij collega's speelt."),
        (Connection, false, "Ik geef constructieve feedback op een respectvolle manier."),
        (Connection, false, "Ik vier successen van het team, niet alleen mijn eigen."),
        (Connection, true, "Ik vind het overdreven om elke fout met zachtheid te bespreken."),
        (Connection, false, "Ik merk snel als iemand zich buitengesloten voelt."),
        (Connection, false, "Ik bied hulp aan zonder dat iemand het moet vragen."),
        (Connection, true, "Ik vind het lastig om collega's te troosten als het misgaat."),
        (Connection, true, "Langdurige persoonlijke banden met collega's zoek ik niet op het werk."),
        (Connection, false, "Ik pas mijn tempo aan als een collega extra uitleg nodig heeft."),
        (Connection, true, "Ik kies eerder voor efficiëntie dan voor een warm gesprek."),
        (Connection, false, "Ik zorg dat overdrachten tussen ploegen persoonlijk en duidelijk zijn."),
        (Connection, false, "Ik vind respectvol omgaan met elkaar net zo belangrijk als kwaliteit."),
        (Connection, true, "Ik zie het werk vooral als taken, niet als relaties."),
        (Connection, true, "Ik heb weinig behoefte om collega's persoonlijk te steunen."),

        // Achievement — 30
        (Achievement, false, "Ik wil zien dat mijn inzet meetbaar verschil maakt."),
        (Achievement, false, "Ik stel mezelf hoge doelen en werk er actief naar toe."),
        (Achievement, true, "Ik vind het prima om gemiddeld te presteren zolang het werk af is."),
        (Achievement, false, "Ik ben trots als ik targets of normen overtreff."),
        (Achievement, false, "Ik zoek feedback om sneller beter te worden."),
        (Achievement, true, "Ik vermijd verantwoordelijkheid voor belangrijke resultaten."),
        (Achievement, false, "Ik houd mijn voortgang bij zodat ik kan laten zien wat ik heb bereikt."),
        (Achievement, false, "Ik ga door als het tegenzit tot de klus echt af is."),
        (Achievement, true, "Ik laat promotie of erkenning liever aan anderen."),
        (Achievement, false, "Ik wil het beste teamlid zijn op mijn onderdeel."),
        (Achievement, false, "Ik leer nieuwe vaardigheden om competitiever te worden in mijn vak."),
        (Achievement, true, "Ik vind competitie tussen collega's ongezond."),
        (Achievement, false, "Ik neem extra taken aan als dat mijn groei versnelt."),
        (Achievement, false, "Ik analyseer wat goed ging na een drukke dag."),
        (Achievement, true, "Ik stel doelen liever laag zodat ik zeker slaag."),
        (Achievement, false, "Ik wil dat mijn werk zichtbaar bijdraagt aan de omzet of kwaliteit."),
        (Achievement, false, "Ik zoek rollen waarin prestaties eerlijk worden beloond."),
        (Achievement, true, "Ik werk liever zonder scoreborden of rankings."),
        (Achievement, false, "Ik plan mijn week rond concrete resultaten die ik wil halen."),
        (Achievement, false, "Ik voel me gemotiveerd door een lastig doel dat net haalbaar is."),
        (Achievement, true, "Ik geef snel op als succes niet direct komt."),
        (Achievement, true, "Ik vergelijk mijn prestaties liever niet met eerdere maanden."),
        (Achievement, false, "Ik neem leiding als dat nodig is om het resultaat te redden."),
        (Achievement, true, "Ik vind het niet belangrijk om de beste te zijn."),
        (Achievement, false, "Ik zoek trainingen die mijn carrière vooruithelpen."),
        (Achievement, true, "Ik vermijd taken waar mijn prestatie openlijk wordt beoordeeld."),
        (Achievement, false, "Ik zet door tot een probleem echt opgelost is, niet half."),
        (Achievement, false, "Ik wil dat anderen mijn vakmanschap herkennen."),
        (Achievement, true, "Ik kies liever voor rust dan voor ambitieuze doelen."),
        (Achievement, true, "Erkenning of promotie motiveert mij nauwelijks."),

        // Stability (Security / Tradition) — 30
        (Stability, false, "Ik voel me rustig als afspraken over uren en taken helder zijn."),
        (Stability, false, "Ik werk graag volgens vaste procedures die bewezen veilig zijn."),
        (Stability, true, "Ik vind regels en protocollen vooral belemmerend."),
        (Stability, false, "Ik zoek een werkgever die langdurige zekerheid biedt."),
        (Stability, false, "Ik houd van een vast team en bekende gezichten op de vloer."),
        (Stability, true, "Ik raak onrustig als er weinig verandert in mijn werk."),
        (Stability, false, "Ik controleer liever dubbel dan dat ik risico neem met onbekende stappen."),
        (Stability, false, "Ik waardeer tradities en vaste routines op de werkvloer."),
        (Stability, true, "Ik vind voorspelbaarheid saai."),
        (Stability, false, "Ik wil weten wat er van mij verwacht wordt vóór ik begin."),
        (Stability, false, "Ik voel me veilig met duidelijke hiërarchie en verantwoordelijkheden."),
        (Stability, true, "Ik spring graag van rol naar rol zonder vast patroon."),
        (Stability, false, "Ik plan financieel en praktisch met een vast inkomen in gedachten."),
        (Stability, false, "Ik volg veiligheids- en kwaliteitsregels ook als het druk is."),
        (Stability, true, "Ik neem liever risico dan dat ik vasthoud aan oude gewoonten."),
        (Stability, false, "Ik blijf graag jaren bij een betrouwbare werkgever."),
        (Stability, false, "Ik vind het belangrijk dat afspraken tussen ploegen hetzelfde blijven."),
        (Stability, true, "Ik word ongeduldig van lange instructies en checklists."),
        (Stability, false, "Ik vertrouw op ervaringen uit het verleden om fouten te voorkomen."),
        (Stability, false, "Ik voel me prettig in een organisatie met duidelijke waarden en gewoonten."),
        (Stability, true, "Ik vind verandering van beleid meestal een verbetering."),
        (Stability, true, "Ik maak me weinig zorgen over waar ik over een jaar sta in mijn functie."),
        (Stability, false, "Ik werk het best met een vaste weekplanning."),
        (Stability, true, "Ik accepteer onzekerheid over mijn rooster makkelijk."),
        (Stability, false, "Ik houd vast aan afspraken die het team al jaren goed doen."),
        (Stability, true, "Ik vind het prima als mijn taken elk seizoen anders zijn."),
        (Stability, false, "Ik meld problemen vroeg zodat de rust op de werkvloer bewaard blijft."),
        (Stability, false, "Ik respecteer de manier waarop senior collega's het werk altijd hebben gedaan."),
        (Stability, true, "Ik verwerp routines liever dan dat ik ze volg."),
        (Stability, true, "Vaste contracten en lange planningen boeien mij weinig."),

        // Impact (Universalism) — 30
        (Impact, false, "Ik wil dat mijn werk iets goeds doet voor de samenleving of het milieu."),
        (Impact, false, "Ik kies liever voor een bedrijf met eerlijke en duurzame praktijken."),
        (Impact, true, "Ik vind het niet belangrijk of mijn werk een groter doel dient."),
        (Impact, false, "Ik let op verspilling en probeer die te verminderen op de werkvloer."),
        (Impact, false, "Ik spreek collega's aan op onveilig of oneerlijk gedrag."),
        (Impact, true, "Ik focus alleen op mijn eigen taken, niet op maatschappelijke thema's."),
        (Impact, false, "Ik help graag klanten die kwetsbaar of afhankelijk zijn."),
        (Impact, false, "Ik vind het zinvol om lokale gemeenschappen te ondersteunen via mijn werk."),
        (Impact, true, "Ik vind idealisme op het werk vaak overdreven."),
        (Impact, false, "Ik zoek werk dat bijdraagt aan gezondheid, zorg of onderwijs."),
        (Impact, false, "Ik denk na over de ecologische voetafdruk van onze processen."),
        (Impact, true, "Ik koop of verkoop zonder me druk te maken over herkomst of impact."),
        (Impact, false, "Ik neem verantwoordelijkheid als ons werk negatieve gevolgen heeft."),
        (Impact, false, "Ik respecteer diversiteit en inclusie in het team."),
        (Impact, true, "Ik vind ethische discussies op de werkvloer tijdverspilling."),
        (Impact, false, "Ik meld misstanden ook als dat ongemakkelijk is."),
        (Impact, false, "Ik wil dat onze producten of diensten niemand onnodig schaden."),
        (Impact, true, "Ik laat maatschappelijke kwesties liever aan management over."),
        (Impact, false, "Ik kies leveranciers of partners die netjes met mens en milieu omgaan."),
        (Impact, true, "Ik vind winst belangrijker dan maatschappelijke bijdrage."),
        (Impact, true, "Ik leg klanten liever niet uit hoe we veilig en eerlijk werken."),
        (Impact, false, "Ik zoek verbeteringen die zowel team als buurt ten goede komen."),
        (Impact, true, "Ik vind het niet nodig om na te denken over de lange termijn van ons werk."),
        (Impact, false, "Ik behandel iedereen gelijk, ongeacht achtergrond."),
        (Impact, false, "Ik voel me trots als ons bedrijf openheid geeft over impact."),
        (Impact, true, "Ik negeer liever signalen van unfairness dan dat ik ingrijp."),
        (Impact, false, "Ik wil dat toekomstige generaties profiteren van hoe wij nu werken."),
        (Impact, false, "Ik kies voor eerlijk werk, ook als dat iets minder opbrengt."),
        (Impact, true, "Ik zie mijn baan vooral als inkomen, niet als missie."),
        (Impact, true, "Duurzaamheid of maatschappelijk nut beïnvloedt mijn dagelijkse keuzes nauwelijks.")
    ];
}
