namespace Jobsy.Core.Rules;

/// <summary>
/// 150 unique Big Five / OCEAN Likert items: 30 per trait, with reverse-keyed items mixed in.
/// Workplace wording for Den Haag / Westland matching — not clinical.
/// </summary>
internal static class DeepAnalysisCompetenceItems
{
    public const string Openheid = "Openheid";
    public const string Consciëntieusheid = "Consciëntieusheid";
    public const string Extraversie = "Extraversie";
    public const string Vriendelijkheid = "Vriendelijkheid";
    public const string EmotioneleStabiliteit = "EmotioneleStabiliteit";

    public static readonly string[] Domains =
    [
        Openheid,
        Consciëntieusheid,
        Extraversie,
        Vriendelijkheid,
        EmotioneleStabiliteit
    ];

    public static IReadOnlyList<(string Domain, bool Reverse, string Prompt)> All { get; } =
    [
        // Openheid (O) — 30 unique
        (Openheid, false, "Ik probeer graag een nieuwe werkwijze als de oude vastloopt."),
        (Openheid, false, "Ik lees of kijk uit mezelf bij over hoe ons vak verandert."),
        (Openheid, false, "Ik bedenk meerdere oplossingen voordat ik een keuze maak."),
        (Openheid, true, "Ik blijf het liefst bij de methode die we altijd al gebruiken."),
        (Openheid, false, "Ik vind het leuk om een onbekend systeem of apparaat uit te proberen."),
        (Openheid, false, "Ik zie snel verbanden tussen losse details op de werkvloer."),
        (Openheid, false, "Ik stel vragen als ik de achtergrond van een taak nog niet snap."),
        (Openheid, true, "Nieuwe ideeën van collega’s wijs ik meestal meteen af."),
        (Openheid, false, "Ik experimenteer liever klein dan dat ik wacht op een perfect plan."),
        (Openheid, true, "Ik vermijd taken waarbij ik iets moet leren dat ik nog nooit deed."),
        (Openheid, false, "Ik haal inspiratie uit hoe andere teams hetzelfde werk aanpakken."),
        (Openheid, true, "Verandering in de planning irriteert me meer dan dat het me scherp maakt."),
        (Openheid, false, "Ik combineer kennis uit verschillende klussen tot een betere aanpak."),
        (Openheid, false, "Ik durf een voorstel te doen dat nog niet in het handboek staat."),
        (Openheid, false, "Ik vind het prettig als werk ook ruimte laat voor eigen invulling."),
        (Openheid, true, "Ik volg instructies letterlijk, ook als een slimmere weg zichtbaar is."),
        (Openheid, false, "Ik raak nieuwsgierig als iets technisch of inhoudelijk anders werkt dan verwacht."),
        (Openheid, false, "Ik zoek bewust afwisseling in taken zodat ik alert blijf."),
        (Openheid, false, "Ik kan me inleven in een probleem vanuit het perspectief van de klant."),
        (Openheid, true, "Abstracte uitleg zonder concrete stappen vind ik tijdverspilling."),
        (Openheid, false, "Ik pas mijn aanpak aan als de seizoensdruk of de piek anders is dan vorig jaar."),
        (Openheid, true, "Ik houd niet van brainstormen; zeg me gewoon wat ik moet doen."),
        (Openheid, false, "Ik merk het snel als een proces onnodig omslachtig is geworden."),
        (Openheid, true, "Ik wantrouw verbeteringen totdat iemand anders ze lang heeft gebruikt."),
        (Openheid, false, "Ik leer graag van fouten door te kijken wat we volgende keer anders doen."),
        (Openheid, false, "Ik vind het leuk om een collega een slimmere truc te laten zien."),
        (Openheid, false, "Ik blijf nadenken over hoe we kwaliteit en tempo beter kunnen combineren."),
        (Openheid, true, "Ik sluit me af voor feedback die mijn vaste routine ter discussie stelt."),
        (Openheid, false, "Ik zie kansen in nieuwe producten, teelten of diensten van de vestiging."),
        (Openheid, true, "Ik voel me ongemakkelijk bij taken zonder duidelijk voorbeeld."),

        // Consciëntieusheid (C) — 30 unique
        (Consciëntieusheid, false, "Ik maak af wat ik beloof, ook als de dag tegenzit."),
        (Consciëntieusheid, false, "Ik plan mijn werk zodat deadlines haalbaar blijven."),
        (Consciëntieusheid, false, "Ik controleer details voordat ik iets als klaar doorgeef."),
        (Consciëntieusheid, true, "Ik laat rommel of half afgemaakt werk makkelijk liggen."),
        (Consciëntieusheid, false, "Ik kom op tijd en geef het door als ik te laat dreig te zijn."),
        (Consciëntieusheid, false, "Ik houd bij wat er nog openstaat, zonder dat iemand erom hoeft te vragen."),
        (Consciëntieusheid, false, "Ik werk netjes volgens afgesproken hygiëne, veiligheid of kwaliteit."),
        (Consciëntieusheid, true, "Ik stel lastige klussen uit tot het niet anders meer kan."),
        (Consciëntieusheid, false, "Ik ruim mijn werkplek op zodat de volgende ploeg er meteen mee verder kan."),
        (Consciëntieusheid, true, "Kleine foutjes in cijfers of labels vind ik niet zo belangrijk."),
        (Consciëntieusheid, false, "Ik houd me aan pauze- en werktijden zoals we die hebben afgesproken."),
        (Consciëntieusheid, true, "Als niemand kijkt, sla ik controles of stappen over."),
        (Consciëntieusheid, false, "Ik bereid me voor op een dienst, zodat ik niet hoef te improviseren op basisdingen."),
        (Consciëntieusheid, false, "Ik geef het eerlijk aan als ik een fout heb gemaakt."),
        (Consciëntieusheid, false, "Ik verdeel grote taken in stukken die ik écht afkrijg."),
        (Consciëntieusheid, true, "Ik begin aan iets nieuws terwijl het vorige nog niet af is."),
        (Consciëntieusheid, false, "Ik bewaar overzicht in bestellingen, orders of takenlijsten."),
        (Consciëntieusheid, false, "Ik kom terug op een afspraak, ook als die een week eerder is gemaakt."),
        (Consciëntieusheid, false, "Ik werk door tot de klus veilig en volledig is, niet tot de klok toevallig stopt."),
        (Consciëntieusheid, true, "Administratie of afronden na de klus laat ik het liefst aan een ander."),
        (Consciëntieusheid, false, "Ik houd rekening met piekmomenten en start op tijd met voorbereiden."),
        (Consciëntieusheid, true, "Ik raak het spoor kwijt als er meerdere openstaande taken zijn."),
        (Consciëntieusheid, false, "Ik volg procedures ook als ze saai zijn, omdat ze schade voorkomen."),
        (Consciëntieusheid, true, "Ik zeg ja tegen extra werk terwijl ik weet dat ik het niet netjes aankan."),
        (Consciëntieusheid, false, "Ik check of de klant of collega écht heeft wat er is beloofd."),
        (Consciëntieusheid, false, "Ik houd materialen, gereedschap of voorraad op peil."),
        (Consciëntieusheid, false, "Ik documenteer wat nodig is zodat een vervanger verder kan."),
        (Consciëntieusheid, true, "Ik vind het overdreven om dubbel te controleren bij routinewerk."),
        (Consciëntieusheid, false, "Ik sluit mijn dienst af met een korte check: wat is klaar, wat moet over."),
        (Consciëntieusheid, true, "Ik laat anderen de rommel opruimen die ik tijdens de drukte heb veroorzaakt."),

        // Extraversie (E) — 30 unique
        (Extraversie, false, "Ik krijg energie van samenwerken met collega’s op de vloer."),
        (Extraversie, false, "Ik spreek makkelijk mensen aan, ook als ik ze nog niet ken."),
        (Extraversie, false, "Ik voel me op mijn gemak in een drukke winkel, kas of horecaruimte."),
        (Extraversie, true, "Ik trek me het liefst terug als er veel mensen om me heen zijn."),
        (Extraversie, false, "Ik neem het woord in een korte briefing of overdracht."),
        (Extraversie, false, "Ik help gasten of klanten graag met een open, vriendelijke toon."),
        (Extraversie, false, "Ik zoek aansluiting bij het team tijdens pauzes."),
        (Extraversie, true, "Ik vermijd gesprekken met klanten als een collega het ook kan doen."),
        (Extraversie, false, "Ik kan een groep op sleeptouw nemen als de sfeer stil valt."),
        (Extraversie, true, "Telefoneren of baliewerk kost me onevenredig veel moeite."),
        (Extraversie, false, "Ik vertel duidelijk wat ik nodig heb van anderen om verder te kunnen."),
        (Extraversie, true, "Ik werk het liefst de hele dienst zonder overleg."),
        (Extraversie, false, "Ik stel me voor aan nieuwe collega’s in plaats van te wachten tot zij komen."),
        (Extraversie, false, "Ik houd het tempo erin door anderen mee te nemen in de actie."),
        (Extraversie, false, "Ik durf een grap of luchtige opmerking te maken om de spanning te breken."),
        (Extraversie, true, "In groepsoverleg blijf ik liever stil, ook als ik iets relevants weet."),
        (Extraversie, false, "Ik merk het als een klant of collega aandacht nodig heeft en loop ernaartoe."),
        (Extraversie, false, "Ik kan schakelen tussen kassa, vloer en overleg zonder dat ik dichtklap."),
        (Extraversie, false, "Ik vind het prettig om zichtbaar te zijn in het team."),
        (Extraversie, true, "Onverwacht aangesproken worden haalt me uit mijn concentratie."),
        (Extraversie, false, "Ik bouw snel een werkrelatie op met uitzendkrachten of seizoenscollega’s."),
        (Extraversie, true, "Ik laat liever een e-mail of appje gaan dan een gesprek van twee minuten."),
        (Extraversie, false, "Ik kan een conflict op de vloer benoemen zonder te verdwijnen."),
        (Extraversie, true, "Netwerken of kennismaken op een vestiging voelt als een opgave."),
        (Extraversie, false, "Ik houd van werk waarin contact met mensen een vast onderdeel is."),
        (Extraversie, false, "Ik geef energie aan het team als de dienst lang duurt."),
        (Extraversie, false, "Ik spreek makkelijk af wie wat doet, in plaats van te wachten."),
        (Extraversie, true, "Ik vermijd overdrachten met veel mensen erbij."),
        (Extraversie, false, "Ik voel me thuis in een omgeving met veel prikkels en beweging."),
        (Extraversie, true, "Ik doe alsof ik druk ben om een extra klantgesprek te ontwijken."),

        // Vriendelijkheid (A) — 30 unique
        (Vriendelijkheid, false, "Ik help een collega ook als het niet letterlijk mijn taak is."),
        (Vriendelijkheid, false, "Ik luister eerst naar de ander voordat ik mijn mening geef."),
        (Vriendelijkheid, false, "Ik houd rekening met hoe mijn toon overkomt bij klanten of gasten."),
        (Vriendelijkheid, true, "Als iemand traag is, laat ik merken dat ik daar weinig geduld voor heb."),
        (Vriendelijkheid, false, "Ik zoek een oplossing waar het team verder mee kan, niet alleen ik."),
        (Vriendelijkheid, false, "Ik geef complimenten als iemand iets goed heeft gedaan."),
        (Vriendelijkheid, false, "Ik kan me inleven in een boze of gestreste klant zonder terug te bijten."),
        (Vriendelijkheid, true, "Ik zet mijn eigen belang boven dat van het team als het schuurt."),
        (Vriendelijkheid, false, "Ik deel kennis zodat anderen zelfstandiger worden."),
        (Vriendelijkheid, true, "Ik maak denigrerende opmerkingen als iemand een fout maakt."),
        (Vriendelijkheid, false, "Ik pas mijn tempo aan als een nieuwe collega nog moet inwerken."),
        (Vriendelijkheid, true, "Ik houd wrok als iemand mijn werk heeft overgenomen of bekritiseerd."),
        (Vriendelijkheid, false, "Ik zeg het rustig als ik het ergens niet mee eens ben."),
        (Vriendelijkheid, false, "Ik respecteer verschillende achtergronden en werkstijlen in het team."),
        (Vriendelijkheid, false, "Ik bied hulp aan voordat iemand erom hoeft te vragen."),
        (Vriendelijkheid, true, "Ik trek me weinig aan van hoe mijn gedrag de sfeer beïnvloedt."),
        (Vriendelijkheid, false, "Ik geef ruimte aan stillere collega’s in overleg."),
        (Vriendelijkheid, false, "Ik kan toegeven als de ander een beter punt heeft."),
        (Vriendelijkheid, false, "Ik behandel uitzendkrachten en vast personeel met dezelfde beleefdheid."),
        (Vriendelijkheid, true, "Ik gebruik sarcastische opmerkingen om mijn zin door te drijven."),
        (Vriendelijkheid, false, "Ik let erop dat niemand buiten de groep valt tijdens de dienst."),
        (Vriendelijkheid, true, "Ik laat een collega bewust klem lopen als we om dezelfde taak concurreren."),
        (Vriendelijkheid, false, "Ik houd rekening met fysieke of taalbarrières van anderen."),
        (Vriendelijkheid, true, "Ik vind het zwak als iemand om hulp vraagt bij iets dat ik vanzelfsprekend vind."),
        (Vriendelijkheid, false, "Ik sluit een conflict af met een duidelijke, respectvolle afspraak."),
        (Vriendelijkheid, false, "Ik bescherm de privacy van collega’s in gesprekken met derden."),
        (Vriendelijkheid, false, "Ik zeg dankjewel voor werk dat anders onzichtbaar blijft."),
        (Vriendelijkheid, true, "Ik onderbreek anderen vaak omdat mijn punt urgenter voelt."),
        (Vriendelijkheid, false, "Ik zoek win-win als roosters of taken botsen."),
        (Vriendelijkheid, true, "Ik speel mensen tegen elkaar uit als dat mijn werk makkelijker maakt."),

        // Emotionele stabiliteit (lage neuroticisme) — 30 unique
        (EmotioneleStabiliteit, false, "Ik blijf kalm als het opeens druk wordt."),
        (EmotioneleStabiliteit, false, "Ik herstel snel na een tegenslag of een fout."),
        (EmotioneleStabiliteit, false, "Ik kan meerdere dingen tegelijk aan zonder in paniek te raken."),
        (EmotioneleStabiliteit, true, "Ik pieker lang na over kritiek, ook als die al is opgelost."),
        (EmotioneleStabiliteit, false, "Ik houd overzicht als de planning last-minute wijzigt."),
        (EmotioneleStabiliteit, false, "Ik blijf beleefd als een klant of collega scherp uit de hoek komt."),
        (EmotioneleStabiliteit, false, "Ik slaap een incident af en begin de volgende dienst schoon."),
        (EmotioneleStabiliteit, true, "Ik raak snel van slag als er iets onverwachts gebeurt."),
        (EmotioneleStabiliteit, false, "Ik adem even door voordat ik reageer in een spannend moment."),
        (EmotioneleStabiliteit, true, "Ik voel me snel persoonlijk aangevallen bij gewone werkfeedback."),
        (EmotioneleStabiliteit, false, "Ik blijf functioneren als er een storing, wachtrij of tekort is."),
        (EmotioneleStabiliteit, true, "Ik vermijd lastige gesprekken uit angst dat het uit de hand loopt."),
        (EmotioneleStabiliteit, false, "Ik kan een fout herstellen zonder dat de rest van de dienst instort."),
        (EmotioneleStabiliteit, false, "Ik houd mijn stem en lichaamstaal rustig onder tijdsdruk."),
        (EmotioneleStabiliteit, false, "Ik vraag om hulp als de druk te hoog wordt, in plaats van vast te lopen."),
        (EmotioneleStabiliteit, true, "Ik neem spanning van werk mee naar huis en kom er moeilijk vanaf."),
        (EmotioneleStabiliteit, false, "Ik blijf beslissen als niet alle informatie perfect is."),
        (EmotioneleStabiliteit, false, "Ik accepteer dat piekdagen horen bij dit werk, zonder te blokkeren."),
        (EmotioneleStabiliteit, false, "Ik kan een conflict laten liggen tot het moment om het te bespreken."),
        (EmotioneleStabiliteit, true, "Kleine tegenvallers voelen bij mij al snel als een ramp."),
        (EmotioneleStabiliteit, false, "Ik blijf veilig werken ook als ik gehaast ben."),
        (EmotioneleStabiliteit, true, "Ik word prikkelbaar als ik niet meteen controle over de situatie heb."),
        (EmotioneleStabiliteit, false, "Ik zet een tegenslag om in een concrete volgende stap."),
        (EmotioneleStabiliteit, true, "Ik vermijd verantwoordelijkheid uit angst om de schuld te krijgen."),
        (EmotioneleStabiliteit, false, "Ik houd mijn aandacht bij de taak, ook als er om me heen rumoer is."),
        (EmotioneleStabiliteit, false, "Ik kan ja en nee zeggen zonder daar uren over te twijfelen."),
        (EmotioneleStabiliteit, false, "Ik blijf vriendelijk aan de kassa of balie als de rij lang is."),
        (EmotioneleStabiliteit, true, "Ik sluit me af of bevries als de druk oploopt."),
        (EmotioneleStabiliteit, false, "Ik zie een drukke dienst als een uitdaging die ik aankan."),
        (EmotioneleStabiliteit, true, "Ik heb na een lastige dienst lang last van piekeren of boosheid.")
    ];
}
