using Jobsy.Core.Rules;

namespace Jobsy.Core.Scholen;

/// <summary>Signal a dream-job need can match against (score threshold and/or like chip).</summary>
public enum PupilNeedSignal
{
    RiasecR,
    RiasecI,
    RiasecA,
    RiasecS,
    RiasecE,
    RiasecC,
    CompetenceSamenwerken,
    CompetenceResultaat,
    CompetenceStress,
    CompetenceInnovatie,
    CompetenceExtraversie,
    ValueAutonomy,
    ValueConnection,
    ValueAchievement,
    ValueStability,
    ValueImpact,
    ChipDieren,
    ChipTechniek,
    ChipKoken,
    ChipSport,
    ChipMuziek,
    ChipTekenen,
    ChipComputers,
    ChipBouwen,
    ChipKleineKinderen,
    ChipNatuur,
    ChipProgrammeren,
    ChipRekenen,
    ChipGamen,
    AlwaysCurious // always met — used only as fallback prose, not as a catalog need
}

/// <summary>One of five needs for a dream job. Text via <c>LeerlingDroom.Need.{NeedKey}</c>.</summary>
public sealed record PupilDreamJobNeed(string NeedKey, PupilNeedSignal Signal, int Threshold = 60);

/// <summary>School route for one <see cref="DreamJobCatalog"/> entry.</summary>
public sealed record PupilDreamJobRoute(
    string JobKey,
    IReadOnlyList<PupilDreamJobNeed> Needs,
    /// <summary>3–4 step copy keys under <c>LeerlingDroom.Route.{JobKey}.{n}</c> (title + detail pairs).</summary>
    int RouteStepCount,
    bool HasAltRoute);

/// <summary>Fixed, reviewable dream-job routes for pupils (no AI, no URLs, no employers).</summary>
public static class PupilDreamJobRoutes
{
    public const int NeedCount = 5;
    public const int MinRouteSteps = 3;
    public const int MaxRouteSteps = 4;

    public static readonly IReadOnlyList<PupilDreamJobRoute> All = BuildAll();

    public static PupilDreamJobRoute? TryGet(string? jobKey)
    {
        if (string.IsNullOrWhiteSpace(jobKey))
        {
            return null;
        }

        return All.FirstOrDefault(r =>
            string.Equals(r.JobKey, jobKey, StringComparison.OrdinalIgnoreCase));
    }

    private static IReadOnlyList<PupilDreamJobRoute> BuildAll()
    {
        // Exactly one route per DreamJobCatalog key, catalog order.
        PupilDreamJobRoute R(
            string key,
            PupilDreamJobNeed n1,
            PupilDreamJobNeed n2,
            PupilDreamJobNeed n3,
            PupilDreamJobNeed n4,
            PupilDreamJobNeed n5,
            int steps = 3,
            bool alt = false)
            => new(key, [n1, n2, n3, n4, n5], steps, alt);

        PupilDreamJobNeed N(string needKey, PupilNeedSignal signal, int thr = 60)
            => new(needKey, signal, thr);

        return
        [
            R("dierenarts",
                N("ZorgVoorDieren", PupilNeedSignal.RiasecS),
                N("Nieuwsgierig", PupilNeedSignal.RiasecI),
                N("Nauwkeurig", PupilNeedSignal.CompetenceResultaat),
                N("RustigBlijven", PupilNeedSignal.CompetenceStress),
                N("BiologieInteresse", PupilNeedSignal.ChipDieren),
                alt: true),
            R("piloot",
                N("Concentratie", PupilNeedSignal.CompetenceStress),
                N("Techniek", PupilNeedSignal.RiasecR),
                N("Verantwoordelijk", PupilNeedSignal.CompetenceResultaat),
                N("Ruimte", PupilNeedSignal.ValueAutonomy),
                N("Rekenen", PupilNeedSignal.ChipRekenen)),
            R("advocaat",
                N("Overtuigen", PupilNeedSignal.RiasecE),
                N("Taal", PupilNeedSignal.RiasecS),
                N("Precies", PupilNeedSignal.CompetenceResultaat),
                N("Stress", PupilNeedSignal.CompetenceStress),
                N("Rechtvaardig", PupilNeedSignal.ValueImpact)),
            R("leraar",
                N("Helpen", PupilNeedSignal.RiasecS),
                N("Uitleggen", PupilNeedSignal.CompetenceExtraversie),
                N("Geduld", PupilNeedSignal.CompetenceStress),
                N("Samen", PupilNeedSignal.CompetenceSamenwerken),
                N("Kinderen", PupilNeedSignal.ChipKleineKinderen),
                alt: true),
            R("arts",
                N("Zorgen", PupilNeedSignal.RiasecS),
                N("Uitzoeken", PupilNeedSignal.RiasecI),
                N("Nauwkeurig", PupilNeedSignal.CompetenceResultaat),
                N("Rustig", PupilNeedSignal.CompetenceStress),
                N("Impact", PupilNeedSignal.ValueImpact)),
            R("architect",
                N("Ontwerpen", PupilNeedSignal.RiasecA),
                N("Bouwen", PupilNeedSignal.RiasecR),
                N("Precies", PupilNeedSignal.CompetenceResultaat),
                N("Ideeën", PupilNeedSignal.CompetenceInnovatie),
                N("Tekenen", PupilNeedSignal.ChipTekenen)),
            R("kok",
                N("Maken", PupilNeedSignal.RiasecR),
                N("Creatief", PupilNeedSignal.RiasecA),
                N("Netjes", PupilNeedSignal.CompetenceResultaat),
                N("Drukte", PupilNeedSignal.CompetenceStress),
                N("Koken", PupilNeedSignal.ChipKoken),
                alt: true),
            R("brandweer",
                N("Helpen", PupilNeedSignal.RiasecS),
                N("Aanpakken", PupilNeedSignal.RiasecR),
                N("Team", PupilNeedSignal.CompetenceSamenwerken),
                N("Kalm", PupilNeedSignal.CompetenceStress),
                N("Sport", PupilNeedSignal.ChipSport)),
            R("game-developer",
                N("Computers", PupilNeedSignal.RiasecI),
                N("Creatief", PupilNeedSignal.RiasecA),
                N("Doorzetten", PupilNeedSignal.CompetenceResultaat),
                N("Nieuw", PupilNeedSignal.CompetenceInnovatie),
                N("Gamen", PupilNeedSignal.ChipGamen),
                alt: true),
            R("astronaut",
                N("Techniek", PupilNeedSignal.RiasecI),
                N("Doorzetten", PupilNeedSignal.CompetenceResultaat),
                N("Kalm", PupilNeedSignal.CompetenceStress),
                N("Team", PupilNeedSignal.CompetenceSamenwerken),
                N("Rekenen", PupilNeedSignal.ChipRekenen)),
            R("politie",
                N("Helpen", PupilNeedSignal.RiasecS),
                N("Ordenen", PupilNeedSignal.RiasecC),
                N("Kalm", PupilNeedSignal.CompetenceStress),
                N("Team", PupilNeedSignal.CompetenceSamenwerken),
                N("Rechtvaardig", PupilNeedSignal.ValueStability)),
            R("verpleegkundige",
                N("Zorgen", PupilNeedSignal.RiasecS),
                N("Netjes", PupilNeedSignal.CompetenceResultaat),
                N("Kalm", PupilNeedSignal.CompetenceStress),
                N("Samen", PupilNeedSignal.CompetenceSamenwerken),
                N("Impact", PupilNeedSignal.ValueImpact),
                alt: true),
            R("ondernemer",
                N("Initiatief", PupilNeedSignal.RiasecE),
                N("Ideeën", PupilNeedSignal.CompetenceInnovatie),
                N("Doorzetten", PupilNeedSignal.CompetenceResultaat),
                N("Mensen", PupilNeedSignal.CompetenceExtraversie),
                N("Vrijheid", PupilNeedSignal.ValueAutonomy)),
            R("journalist",
                N("Schrijven", PupilNeedSignal.RiasecA),
                N("Uitzoeken", PupilNeedSignal.RiasecI),
                N("Mensen", PupilNeedSignal.CompetenceExtraversie),
                N("Doorzetten", PupilNeedSignal.CompetenceResultaat),
                N("Impact", PupilNeedSignal.ValueImpact)),
            R("fotograaf",
                N("Creatief", PupilNeedSignal.RiasecA),
                N("Kijken", PupilNeedSignal.RiasecI),
                N("Precies", PupilNeedSignal.CompetenceResultaat),
                N("Vrijheid", PupilNeedSignal.ValueAutonomy),
                N("Tekenen", PupilNeedSignal.ChipTekenen),
                alt: true),
            R("kapper",
                N("Mensen", PupilNeedSignal.RiasecS),
                N("Creatief", PupilNeedSignal.RiasecA),
                N("Handig", PupilNeedSignal.RiasecR),
                N("Netjes", PupilNeedSignal.CompetenceResultaat),
                N("Mode", PupilNeedSignal.ChipTekenen),
                alt: true),
            R("programmeur",
                N("Logica", PupilNeedSignal.RiasecI),
                N("Ordenen", PupilNeedSignal.RiasecC),
                N("Doorzetten", PupilNeedSignal.CompetenceResultaat),
                N("Nieuw", PupilNeedSignal.CompetenceInnovatie),
                N("Computers", PupilNeedSignal.ChipProgrammeren),
                alt: true),
            R("bouwkundige",
                N("Bouwen", PupilNeedSignal.RiasecR),
                N("Uitzoeken", PupilNeedSignal.RiasecI),
                N("Precies", PupilNeedSignal.CompetenceResultaat),
                N("Rekenen", PupilNeedSignal.ChipRekenen),
                N("Techniek", PupilNeedSignal.ChipTechniek),
                alt: true),
            R("tandarts",
                N("Zorgen", PupilNeedSignal.RiasecS),
                N("Precies", PupilNeedSignal.CompetenceResultaat),
                N("Kalm", PupilNeedSignal.CompetenceStress),
                N("Uitzoeken", PupilNeedSignal.RiasecI),
                N("Netjes", PupilNeedSignal.ValueAchievement)),
            R("psycholoog",
                N("Luisteren", PupilNeedSignal.RiasecS),
                N("Uitzoeken", PupilNeedSignal.RiasecI),
                N("Geduld", PupilNeedSignal.CompetenceStress),
                N("Helpen", PupilNeedSignal.ValueConnection),
                N("Impact", PupilNeedSignal.ValueImpact)),
            R("fysiotherapeut",
                N("Helpen", PupilNeedSignal.RiasecS),
                N("Lichaam", PupilNeedSignal.RiasecR),
                N("Uitzoeken", PupilNeedSignal.RiasecI),
                N("Geduld", PupilNeedSignal.CompetenceStress),
                N("Sport", PupilNeedSignal.ChipSport),
                alt: true),
            R("verloskundige",
                N("Zorgen", PupilNeedSignal.RiasecS),
                N("Kalm", PupilNeedSignal.CompetenceStress),
                N("Verantwoordelijk", PupilNeedSignal.CompetenceResultaat),
                N("Helpen", PupilNeedSignal.ValueConnection),
                N("Impact", PupilNeedSignal.ValueImpact)),
            R("apotheker",
                N("Precies", PupilNeedSignal.CompetenceResultaat),
                N("Uitzoeken", PupilNeedSignal.RiasecI),
                N("Ordenen", PupilNeedSignal.RiasecC),
                N("Helpen", PupilNeedSignal.RiasecS),
                N("Netjes", PupilNeedSignal.ValueStability)),
            R("rechter",
                N("Rechtvaardig", PupilNeedSignal.ValueImpact),
                N("Precies", PupilNeedSignal.CompetenceResultaat),
                N("Kalm", PupilNeedSignal.CompetenceStress),
                N("Ordenen", PupilNeedSignal.RiasecC),
                N("Taal", PupilNeedSignal.RiasecS)),
            R("notaris",
                N("Precies", PupilNeedSignal.CompetenceResultaat),
                N("Ordenen", PupilNeedSignal.RiasecC),
                N("Vertrouwen", PupilNeedSignal.ValueStability),
                N("Taal", PupilNeedSignal.RiasecS),
                N("Netjes", PupilNeedSignal.CompetenceInnovatie, 40)),
            R("ingenieur",
                N("Techniek", PupilNeedSignal.RiasecI),
                N("Maken", PupilNeedSignal.RiasecR),
                N("Rekenen", PupilNeedSignal.ChipRekenen),
                N("Doorzetten", PupilNeedSignal.CompetenceResultaat),
                N("Nieuw", PupilNeedSignal.CompetenceInnovatie),
                alt: true),
            R("elektricien",
                N("Handig", PupilNeedSignal.RiasecR),
                N("Precies", PupilNeedSignal.CompetenceResultaat),
                N("Techniek", PupilNeedSignal.ChipTechniek),
                N("Probleem", PupilNeedSignal.CompetenceInnovatie),
                N("Bouwen", PupilNeedSignal.ChipBouwen),
                alt: true),
            R("automonteur",
                N("Handig", PupilNeedSignal.RiasecR),
                N("Uitzoeken", PupilNeedSignal.RiasecI),
                N("Precies", PupilNeedSignal.CompetenceResultaat),
                N("Techniek", PupilNeedSignal.ChipTechniek),
                N("Autos", PupilNeedSignal.ChipBouwen),
                alt: true),
            R("timmerman",
                N("Maken", PupilNeedSignal.RiasecR),
                N("Precies", PupilNeedSignal.CompetenceResultaat),
                N("Bouwen", PupilNeedSignal.ChipBouwen),
                N("Creatief", PupilNeedSignal.RiasecA),
                N("Doorzetten", PupilNeedSignal.ValueAchievement),
                alt: true),
            R("hovenier",
                N("Buiten", PupilNeedSignal.RiasecR),
                N("Natuur", PupilNeedSignal.ChipNatuur),
                N("Maken", PupilNeedSignal.CompetenceResultaat),
                N("Geduld", PupilNeedSignal.CompetenceStress),
                N("Dieren", PupilNeedSignal.ChipDieren),
                alt: true),
            R("bioloog",
                N("Uitzoeken", PupilNeedSignal.RiasecI),
                N("Natuur", PupilNeedSignal.ChipNatuur),
                N("Precies", PupilNeedSignal.CompetenceResultaat),
                N("Nieuwsgierig", PupilNeedSignal.CompetenceInnovatie),
                N("Dieren", PupilNeedSignal.ChipDieren)),
            R("wetenschapper",
                N("Uitzoeken", PupilNeedSignal.RiasecI),
                N("Precies", PupilNeedSignal.CompetenceResultaat),
                N("Doorzetten", PupilNeedSignal.ValueAchievement),
                N("Nieuw", PupilNeedSignal.CompetenceInnovatie),
                N("Rekenen", PupilNeedSignal.ChipRekenen)),
            R("grafisch-ontwerper",
                N("Creatief", PupilNeedSignal.RiasecA),
                N("Computers", PupilNeedSignal.ChipComputers),
                N("Tekenen", PupilNeedSignal.ChipTekenen),
                N("Precies", PupilNeedSignal.CompetenceResultaat),
                N("Ideeën", PupilNeedSignal.CompetenceInnovatie),
                alt: true),
            R("muzikant",
                N("Muziek", PupilNeedSignal.ChipMuziek),
                N("Creatief", PupilNeedSignal.RiasecA),
                N("Doorzetten", PupilNeedSignal.CompetenceResultaat),
                N("Optreden", PupilNeedSignal.CompetenceExtraversie),
                N("Vrijheid", PupilNeedSignal.ValueAutonomy),
                alt: true),
            R("acteur",
                N("Creatief", PupilNeedSignal.RiasecA),
                N("Mensen", PupilNeedSignal.CompetenceExtraversie),
                N("Durf", PupilNeedSignal.RiasecE),
                N("Doorzetten", PupilNeedSignal.CompetenceResultaat),
                N("Theater", PupilNeedSignal.ChipMuziek),
                alt: true),
            R("profsporter",
                N("Sport", PupilNeedSignal.ChipSport),
                N("Doorzetten", PupilNeedSignal.CompetenceResultaat),
                N("Team", PupilNeedSignal.CompetenceSamenwerken),
                N("Kalm", PupilNeedSignal.CompetenceStress),
                N("Presteren", PupilNeedSignal.ValueAchievement)),
            R("personal-trainer",
                N("Sport", PupilNeedSignal.ChipSport),
                N("Helpen", PupilNeedSignal.RiasecS),
                N("Mensen", PupilNeedSignal.CompetenceExtraversie),
                N("Doorzetten", PupilNeedSignal.CompetenceResultaat),
                N("Lichaam", PupilNeedSignal.RiasecR),
                alt: true),
            R("contentmaker",
                N("Creatief", PupilNeedSignal.RiasecA),
                N("Computers", PupilNeedSignal.ChipComputers),
                N("Mensen", PupilNeedSignal.CompetenceExtraversie),
                N("Ideeën", PupilNeedSignal.CompetenceInnovatie),
                N("Filmpjes", PupilNeedSignal.ChipGamen),
                alt: true),
            R("marketeer",
                N("Overtuigen", PupilNeedSignal.RiasecE),
                N("Ideeën", PupilNeedSignal.CompetenceInnovatie),
                N("Mensen", PupilNeedSignal.CompetenceExtraversie),
                N("Ordenen", PupilNeedSignal.RiasecC),
                N("Presteren", PupilNeedSignal.ValueAchievement)),
            R("accountant",
                N("Ordenen", PupilNeedSignal.RiasecC),
                N("Precies", PupilNeedSignal.CompetenceResultaat),
                N("Rekenen", PupilNeedSignal.ChipRekenen),
                N("Betrouwbaar", PupilNeedSignal.ValueStability),
                N("Uitzoeken", PupilNeedSignal.RiasecI),
                alt: true),
            R("makelaar",
                N("Mensen", PupilNeedSignal.RiasecE),
                N("Praten", PupilNeedSignal.CompetenceExtraversie),
                N("Ordenen", PupilNeedSignal.RiasecC),
                N("Doorzetten", PupilNeedSignal.CompetenceResultaat),
                N("Presteren", PupilNeedSignal.ValueAchievement)),
            R("cabinepersoneel",
                N("Mensen", PupilNeedSignal.RiasecS),
                N("Kalm", PupilNeedSignal.CompetenceStress),
                N("Team", PupilNeedSignal.CompetenceSamenwerken),
                N("Netjes", PupilNeedSignal.CompetenceResultaat),
                N("Reizen", PupilNeedSignal.ValueAutonomy)),
            R("militair",
                N("Team", PupilNeedSignal.CompetenceSamenwerken),
                N("Doorzetten", PupilNeedSignal.CompetenceResultaat),
                N("Kalm", PupilNeedSignal.CompetenceStress),
                N("Ordenen", PupilNeedSignal.RiasecC),
                N("Sport", PupilNeedSignal.ChipSport)),
            R("pedagogisch-medewerker",
                N("Kinderen", PupilNeedSignal.ChipKleineKinderen),
                N("Helpen", PupilNeedSignal.RiasecS),
                N("Geduld", PupilNeedSignal.CompetenceStress),
                N("Samen", PupilNeedSignal.CompetenceSamenwerken),
                N("Spelen", PupilNeedSignal.RiasecA),
                alt: true),
            R("dierenverzorger",
                N("Dieren", PupilNeedSignal.ChipDieren),
                N("Zorgen", PupilNeedSignal.RiasecS),
                N("Handig", PupilNeedSignal.RiasecR),
                N("Netjes", PupilNeedSignal.CompetenceResultaat),
                N("Natuur", PupilNeedSignal.ChipNatuur),
                alt: true),
            R("evenementenorganisator",
                N("Organiseren", PupilNeedSignal.RiasecE),
                N("Mensen", PupilNeedSignal.CompetenceExtraversie),
                N("Doorzetten", PupilNeedSignal.CompetenceResultaat),
                N("Creatief", PupilNeedSignal.RiasecA),
                N("Team", PupilNeedSignal.CompetenceSamenwerken),
                alt: true),
            R("data-scientist",
                N("Uitzoeken", PupilNeedSignal.RiasecI),
                N("Rekenen", PupilNeedSignal.ChipRekenen),
                N("Computers", PupilNeedSignal.ChipComputers),
                N("Precies", PupilNeedSignal.CompetenceResultaat),
                N("Ordenen", PupilNeedSignal.RiasecC)),
            R("bakker",
                N("Maken", PupilNeedSignal.RiasecR),
                N("Koken", PupilNeedSignal.ChipKoken),
                N("Netjes", PupilNeedSignal.CompetenceResultaat),
                N("Vroeg", PupilNeedSignal.CompetenceStress),
                N("Creatief", PupilNeedSignal.RiasecA),
                alt: true),
        ];
    }
}
