namespace Jobsy.Web.Localization;

public static class UiStringsWerkgever
{
    public static void MergeAll(
        Dictionary<string, string> nl, Dictionary<string, string> en,
        Dictionary<string, string> pl, Dictionary<string, string> ro,
        Dictionary<string, string> ar)
    {
        void Add(string key, string nlText, string enText, string plText, string roText, string arText)
        {
            nl[key] = nlText;
            en[key] = enText;
            pl[key] = plText;
            ro[key] = roText;
            ar[key] = arText;
        }

        // Terminology overrides (D11) — replace jargon left in UiStringsExtras
        Add("Partner.Usp2", "Funda-model: banenkaart + uitlicht-carrousel", "Funda-style job map + feature carousel", "Model Funda: mapa ofert + karuzela wyróżnień", "Model Funda: hartă joburi + carusel evidențieri", "نموذج Funda: خريطة وظائف + دوّارة التمييز");
        Add("Employer.FilterMatched", "Aangenomen", "Hired", "Zatrudniony", "Angajat", "مُعيَّن");
        Add("Employer.ApplicantsReadOnly", "Je kunt sollicitaties inzien; reageren doet de vestigings- of bedrijfsmanager.", "You can view applications; the branch or company manager responds.", "Możesz przeglądać aplikacje; reaguje menedżer placówki lub firmy.", "Poți vedea aplicațiile; răspunde managerul de filială sau de firmă.", "يمكنك عرض الطلبات؛ يرد مدير الفرع أو الشركة.");
        Add("Register.RoleBranch", "Vestigingsmanager", "Branch manager", "Menedżer placówki", "Manager de filială", "مدير الفرع");

        // Enterprise UI primitives
        Add("EntUi.Loading", "Laden…", "Loading…", "Ładowanie…", "Se încarcă…", "جارٍ التحميل…");
        Add("EntUi.Empty", "Niets gevonden.", "Nothing found.", "Nic nie znaleziono.", "Nimic găsit.", "لم يُعثر على شيء.");
        Add("EntUi.Selected", "{0} geselecteerd", "{0} selected", "{0} zaznaczono", "{0} selectate", "{0} محدد");
        Add("EntUi.ClearSelection", "Selectie wissen", "Clear selection", "Wyczyść zaznaczenie", "Șterge selecția", "مسح التحديد");
        Add("EntUi.FilterSearch", "Zoeken", "Search", "Szukaj", "Căutare", "بحث");
        Add("EntUi.PrevPage", "Vorige", "Previous", "Poprzednia", "Anterior", "السابق");
        Add("EntUi.NextPage", "Volgende", "Next", "Następna", "Următor", "التالي");
        Add("EntUi.PageOf", "Pagina {0} van {1}", "Page {0} of {1}", "Strona {0} z {1}", "Pagina {0} din {1}", "صفحة {0} من {1}");
        Add("EntUi.Pager", "Paginering", "Pagination", "Paginacja", "Paginare", "ترقيم الصفحات");
        Add("EntUi.CloseDrawer", "Sluiten", "Close", "Zamknij", "Închide", "إغلاق");
        Add("EntUi.Actions", "Acties", "Actions", "Akcje", "Acțiuni", "إجراءات");

        // Shell
        Add("WgShell.Werkgever", "Werkgever", "Employer", "Pracodawca", "Angajator", "صاحب العمل");
        Add("WgShell.ScopeChip", "Bereik", "Scope", "Zakres", "Domeniu", "النطاق");
        Add("WgShell.ReadOnly", "Alleen lezen", "Read only", "Tylko odczyt", "Doar citire", "للقراءة فقط");
        Add("WgShell.ReadOnlyHint", "Alleen lezen. Wijzigen doen de vestigings- en bedrijfsmanagers.", "Read only. Branch and company managers make changes.", "Tylko odczyt. Zmiany wprowadzają menedżerowie placówki i firmy.", "Doar citire. Modificările le fac managerii de filială și de firmă.", "للقراءة فقط. يقوم مديرو الفرع والشركة بالتعديل.");
        Add("WgShell.ReadOnlyAction", "Dit doet de vestigings- of bedrijfsmanager", "The branch or company manager does this", "To robi menedżer placówki lub firmy", "Aceasta o face managerul de filială sau de firmă", "يقوم بذلك مدير الفرع أو الشركة");
        Add("WgShell.RmFooter", "Je kijkt mee als regiomanager. Wijzigen doen de vestigings- en bedrijfsmanagers.", "You are viewing as regional manager. Branch and company managers make changes.", "Przeglądasz jako menedżer regionu. Zmiany wprowadzają menedżerowie placówki i firmy.", "Vizualizezi ca manager regional. Modificările le fac managerii de filială și de firmă.", "أنت تعرض كمدير منطقة. يقوم مديرو الفرع والشركة بالتعديل.");
        Add("WgShell.JobMap", "Banenkaart bekijken", "View job map", "Zobacz mapę ofert", "Vezi harta joburilor", "عرض خريطة الوظائف");
        Add("WgShell.Role.BM", "Bedrijfsmanager", "Company manager", "Menedżer firmy", "Manager de firmă", "مدير الشركة");
        Add("WgShell.Role.RM", "Regiomanager", "Regional manager", "Menedżer regionu", "Manager regional", "مدير المنطقة");
        Add("WgShell.Role.VM", "Vestigingsmanager", "Branch manager", "Menedżer placówki", "Manager de filială", "مدير الفرع");
        Add("WgShell.Role.IM", "Intermediair", "Intermediary", "Pośrednik", "Intermediar", "وسيط");
        Add("WgShell.AllBranches", "Alle vestigingen", "All branches", "Wszystkie placówki", "Toate filialele", "كل الفروع");
        Add("WgShell.ScopeDenied", "Je hebt geen toegang tot die vestiging.", "You do not have access to that branch.", "Nie masz dostępu do tej placówki.", "Nu ai acces la acea filială.", "ليس لديك وصول إلى ذلك الفرع.");
        Add("WgShell.Breadcrumb", "Kruimelpad", "Breadcrumb", "Ścieżka nawigacji", "Breadcrumb", "مسار التنقل");
        Add("WgShell.MainNav", "Werkgever navigatie", "Employer navigation", "Nawigacja pracodawcy", "Navigare angajator", "تنقل صاحب العمل");
        Add("WgShell.BottomNav", "Onderste navigatie", "Bottom navigation", "Dolna nawigacja", "Navigare inferioară", "التنقل السفلي");
        Add("WgShell.MoreSheet", "Meer", "More", "Więcej", "Mai mult", "المزيد");
        Add("WgShell.BranchCount", "{0} vestigingen", "{0} branches", "{0} placówek", "{0} filiale", "{0} فروع");
        Add("WgShell.TokensAskBm", "Vraag je bedrijfsmanager om tokens", "Ask your company manager for tokens", "Poproś menedżera firmy o tokeny", "Cere tokenuri managerului de firmă", "اطلب الرموز من مدير شركتك");

        // Nav groups
        Add("WgNav.Group.Overview", "Overzicht", "Overview", "Przegląd", "Prezentare", "نظرة عامة");
        Add("WgNav.Group.Recruitment", "Werving", "Recruitment", "Rekrutacja", "Recrutare", "التوظيف");
        Add("WgNav.Group.Organisation", "Organisatie", "Organisation", "Organizacja", "Organizație", "المنظمة");
        Add("WgNav.Group.MyBranch", "Mijn vestiging", "My branch", "Moja placówka", "Filiala mea", "فرعي");
        Add("WgNav.Group.MyRegion", "Mijn regio", "My region", "Mój region", "Regiunea mea", "منطقتي");
        Add("WgNav.Group.Tokens", "Tokens & facturen", "Tokens & invoices", "Tokeny i faktury", "Tokenuri și facturi", "الرموز والفواتير");
        Add("WgNav.Group.TokenUsage", "Tokenverbruik", "Token usage", "Zużycie tokenów", "Consum tokenuri", "استهلاك الرموز");
        Add("WgNav.Group.More", "Meer", "More", "Więcej", "Mai mult", "المزيد");

        // Nav items
        Add("WgNav.Dashboard", "Dashboard", "Dashboard", "Panel", "Tablou de bord", "لوحة التحكم");
        Add("WgNav.Todo", "Te doen", "To do", "Do zrobienia", "De făcut", "للقيام به");
        Add("WgNav.Signals", "Signalen", "Signals", "Sygnały", "Semnale", "إشارات");
        Add("WgNav.Vacancies", "Vacatures", "Vacancies", "Oferty", "Posturi", "الوظائف");
        Add("WgNav.Applications", "Sollicitaties", "Applications", "Aplikacje", "Aplicații", "الطلبات");
        Add("WgNav.Talentpool", "Talentpool", "Talent pool", "Pula talentów", "Baza de talente", "مجموعة المواهب");
        Add("WgNav.CandidateInsights", "Kandidaatinzichten", "Candidate insights", "Wnioski o kandydatach", "Perspective candidați", "رؤى المرشحين");
        Add("WgNav.BranchesRegions", "Vestigingen & regio's", "Branches & regions", "Placówki i regiony", "Filiale și regiuni", "الفروع والمناطق");
        Add("WgNav.TeamRights", "Team & rechten", "Team & rights", "Zespół i uprawnienia", "Echipă și drepturi", "الفريق والصلاحيات");
        Add("WgNav.CompanyProfile", "Bedrijfsprofiel", "Company profile", "Profil firmy", "Profil firmă", "ملف الشركة");
        Add("WgNav.BranchProfile", "Vestigingsprofiel", "Branch profile", "Profil placówki", "Profil filială", "ملف الفرع");
        Add("WgNav.SalaryTables", "Salaristabellen", "Salary tables", "Tabele wynagrodzeń", "Tabele salariale", "جداول الرواتب");
        Add("WgNav.BalanceBuy", "Saldo & kopen", "Balance & buy", "Saldo i zakup", "Sold și cumpărare", "الرصيد والشراء");
        Add("WgNav.BalanceRequest", "Saldo & aanvragen", "Balance & requests", "Saldo i wnioski", "Sold și cereri", "الرصيد والطلبات");
        Add("WgNav.TokenUsage", "Tokenverbruik", "Token usage", "Zużycie tokenów", "Consum tokenuri", "استهلاك الرموز");
        Add("WgNav.UsagePerBranch", "Verbruik per vestiging", "Usage per branch", "Zużycie per placówka", "Consum pe filială", "الاستهلاك لكل فرع");
        Add("WgNav.Mutations", "Mutaties", "Mutations", "Mutacje", "Mutări", "الحركات");
        Add("WgNav.Invoices", "Facturen", "Invoices", "Faktury", "Facturi", "الفواتير");
        Add("WgNav.Integrations", "Koppelingen", "Integrations", "Integracje", "Integrări", "التكاملات");
        Add("WgNav.Takeovers", "Overnames", "Takeovers", "Przejęcia", "Preluări", "الاستحواذات");
        Add("WgNav.RecruitmentMaterials", "Wervingsmateriaal", "Recruitment materials", "Materiały rekrutacyjne", "Materiale de recrutare", "مواد التوظيف");
        Add("WgNav.PartnerProgram", "Partnerprogramma", "Partner program", "Program partnerski", "Program partener", "برنامج الشركاء");
        Add("WgNav.Clients", "Klanten", "Clients", "Klienci", "Clienți", "العملاء");
        Add("WgNav.Team", "Team", "Team", "Zespół", "Echipă", "الفريق");
        Add("WgNav.MyApplications", "Mijn sollicitaties", "My applications", "Moje aplikacje", "Aplicațiile mele", "طلباتي");
        Add("WgNav.More", "Meer", "More", "Więcej", "Mai mult", "المزيد");

        // Tabs
        Add("WgTabs.Search", "Zoeken", "Search", "Szukaj", "Căutare", "بحث");
        Add("WgTabs.Contacts", "Contactverzoeken", "Contact requests", "Prośby o kontakt", "Cereri de contact", "طلبات التواصل");
        Add("WgTabs.Profile", "Profiel", "Profile", "Profil", "Profil", "الملف");
        Add("WgTabs.Culture", "Cultuur", "Culture", "Kultura", "Cultură", "الثقافة");
        Add("WgTabs.Regions", "Regio's", "Regions", "Regiony", "Regiuni", "المناطق");

        // Dashboard (02)
        Add("WgDash.Title.Rm", "Regio dashboard", "Region dashboard", "Panel regionu", "Tablou regional", "لوحة المنطقة");
        Add("WgDash.Lead.Bm", "{0} · {1} vestigingen in {2} regio's · laatste {3}", "{0} · {1} branches in {2} regions · last {3}", "{0} · {1} placówek w {2} regionach · ostatnie {3}", "{0} · {1} filiale în {2} regiuni · ultimele {3}", "{0} · {1} فروع في {2} مناطق · آخر {3}");
        Add("WgDash.Lead.Rm", "{0} · {1} vestigingen · laatste {2}", "{0} · {1} branches · last {2}", "{0} · {1} placówek · ostatnie {2}", "{0} · {1} filiale · ultimele {2}", "{0} · {1} فروع · آخر {2}");
        Add("WgDash.Lead.Vm", "{0} · laatste {1}", "{0} · last {1}", "{0} · ostatnie {1}", "{0} · ultimele {1}", "{0} · آخر {1}");
        Add("WgDash.Lead.Intermediary", "KPI’s over alle opdrachtgevers. Detail per bedrijf staat in Bedrijvenoverzicht.", "KPIs across all clients. Per-company detail is in Clients.", "KPI dla wszystkich klientów. Szczegóły per firma w Klienci.", "KPI pentru toți clienții. Detaliile pe firmă sunt la Clienți.", "مؤشرات لكل العملاء. التفاصيل لكل شركة في العملاء.");
        Add("WgDash.Export", "Exporteren", "Export", "Eksportuj", "Exportă", "تصدير");
        Add("WgDash.PostVacancy", "Vacature plaatsen", "Post vacancy", "Opublikuj ofertę", "Publică post", "نشر وظيفة");
        Add("WgDash.TodoTitle", "Te doen", "To do", "Do zrobienia", "De făcut", "للقيام به");
        Add("WgDash.SignalsTitle", "Signalen in je regio", "Signals in your region", "Sygnały w regionie", "Semnale în regiune", "إشارات في منطقتك");
        Add("WgDash.ForInfo", "Ter info", "For info", "Informacyjnie", "Informativ", "للعلم");
        Add("WgDash.ViewAll", "Alles bekijken", "View all", "Zobacz wszystko", "Vezi tot", "عرض الكل");
        Add("WgDash.TodoEmpty", "Niets te doen. Alles loopt.", "Nothing to do. Everything is on track.", "Nic do zrobienia. Wszystko działa.", "Nimic de făcut. Totul merge.", "لا شيء للقيام به. كل شيء على ما يرام.");
        Add("WgDash.Funnel", "Wervingstrechter", "Recruitment funnel", "Lejek rekrutacji", "Pâlnie recrutare", "قمع التوظيف");
        Add("WgDash.Funnel.Applications", "Sollicitaties", "Applications", "Aplikacje", "Aplicații", "الطلبات");
        Add("WgDash.Funnel.Accepted", "Geaccepteerd", "Accepted", "Zaakceptowane", "Acceptate", "مقبولة");
        Add("WgDash.Funnel.Invited", "Uitgenodigd", "Invited", "Zaproszeni", "Invitați", "مدعوون");
        Add("WgDash.Funnel.Hired", "Aangenomen", "Hired", "Zatrudnieni", "Angajați", "مُعيَّنون");
        Add("WgDash.Branches", "Vestigingen", "Branches", "Placówki", "Filiale", "الفروع");
        Add("WgDash.BranchesRegion", "Vestigingen in je regio", "Branches in your region", "Placówki w regionie", "Filiale în regiune", "فروع في منطقتك");
        Add("WgDash.BranchesBehind", "Vestigingen met achterstand", "Branches behind", "Placówki z opóźnieniem", "Filiale în întârziere", "فروع متأخرة");
        Add("WgDash.NoBehind", "Geen vestigingen met achterstand.", "No branches behind.", "Brak placówek z opóźnieniem.", "Nicio filială în întârziere.", "لا فروع متأخرة.");
        Add("WgDash.AllBranches", "Alle {0} vestigingen", "All {0} branches", "Wszystkie {0} placówki", "Toate cele {0} filiale", "كل الـ {0} فروع");
        Add("WgDash.AllBranchesShort", "Alle {0}", "All {0}", "Wszystkie {0}", "Toate {0}", "الكل {0}");
        Add("WgDash.Col.Branch", "Vestiging", "Branch", "Placówka", "Filială", "الفرع");
        Add("WgDash.Col.Live", "Live vac.", "Live jobs", "Live oferty", "Posturi live", "وظائف مباشرة");
        Add("WgDash.Col.New", "Nieuw", "New", "Nowe", "Noi", "جديد");
        Add("WgDash.Col.FirstResponse", "1e reactie", "1st response", "1. odpowiedź", "1. răspuns", "أول رد");
        Add("WgDash.Col.Status", "Status", "Status", "Status", "Status", "الحالة");
        Add("WgDash.Status.OpSchema", "Op schema", "On track", "Zgodnie z planem", "În grafic", "وفق الجدول");
        Add("WgDash.Status.Aandacht", "Aandacht", "Attention", "Uwaga", "Atenție", "انتباه");
        Add("WgDash.Status.Achterstand", "Achterstand", "Behind", "Opóźnienie", "Întârziere", "تأخر");
        Add("WgDash.Kpi.ActiveVacancies", "Actieve vacatures", "Active vacancies", "Aktywne oferty", "Posturi active", "وظائف نشطة");
        Add("WgDash.Kpi.NewApplications", "Nieuwe sollicitaties", "New applications", "Nowe aplikacje", "Aplicații noi", "طلبات جديدة");
        Add("WgDash.Kpi.FirstResponse", "Gem. eerste reactie", "Avg. first response", "Śr. pierwsza odpowiedź", "Răspuns mediu", "متوسط أول رد");
        Add("WgDash.Kpi.FirstResponseShort", "Eerste reactie", "First response", "Pierwsza odpowiedź", "Primul răspuns", "أول رد");
        Add("WgDash.Kpi.FirstResponseTip", "Te weinig reacties om te meten", "Too few responses to measure", "Za mało odpowiedzi do pomiaru", "Prea puține răspunsuri", "ردود قليلة جداً للقياس");
        Add("WgDash.Kpi.Hired", "Aangenomen", "Hired", "Zatrudnieni", "Angajați", "مُعيَّنون");
        Add("WgDash.Kpi.TokenBalance", "Tokensaldo", "Token balance", "Saldo tokenów", "Sold tokenuri", "رصيد الرموز");
        Add("WgDash.Kpi.TokenUsage", "Tokenverbruik regio", "Region token usage", "Zużycie tokenów regionu", "Consum tokenuri regiune", "استهلاك رموز المنطقة");
        Add("WgDash.Kpi.TokenUsageShort", "Tokenverbruik", "Token usage", "Zużycie tokenów", "Consum tokenuri", "استهلاك الرموز");
        Add("WgDash.Kpi.TokenUsageValue", "{0} van {1} toegewezen", "{0} of {1} allocated", "{0} z {1} przydzielonych", "{0} din {1} alocate", "{0} من {1} مخصصة");
        Add("WgDash.Kpi.Runway", "± {0} weken bij huidig verbruik", "± {0} weeks at current usage", "± {0} tyg. przy obecnym zużyciu", "± {0} săpt. la consum curent", "± {0} أسابيع بالاستهلاك الحالي");
        Add("WgDash.Kpi.RunwayShort", "± {0} weken", "± {0} weeks", "± {0} tyg.", "± {0} săpt.", "± {0} أسابيع");
        Add("WgDash.Days", "{0:0.#} d", "{0:0.#} d", "{0:0.#} d", "{0:0.#} z", "{0:0.#} ي");
        Add("WgDash.Faster", "{0} d sneller", "{0} d faster", "{0} d szybciej", "{0} z mai rapid", "{0} ي أسرع");
        Add("WgDash.Slower", "{0} d langzamer", "{0} d slower", "{0} d wolniej", "{0} z mai lent", "{0} ي أبطأ");
        Add("WgDash.Period.7d", "7 d", "7 d", "7 d", "7 z", "7 ي");
        Add("WgDash.Period.30d", "30 d", "30 d", "30 d", "30 z", "30 ي");
        Add("WgDash.Period.90d", "90 d", "90 d", "90 d", "90 z", "90 ي");
        Add("WgDash.Raamflyer", "Raamflyer", "Window flyer", "Ulotka witryny", "Flyer vitrină", "منشور الواجهة");
        Add("WgDash.RaamflyerHint", "Download wervingsmateriaal voor je vestiging.", "Download recruitment materials for your branch.", "Pobierz materiały rekrutacyjne dla placówki.", "Descarcă materiale de recrutare pentru filială.", "حمّل مواد التوظيف لفرعك.");

        // Te doen
        Add("WgTodo.Lead", "Wat aandacht vraagt in je huidige bereik.", "What needs attention in your current scope.", "Co wymaga uwagi w bieżącym zakresie.", "Ce necesită atenție în domeniul curent.", "ما يحتاج انتباهاً في نطاقك الحالي.");
        Add("WgTodo.Filters", "Filters", "Filters", "Filtry", "Filtre", "عوامل التصفية");
        Add("WgTodo.Filter.All", "Alles", "All", "Wszystko", "Tot", "الكل");
        Add("WgTodo.Severity.Danger", "Urgent", "Urgent", "Pilne", "Urgent", "عاجل");
        Add("WgTodo.Severity.Warning", "Aandacht", "Attention", "Uwaga", "Atenție", "انتباه");
        Add("WgTodo.Severity.Info", "Ter info", "For info", "Informacyjnie", "Informativ", "للعلم");
        Add("WgTodo.Kind.PublishRequests", "Publicatieaanvragen", "Publish requests", "Wnioski o publikację", "Cereri publicare", "طلبات النشر");
        Add("WgTodo.Kind.ApplicationsOverdue", "Sollicitaties > 48 uur", "Applications > 48h", "Aplikacje > 48 godz.", "Aplicații > 48 ore", "طلبات > 48 ساعة");
        Add("WgTodo.Kind.VacanciesExpiring", "Vacatures verlopen", "Vacancies expiring", "Oferty wygasają", "Posturi expiră", "وظائف تنتهي");
        Add("WgTodo.Kind.LowTokens", "Lage tokensaldo’s", "Low token balances", "Niskie salda tokenów", "Solduri tokenuri mici", "أرصدة رموز منخفضة");
        Add("WgTodo.Kind.NoManager", "Zonder vestigingsmanager", "Without branch manager", "Bez menedżera placówki", "Fără manager de filială", "بدون مدير فرع");
        Add("WgTodo.Kind.Takeovers", "Overnames", "Takeovers", "Przejęcia", "Preluări", "الاستحواذات");
        Add("WgTodo.Action.Beoordelen", "Beoordelen", "Review", "Oceń", "Evaluează", "مراجعة");
        Add("WgTodo.Action.Bekijken", "Bekijken", "View", "Zobacz", "Vezi", "عرض");
        Add("WgTodo.Action.Verlengen", "Verlengen", "Extend", "Przedłuż", "Prelungește", "تمديد");
        Add("WgTodo.Action.TokensVerdelen", "Tokens verdelen", "Allocate tokens", "Przydziel tokeny", "Alocă tokenuri", "توزيع الرموز");
        Add("WgTodo.Action.TokensAanvragen", "Tokens aanvragen", "Request tokens", "Poproś o tokeny", "Cere tokenuri", "طلب رموز");
        Add("WgTodo.Action.IemandUitnodigen", "Iemand uitnodigen", "Invite someone", "Zaproś kogoś", "Invită pe cineva", "دعوة شخص");
        Add("WgTodo.PublishRequests.Title", "{0} publicatieaanvragen wachten op jouw goedkeuring", "{0} publish requests await your approval", "{0} wnioski o publikację czekają na zatwierdzenie", "{0} cereri de publicare așteaptă aprobarea", "{0} طلبات نشر بانتظار موافقتك");
        Add("WgTodo.PublishRequests.Meta", "{0}", "{0}", "{0}", "{0}", "{0}");
        Add("WgTodo.PublishRequests.MetaRm", "De bedrijfsmanager keurt goed · {0}", "The company manager approves · {0}", "Menedżer firmy zatwierdza · {0}", "Managerul de firmă aprobă · {0}", "مدير الشركة يوافق · {0}");
        Add("WgTodo.PublishRequests.MetaVm", "Wacht op bedrijfsmanager · {0}", "Waiting for company manager · {0}", "Czeka na menedżera firmy · {0}", "Așteaptă managerul de firmă · {0}", "بانتظار مدير الشركة · {0}");
        Add("WgTodo.ApplicationsOverdue.Title", "{0} sollicitaties langer dan 48 uur zonder reactie", "{0} applications without a response for over 48 hours", "{0} aplikacji bez odpowiedzi ponad 48 godzin", "{0} aplicații fără răspuns de peste 48 de ore", "{0} طلبات بلا رد لأكثر من 48 ساعة");
        Add("WgTodo.ApplicationsOverdue.Meta", "{0}", "{0}", "{0}", "{0}", "{0}");
        Add("WgTodo.VacanciesExpiring.Title", "{0} vacatures verlopen binnen 7 dagen", "{0} vacancies expire within 7 days", "{0} ofert wygasa w ciągu 7 dni", "{0} posturi expiră în 7 zile", "{0} وظائف تنتهي خلال 7 أيام");
        Add("WgTodo.VacanciesExpiring.Meta", "{0}", "{0}", "{0}", "{0}", "{0}");
        Add("WgTodo.LowTokens.Title", "{0} heeft nog {1} tokens", "{0} still has {1} tokens", "{0} ma jeszcze {1} tokenów", "{0} mai are {1} tokenuri", "{0} لديه {1} رموز متبقية");
        Add("WgTodo.LowTokens.Meta", "Tokens verdelen naar vestigingen met tekort.", "Allocate tokens to branches that are short.", "Przydziel tokeny placówkom z niedoborem.", "Alocă tokenuri filialelor cu deficit.", "وزّع الرموز على الفروع الناقصة.");
        Add("WgTodo.LowTokens.MetaVm", "Vraag tokens aan bij je bedrijfsmanager.", "Ask your company manager for tokens.", "Poproś menedżera firmy o tokeny.", "Cere tokenuri managerului de firmă.", "اطلب الرموز من مدير شركتك.");
        Add("WgTodo.NoManager.Title", "{0} heeft nog geen vestigingsmanager", "{0} still has no branch manager", "{0} nie ma jeszcze menedżera placówki", "{0} nu are încă manager de filială", "{0} ليس لديه مدير فرع بعد");
        Add("WgTodo.NoManager.Meta", "Nodig iemand uit voor deze vestiging.", "Invite someone for this branch.", "Zaproś kogoś do tej placówki.", "Invită pe cineva pentru această filială.", "ادعُ شخصاً لهذا الفرع.");
        Add("WgTodo.Takeovers.Title", "Overnameverzoek voor vestiging {0}", "Takeover request for branch {0}", "Wniosek o przejęcie placówki {0}", "Cerere de preluare pentru filiala {0}", "طلب استحواذ على الفرع {0}");
        Add("WgTodo.Takeovers.Meta", "Aangevraagd op {0}", "Requested on {0}", "Złożono {0}", "Solicitat pe {0}", "طُلب في {0}");

        // Vacatures (03) — terminology overrides + page copy
        Add("Employer.Highlight", "Uitlichten", "Feature", "Wyróżnienie", "Evidențiere", "تمييز");
        Add("Employer.PushBom", "Pushbericht naar kandidaten", "Push message", "Powiadomienie do kandydatów", "Notificare către candidați", "إشعار للمرشحين");
        Add("Employer.Extend", "Verlengen", "Extend", "Przedłuż", "Prelungește", "تمديد");
        Add("VacancyAction.Highlight", "Uitlichten", "Feature", "Wyróżnij", "Evidențiază", "تمييز");
        Add("VacancyAction.PushBom", "Pushbericht naar kandidaten", "Push message", "Powiadomienie do kandydatów", "Notificare către candidați", "إشعار للمرشحين");
        Add("VacancyAction.Extend", "Verlengen", "Extend", "Przedłuż", "Prelungește", "تمديد");
        Add("VacancyAction.Deactivate", "Deactiveren", "Deactivate", "Dezaktywuj", "Dezactivează", "إلغاء التفعيل");
        Add("VacancyAction.Duplicate", "Dupliceren", "Duplicate", "Duplikuj", "Duplică", "تكرار");
        Add("VacancyAction.Reactivate", "Heropenen", "Reopen", "Ponów", "Redeschide", "إعادة فتح");
        Add("VacancyAction.Approve", "Goedkeuren", "Approve", "Zatwierdź", "Aprobă", "موافقة");
        Add("VacancyAction.Finish", "Afmaken", "Finish", "Dokończ", "Finalizează", "إكمال");
        Add("VacancyAction.Visibility", "Zichtbaarheid & kosten", "Visibility & costs", "Widoczność i koszty", "Vizibilitate și costuri", "الظهور والتكاليف");
        Add("VacancyAction.Applications", "Sollicitaties", "Applications", "Aplikacje", "Aplicații", "الطلبات");
        Add("PushBom.Title", "Pushbericht naar kandidaten versturen?", "Send push message?", "Wysłać powiadomienie do kandydatów?", "Trimiți notificare către candidați?", "إرسال إشعار للمرشحين؟");
        Add("PushBom.Confirm", "Versturen", "Send", "Wyślij", "Trimite", "إرسال");
        Add("Employer.PublishOptionsTitle", "Zichtbaarheid & kosten", "Visibility & costs", "Widoczność i koszty", "Vizibilitate și costuri", "الظهور والتكاليف");

        Add("WgVac.Lead.Bm", "Alle vacatures van je {0} vestigingen.", "All vacancies across your {0} branches.", "Wszystkie oferty z {0} placówek.", "Toate posturile din cele {0} filiale.", "كل الوظائف في فروعك الـ {0}.");
        Add("WgVac.Lead.Rm", "Vacatures in regio {0}.", "Vacancies in region {0}.", "Oferty w regionie {0}.", "Posturi în regiunea {0}.", "وظائف في منطقة {0}.");
        Add("WgVac.Lead.Vm", "Vacatures van vestiging {0}.", "Vacancies of branch {0}.", "Oferty placówki {0}.", "Posturi ale filialei {0}.", "وظائف فرع {0}.");
        Add("WgVac.Export", "Exporteren", "Export", "Eksportuj", "Exportă", "تصدير");
        Add("WgVac.Post", "Vacature plaatsen", "Post vacancy", "Opublikuj ofertę", "Publică post", "نشر وظيفة");
        Add("WgVac.Tab.All", "Alle", "All", "Wszystkie", "Toate", "الكل");
        Add("WgVac.Tab.Active", "Actief", "Active", "Aktywne", "Active", "نشط");
        Add("WgVac.Tab.Pending", "Wacht op goedkeuring", "Awaiting approval", "Czeka na zatwierdzenie", "Așteaptă aprobare", "بانتظار الموافقة");
        Add("WgVac.Tab.Draft", "Concept", "Draft", "Szkic", "Concept", "مسودة");
        Add("WgVac.Tab.Expiring", "Verloopt binnenkort", "Expires soon", "Wkrótce wygasa", "Expiră curând", "تنتهي قريباً");
        Add("WgVac.Tab.Closed", "Gesloten", "Closed", "Zamknięte", "Închise", "مغلقة");
        Add("WgVac.Search", "Zoek op titel of nummer", "Search by title or number", "Szukaj po tytule lub numerze", "Caută după titlu sau număr", "ابحث بالعنوان أو الرقم");
        Add("WgVac.Filter.Branch", "Vestiging", "Branch", "Placówka", "Filială", "الفرع");
        Add("WgVac.Filter.Region", "Regio", "Region", "Region", "Regiune", "المنطقة");
        Add("WgVac.Filter.Type", "Type", "Type", "Typ", "Tip", "النوع");
        Add("WgVac.Filter.SalaryTable", "Salaristabel", "Salary table", "Tabela wynagrodzeń", "Tabel salarial", "جدول الرواتب");
        Add("WgVac.Filter.PostedBy", "Geplaatst door", "Posted by", "Opublikował", "Publicat de", "نُشر بواسطة");
        Add("WgVac.Columns", "Kolommen", "Columns", "Kolumny", "Coloane", "الأعمدة");
        Add("WgVac.Col.Vacancy", "Vacature", "Vacancy", "Oferta", "Post", "الوظيفة");
        Add("WgVac.Col.Status", "Status", "Status", "Status", "Status", "الحالة");
        Add("WgVac.Col.Applications", "Sollicitaties", "Applications", "Aplikacje", "Aplicații", "الطلبات");
        Add("WgVac.Col.Views", "Weergaven", "Views", "Wyświetlenia", "Vizualizări", "المشاهدات");
        Add("WgVac.Col.OnlineUntil", "Online tot", "Online until", "Online do", "Online până", "متاح حتى");
        Add("WgVac.Col.Visibility", "Zichtbaarheid", "Visibility", "Widoczność", "Vizibilitate", "الظهور");
        Add("WgVac.Status.Active", "Actief", "Active", "Aktywna", "Activă", "نشط");
        Add("WgVac.Status.Pending", "Wacht op goedkeuring", "Awaiting approval", "Czeka na zatwierdzenie", "Așteaptă aprobare", "بانتظار الموافقة");
        Add("WgVac.Status.PendingVm", "Wacht op bedrijfsmanager", "Waiting for company manager", "Czeka na menedżera firmy", "Așteaptă managerul de firmă", "بانتظار مدير الشركة");
        Add("WgVac.Status.Draft", "Concept", "Draft", "Szkic", "Concept", "مسودة");
        Add("WgVac.Status.Archived", "Inactief", "Inactive", "Nieaktywna", "Inactivă", "غير نشط");
        Add("WgVac.Status.Fulfilled", "Vervuld", "Filled", "Obsadzona", "Ocupat", "مُشغَل");
        Add("WgVac.Visibility.Highlighted", "Uitgelicht", "Featured", "Wyróżniona", "Evidențiat", "مميز");
        Add("WgVac.Visibility.Push", "Pushbericht", "Push", "Powiadomienie", "Notificare", "إشعار");
        Add("WgVac.Info.PendingBm", "{0} vestigingen vragen tokens aan om te publiceren. Goedkeuren boekt de tokens af van het centrale saldo ({1}).", "{0} branches request tokens to publish. Approving deducts from the central balance ({1}).", "{0} placówek prosi o tokeny do publikacji. Zatwierdzenie pobiera tokeny z salda centralnego ({1}).", "{0} filiale cer tokenuri pentru publicare. Aprobarea scade din soldul central ({1}).", "{0} فروع تطلب رموزاً للنشر. الموافقة تخصم من الرصيد المركزي ({1}).");
        Add("WgVac.Info.ShowRequests", "Alleen aanvragen tonen", "Show requests only", "Pokaż tylko wnioski", "Arată doar cererile", "عرض الطلبات فقط");
        Add("WgVac.Info.VmTokens", "Vestiging {0} heeft {1} tokens, toegewezen door de bedrijfsmanager. Publiceer je boven dit saldo, dan gaat de vacature als aanvraag naar de bedrijfsmanager.", "Branch {0} has {1} tokens, allocated by the company manager. If you publish above this balance, the vacancy becomes a request to the company manager.", "Placówka {0} ma {1} tokenów, przydzielonych przez menedżera firmy. Publikacja powyżej salda staje się wnioskiem do menedżera firmy.", "Filiala {0} are {1} tokenuri, alocate de managerul de firmă. Dacă publici peste sold, postul devine cerere către managerul de firmă.", "فرع {0} لديه {1} رمزاً مخصصاً من مدير الشركة. النشر فوق الرصيد يحوّل الوظيفة إلى طلب لمدير الشركة.");
        Add("WgVac.Info.ViewTokens", "Tokens bekijken", "View tokens", "Zobacz tokeny", "Vezi tokenuri", "عرض الرموز");
        Add("WgVac.RequestLine", "Aanvraag {0} · {1} tokens", "Request {0} · {1} tokens", "Wniosek {0} · {1} tokenów", "Cerere {0} · {1} tokenuri", "طلب {0} · {1} رموز");
        Add("WgVac.RequestLineAnon", "Aanvraag · {0} tokens", "Request · {0} tokens", "Wniosek · {0} tokenów", "Cerere · {0} tokenuri", "طلب · {0} رموز");
        Add("WgVac.DraftIncomplete", "Nog {0} velden invullen", "{0} fields left", "Jeszcze {0} pól", "Mai {0} câmpuri", "متبقي {0} حقول");
        Add("WgVac.DraftReady", "Klaar om te publiceren", "Ready to publish", "Gotowe do publikacji", "Gata de publicare", "جاهز للنشر");
        Add("WgVac.Bulk.Extend", "Verlengen · {0} tokens", "Extend · {0} tokens", "Przedłuż · {0} tokenów", "Prelungește · {0} tokenuri", "تمديد · {0} رموز");
        Add("WgVac.Bulk.Highlight", "Uitlichten · {0} tokens", "Feature · {0} tokens", "Wyróżnij · {0} tokenów", "Evidențiază · {0} tokenuri", "تمييز · {0} رموز");
        Add("WgVac.Bulk.Duplicate", "Dupliceren", "Duplicate", "Duplikuj", "Duplică", "تكرار");
        Add("WgVac.Bulk.Deactivate", "Deactiveren", "Deactivate", "Dezaktywuj", "Dezactivează", "إلغاء التفعيل");
        Add("WgVac.Bulk.Summary", "{0} gelukt, {1} niet gelukt", "{0} succeeded, {1} failed", "{0} udało się, {1} nie", "{0} reușite, {1} eșuate", "{0} نجحت، {1} فشلت");
        Add("WgVac.Confirm.ApproveTitle", "Publicatieaanvraag goedkeuren?", "Approve publication request?", "Zatwierdzić wniosek o publikację?", "Aprobi cererea de publicare?", "الموافقة على طلب النشر؟");
        Add("WgVac.Confirm.ApproveBody", "Dit kost {0} tokens. Saldo nu: {1}. Saldo na: {2}.", "This costs {0} tokens. Balance now: {1}. Balance after: {2}.", "To kosztuje {0} tokenów. Saldo teraz: {1}. Po: {2}.", "Costă {0} tokenuri. Sold acum: {1}. După: {2}.", "يكلف {0} رمزاً. الرصيد الآن: {1}. بعده: {2}.");
        Add("WgVac.Confirm.BulkTitle", "Bulkactie bevestigen?", "Confirm bulk action?", "Potwierdzić akcję zbiorczą?", "Confirmi acțiunea în masă?", "تأكيد الإجراء الجماعي؟");
        Add("WgVac.Confirm.BulkBody", "Totaal {0} tokens. Saldo nu: {1}. Saldo na: {2}.", "Total {0} tokens. Balance now: {1}. Balance after: {2}.", "Razem {0} tokenów. Saldo teraz: {1}. Po: {2}.", "Total {0} tokenuri. Sold acum: {1}. După: {2}.", "المجموع {0} رمزاً. الرصيد الآن: {1}. بعده: {2}.");
        Add("WgVac.Confirm.AskTokens", "Vraag tokens aan bij je bedrijfsmanager", "Ask your company manager for tokens", "Poproś menedżera firmy o tokeny", "Cere tokenuri managerului de firmă", "اطلب الرموز من مدير شركتك");
        Add("WgVac.Cost.Highlight", "Uitlichten · {0} tokens", "Feature · {0} tokens", "Wyróżnij · {0} tokenów", "Evidențiază · {0} tokenuri", "تمييز · {0} رموز");
        Add("WgVac.Cost.Extend", "Verlengen · {0} tokens", "Extend · {0} tokens", "Przedłuż · {0} tokenów", "Prelungește · {0} tokenuri", "تمديد · {0} رموز");
        Add("WgVac.Cost.Push", "Pushbericht naar kandidaten · {0} tokens", "Push message · {0} tokens", "Powiadomienie · {0} tokenów", "Notificare · {0} tokenuri", "إشعار · {0} رموز");
        Add("WgVac.Pager", "{0} van {1} vacatures", "{0} of {1} vacancies", "{0} z {1} ofert", "{0} din {1} posturi", "{0} من {1} وظائف");
        Add("WgVac.Empty", "Nog geen vacatures.", "No vacancies yet.", "Brak ofert.", "Niciun post încă.", "لا وظائف بعد.");
        Add("WgVac.EmptyFilter", "Geen vacatures gevonden voor deze zoekopdracht of filter.", "No vacancies match this search or filter.", "Brak ofert dla tego wyszukiwania lub filtra.", "Niciun post pentru această căutare sau filtru.", "لا وظائف لهذا البحث أو التصفية.");
        Add("WgVac.ClosedOn", "gesloten {0}", "closed {0}", "zamknięta {0}", "închis {0}", "أُغلق {0}");
        Add("WgVac.Deactivated", "gedeactiveerd", "deactivated", "dezaktywowana", "dezactivat", "مُلغى");
        Add("WgVac.Create.VmPublishNote", "Je vestiging heeft {0} tokens. Publiceren kost {1}. Is je saldo te laag, dan gaat de vacature als publicatieaanvraag naar de bedrijfsmanager.", "Your branch has {0} tokens. Publishing costs {1}. If your balance is too low, the vacancy becomes a publication request to the company manager.", "Twoja placówka ma {0} tokenów. Publikacja kosztuje {1}. Przy zbyt niskim saldzie oferta trafia jako wniosek do menedżera firmy.", "Filiala ta are {0} tokenuri. Publicarea costă {1}. Dacă soldul e prea mic, postul devine cerere de publicare către managerul de firmă.", "فرعك لديه {0} رمزاً. النشر يكلف {1}. إذا كان الرصيد منخفضاً تصبح الوظيفة طلب نشر لمدير الشركة.");
        Add("WgVac.Paid.Publish", "Betaling gelukt — vacature is gepubliceerd.", "Payment succeeded — vacancy published.", "Płatność OK — oferta opublikowana.", "Plată reușită — post publicat.", "تم الدفع — نُشرت الوظيفة.");
        Add("WgVac.Paid.Highlight", "Betaling gelukt — vacature is uitgelicht.", "Payment succeeded — vacancy featured.", "Płatność OK — oferta wyróżniona.", "Plată reușită — post evidențiat.", "تم الدفع — مُيِّزت الوظيفة.");
        Add("WgVac.Paid.PushBom", "Betaling gelukt — pushbericht is verstuurd.", "Payment succeeded — push message sent.", "Płatność OK — powiadomienie wysłane.", "Plată reușită — notificare trimisă.", "تم الدفع — أُرسل الإشعار.");
        Add("WgVac.Paid.Extend", "Betaling gelukt — vacature is verlengd.", "Payment succeeded — vacancy extended.", "Płatność OK — oferta przedłużona.", "Plată reușită — post prelungit.", "تم الدفع — مُدِّدت الوظيفة.");

        // Sollicitaties (04)
        Add("WgApp.Lead", "Per vacature, van nieuw tot aangenomen.", "Per vacancy, from new to hired.", "Na ofertę: od nowych do zatrudnionych.", "Pe post, de la noi la angajați.", "لكل وظيفة، من الجديد إلى التعيين.");
        Add("WgApp.Filter.Vacancy", "Vacature", "Vacancy", "Oferta", "Post", "الوظيفة");
        Add("WgApp.Filter.Branch", "Vestiging", "Branch", "Placówka", "Filială", "الفرع");
        Add("WgApp.Filter.Overdue", "Alleen > 48 uur", "Only > 48 hours", "Tylko > 48 godz.", "Doar > 48 ore", "فقط > 48 ساعة");
        Add("WgApp.View.Pipeline", "Pijplijn", "Pipeline", "Lejek", "Pipeline", "مسار");
        Add("WgApp.View.List", "Lijst", "List", "Lista", "Listă", "قائمة");
        Add("WgApp.Col.New", "Nieuw", "New", "Nowe", "Noi", "جديد");
        Add("WgApp.Col.Accepted", "Geaccepteerd", "Accepted", "Zaakceptowane", "Acceptate", "مقبول");
        Add("WgApp.Col.Invited", "Uitgenodigd", "Invited", "Zaproszeni", "Invitați", "مدعو");
        Add("WgApp.Col.Hired", "Aangenomen", "Hired", "Zatrudnieni", "Angajați", "مُعيَّن");
        Add("WgApp.Col.Rejected", "Afgewezen", "Rejected", "Odrzucone", "Respinse", "مرفوض");
        Add("WgApp.Hint.Anonymous", "anoniem", "anonymous", "anonimowo", "anonim", "مجهول");
        Add("WgApp.Hint.NameCv", "naam + cv", "name + cv", "imię + cv", "nume + cv", "اسم + سيرة");
        Add("WgApp.Hint.Contact", "contact", "contact", "kontakt", "contact", "تواصل");
        Add("WgApp.Anonymous", "Kandidaat #{0}", "Candidate #{0}", "Kandydat #{0}", "Candidat #{0}", "مرشح #{0}");
        Add("WgApp.Overdue", "{0} dagen · te laat", "{0} days · overdue", "{0} dni · spóźnione", "{0} zile · întârziat", "{0} أيام · متأخر");
        Add("WgApp.AgeDays", "{0} dagen", "{0} days", "{0} dni", "{0} zile", "{0} أيام");
        Add("WgApp.Since", "Sinds {0}", "Since {0}", "Od {0}", "Din {0}", "منذ {0}");
        Add("WgApp.InvitedOn", "Uitgenodigd {0}", "Invited {0}", "Zaproszony {0}", "Invitat {0}", "دُعي {0}");
        Add("WgApp.ContactVisible", "Contact zichtbaar", "Contact visible", "Kontakt widoczny", "Contact vizibil", "التواصل ظاهر");
        Add("WgApp.RejectedSummary", "{0} afgewezen · {1} elders aan de slag · {2} teruggetrokken", "{0} rejected · {1} hired elsewhere · {2} withdrawn", "{0} odrzuconych · {1} gdzie indziej · {2} wycofanych", "{0} respinși · {1} angajați altundeva · {2} retrași", "{0} مرفوض · {1} عُيِّنوا في مكان آخر · {2} منسحب");
        Add("WgApp.ShowAll", "Toon alle {0}", "Show all {0}", "Pokaż wszystkie {0}", "Arată toate {0}", "عرض كل {0}");
        Add("WgApp.Match", "Match {0}%", "Match {0}%", "Dopasowanie {0}%", "Potrivire {0}%", "تطابق {0}%");
        Add("WgApp.MatchPill", "{0}% match", "{0}% match", "{0}% dopasowanie", "{0}% potrivire", "تطابق {0}%");
        Add("WgApp.Tab.Profile", "Profiel", "Profile", "Profil", "Profil", "الملف");
        Add("WgApp.Tab.Motivation", "Motivatie", "Motivation", "Motywacja", "Motivație", "الدافع");
        Add("WgApp.Tab.Timeline", "Tijdlijn", "Timeline", "Oś czasu", "Cronologie", "الجدول الزمني");
        Add("WgApp.See.Title", "Wat je ziet", "What you see", "Co widzisz", "Ce vezi", "ما تراه");
        Add("WgApp.See.Anonymous", "Anoniem profiel, match en motivatie", "Anonymous profile, match and motivation", "Anonimowy profil, dopasowanie i motywacja", "Profil anonim, potrivire și motivație", "ملف مجهول والتطابق والدافع");
        Add("WgApp.See.NameCv", "Naam en Lobsy-cv (na accepteren)", "Name and Lobsy CV (after accept)", "Imię i CV Lobsy (po akceptacji)", "Nume și CV Lobsy (după acceptare)", "الاسم وسيرة Lobsy (بعد القبول)");
        Add("WgApp.See.Contact", "E-mail en telefoon: zichtbaar na aanname", "Email and phone: visible after hire", "E-mail i telefon: widoczne po zatrudnieniu", "E-mail și telefon: vizibile după angajare", "البريد والهاتف: يظهران بعد التعيين");
        Add("WgApp.Fact.Travel", "Reistijd", "Travel time", "Czas dojazdu", "Timp de deplasare", "وقت التنقل");
        Add("WgApp.Fact.Available", "Beschikbaar", "Available", "Dostępność", "Disponibil", "متاح");
        Add("WgApp.Fact.License", "Rijbewijs", "License", "Prawo jazdy", "Permis", "رخصة");
        Add("WgApp.Fact.Education", "Opleiding", "Education", "Wykształcenie", "Studii", "التعليم");
        Add("WgApp.Fact.Experience", "Ervaring", "Experience", "Doświadczenie", "Experiență", "الخبرة");
        Add("WgApp.Fact.Hours", "Uren per week", "Hours per week", "Godziny/tydzień", "Ore pe săptămână", "ساعات أسبوعياً");
        Add("WgApp.Fact.EducationExp", "Opleiding en ervaring", "Education and experience", "Wykształcenie i doświadczenie", "Studii și experiență", "التعليم والخبرة");
        Add("WgApp.Timeline.Applied", "Gesolliciteerd", "Applied", "Aplikowano", "A aplicat", "تقدّم");
        Add("WgApp.Timeline.Responded", "Eerste reactie", "First response", "Pierwsza reakcja", "Primul răspuns", "أول رد");
        Add("WgApp.Timeline.Status", "Status", "Status", "Status", "Status", "الحالة");
        Add("WgApp.Action.Accept", "Accepteren", "Accept", "Zaakceptuj", "Acceptă", "قبول");
        Add("WgApp.Action.Reject", "Afwijzen", "Reject", "Odrzuć", "Respinge", "رفض");
        Add("WgApp.Action.Invite", "Uitnodigen", "Invite", "Zaproś", "Invită", "دعوة");
        Add("WgApp.Action.Hire", "Aannemen", "Hire", "Zatrudnij", "Angajează", "تعيين");
        Add("WgApp.Action.Cv", "Lobsy-cv", "Lobsy CV", "CV Lobsy", "CV Lobsy", "سيرة Lobsy");
        Add("WgApp.Action.BulkReject", "Afwijzen", "Reject", "Odrzuć", "Respinge", "رفض");
        Add("WgApp.HireConfirmTitle", "Vacature als vervuld markeren?", "Mark vacancy as filled?", "Oznaczyć ofertę jako obsadzoną?", "Marchezi postul ca ocupat?", "تعليم الوظيفة كمشغولة؟");
        Add("WgApp.HireConfirmBody", "Je neemt {0} aan voor “{1}”. De vacature wordt als vervuld gemarkeerd.", "You hire {0} for “{1}”. The vacancy will be marked filled.", "Zatrudniasz {0} na “{1}”. Oferta zostanie oznaczona jako obsadzona.", "Angajezi {0} pentru “{1}”. Postul va fi marcat ca ocupat.", "تعيّن {0} لـ “{1}”. ستُعلَّم الوظيفة كمشغولة.");
        Add("WgApp.RejectConfirmTitle", "Sollicitatie afwijzen?", "Reject application?", "Odrzucić aplikację?", "Respingi aplicația?", "رفض الطلب؟");
        Add("WgApp.RejectConfirmBody", "De kandidaat krijgt een afwijzing. Dit kun je niet ongedaan maken.", "The candidate will be rejected. This cannot be undone.", "Kandydat otrzyma odmowę. Nie da się tego cofnąć.", "Candidatul va fi respins. Nu se poate anula.", "سيُرفض المرشح. لا يمكن التراجع.");
        Add("WgApp.BulkRejectConfirm", "{0} sollicitaties afwijzen?", "Reject {0} applications?", "Odrzucić {0} aplikacji?", "Respingi {0} aplicații?", "رفض {0} طلبات؟");
        Add("WgApp.RmHint", "Reageren doet de vestigings- of bedrijfsmanager.", "The branch or company manager responds.", "Odpowiada menedżer placówki lub firmy.", "Răspunde managerul de filială sau de firmă.", "يرد مدير الفرع أو الشركة.");
        Add("WgApp.Status.Pending", "Nieuw", "New", "Nowe", "Nou", "جديد");
        Add("WgApp.Status.Accepted", "Geaccepteerd", "Accepted", "Zaakceptowane", "Acceptat", "مقبول");
        Add("WgApp.Status.Invited", "Uitgenodigd", "Invited", "Zaproszony", "Invitat", "مدعو");
        Add("WgApp.Status.Hired", "Aangenomen", "Hired", "Zatrudniony", "Angajat", "مُعيَّن");
        Add("WgApp.Status.Rejected", "Afgewezen", "Rejected", "Odrzucone", "Respins", "مرفوض");
        Add("WgApp.Status.FilledElsewhere", "Elders aan de slag", "Hired elsewhere", "Zatrudniony gdzie indziej", "Angajat altundeva", "عُيِّن في مكان آخر");
        Add("WgApp.Status.Withdrawn", "Teruggetrokken", "Withdrawn", "Wycofane", "Retras", "منسحب");
        Add("WgApp.List.Candidate", "Kandidaat", "Candidate", "Kandydat", "Candidat", "المرشح");
        Add("WgApp.List.Vacancy", "Vacature", "Vacancy", "Oferta", "Post", "الوظيفة");
        Add("WgApp.List.Branch", "Vestiging", "Branch", "Placówka", "Filială", "الفرع");
        Add("WgApp.List.Status", "Status", "Status", "Status", "Status", "الحالة");
        Add("WgApp.List.Match", "Match", "Match", "Dopasowanie", "Potrivire", "تطابق");
        Add("WgApp.List.Applied", "Gesolliciteerd", "Applied", "Aplikowano", "Aplicat", "تقدّم");
        Add("WgApp.List.FirstResponse", "Eerste reactie", "First response", "Pierwsza reakcja", "Primul răspuns", "أول رد");
        Add("WgApp.Empty", "Nog geen sollicitaties.", "No applications yet.", "Brak aplikacji.", "Nicio aplicație încă.", "لا طلبات بعد.");
        Add("WgApp.EmptyFilter", "Geen sollicitaties voor deze filter.", "No applications for this filter.", "Brak aplikacji dla tego filtra.", "Nicio aplicație pentru acest filtru.", "لا طلبات لهذه التصفية.");
        Add("WgApp.EmptyVacancy", "Kies een vacature om de pijplijn te zien.", "Choose a vacancy to see the pipeline.", "Wybierz ofertę, aby zobaczyć lejek.", "Alege un post pentru pipeline.", "اختر وظيفة لعرض المسار.");
        Add("WgApp.Mobile.NewTitle", "Nieuwe sollicitatie", "New application", "Nowa aplikacja", "Aplicație nouă", "طلب جديد");
        Add("WgApp.Mobile.NoResponse", "{0} dagen zonder reactie", "{0} days without a response", "{0} dni bez odpowiedzi", "{0} zile fără răspuns", "{0} أيام بلا رد");
        Add("WgApp.Privacy.Pending", "Naam en cv zie je na accepteren. Contactgegevens na aanname.", "Name and CV appear after accepting. Contact details after hiring.", "Imię i CV po akceptacji. Kontakt po zatrudnieniu.", "Numele și CV după acceptare. Contact după angajare.", "الاسم والسيرة بعد القبول. بيانات التواصل بعد التعيين.");
        Add("WgApp.Privacy.Accepted", "Contactgegevens zie je na aanname.", "Contact details appear after hiring.", "Dane kontaktowe po zatrudnieniu.", "Datele de contact după angajare.", "بيانات التواصل تظهر بعد التعيين.");
        Add("WgApp.Privacy.Hired", "Contactgegevens zijn zichtbaar.", "Contact details are visible.", "Dane kontaktowe są widoczne.", "Datele de contact sunt vizibile.", "بيانات التواصل ظاهرة.");
        Add("WgApp.AcceptedToast", "Sollicitatie geaccepteerd.", "Application accepted.", "Aplikacja zaakceptowana.", "Aplicație acceptată.", "تم قبول الطلب.");
        Add("WgApp.RejectedToast", "Sollicitatie afgewezen.", "Application rejected.", "Aplikacja odrzucona.", "Aplicație respinsă.", "تم رفض الطلب.");
        Add("WgApp.InvitedToast", "Kandidaat uitgenodigd.", "Candidate invited.", "Kandydat zaproszony.", "Candidat invitat.", "دُعي المرشح.");
        Add("WgApp.HiredToast", "Kandidaat aangenomen.", "Candidate hired.", "Kandydat zatrudniony.", "Candidat angajat.", "تم تعيين المرشح.");
        Add("WgApp.Pager", "{0} van {1} sollicitaties", "{0} of {1} applications", "{0} z {1} aplikacji", "{0} din {1} aplicații", "{0} من {1} طلبات");
        Add("WgApp.Direct", "Direct", "Immediate", "Od razu", "Imediat", "فوري");
        Add("WgApp.TravelFmt", "{0} min {1}", "{0} min {1}", "{0} min {1}", "{0} min {1}", "{0} د {1}");
        Add("WgApp.Step.New", "Nieuw", "New", "Nowe", "Nou", "جديد");
        Add("WgApp.Step.Accepted", "Geaccepteerd", "Accepted", "Zaakceptowane", "Acceptat", "مقبول");
        Add("WgApp.Step.Invited", "Uitgenodigd", "Invited", "Zaproszony", "Invitat", "مدعو");
        Add("WgApp.Step.Hired", "Aangenomen", "Hired", "Zatrudniony", "Angajat", "مُعيَّن");
        Add("WgApp.Back", "Terug", "Back", "Wstecz", "Înapoi", "رجوع");
        Add("WgApp.Completed", "Afgerond", "Completed", "Ukończone", "Finalizat", "مكتمل");

        // Organisatie / Team (05)
        Add("WgOrg.Lead", "Je organisatie, regio's, vestigingen en wie waar bij kan.", "Your organisation, regions, branches and who can access what.", "Twoja organizacja, regiony, placówki i kto ma dostęp.", "Organizația, regiunile, filialele și cine are acces.", "منظمتك والمناطق والفروع ومن يمكنه الوصول.");
        Add("WgOrg.TreeLabel", "Organisatiestructuur", "Organisation structure", "Struktura organizacji", "Structura organizației", "هيكل المنظمة");
        Add("WgOrg.SelectNode", "Selecteer een regio of vestiging.", "Select a region or branch.", "Wybierz region lub placówkę.", "Selectează o regiune sau filială.", "اختر منطقة أو فرعاً.");
        Add("WgOrg.NoManager", "Geen manager", "No manager", "Brak menedżera", "Fără manager", "بدون مدير");
        Add("WgOrg.AddRegion", "Regio toevoegen", "Add region", "Dodaj region", "Adaugă regiune", "إضافة منطقة");
        Add("WgOrg.EditRegion", "Regio bewerken", "Edit region", "Edytuj region", "Editează regiunea", "تعديل المنطقة");
        Add("WgOrg.AddBranchKvk", "Vestiging toevoegen via KvK", "Add branch via KvK", "Dodaj placówkę przez KvK", "Adaugă filială via KvK", "إضافة فرع عبر KvK");
        Add("WgOrg.Export", "Exporteren", "Export", "Eksportuj", "Exportă", "تصدير");
        Add("WgOrg.ExportReady", "Export klaar.", "Export ready.", "Eksport gotowy.", "Export gata.", "التصدير جاهز.");
        Add("WgOrg.ExportCount", "{0} vestigingen klaar voor export.", "{0} branches ready to export.", "{0} placówek gotowych do eksportu.", "{0} filiale gata de export.", "{0} فروع جاهزة للتصدير.");
        Add("WgOrg.Tab.Branches", "Vestigingen", "Branches", "Placówki", "Filiale", "الفروع");
        Add("WgOrg.Tab.Team", "Team ({0})", "Team ({0})", "Zespół ({0})", "Echipă ({0})", "الفريق ({0})");
        Add("WgOrg.Tab.Tokens", "Tokens", "Tokens", "Tokeny", "Tokenuri", "الرموز");
        Add("WgOrg.Detail.Group", "{0} vestigingen · {1} live vacatures", "{0} branches · {1} live vacancies", "{0} placówek · {1} ofert", "{0} filiale · {1} posturi live", "{0} فروع · {1} وظائف مباشرة");
        Add("WgOrg.Detail.Vestiging", "{0} live vacatures · {1} tokens", "{0} live vacancies · {1} tokens", "{0} ofert · {1} tokenów", "{0} posturi live · {1} tokenuri", "{0} وظائف مباشرة · {1} رموز");
        Add("WgOrg.BranchMeta", "{0} live · {1} tokens", "{0} live · {1} tokens", "{0} live · {1} tokenów", "{0} live · {1} tokenuri", "{0} مباشرة · {1} رموز");
        Add("WgOrg.NoChildBranches", "Geen vestigingen onder dit niveau.", "No branches under this level.", "Brak placówek na tym poziomie.", "Nicio filială la acest nivel.", "لا فروع تحت هذا المستوى.");
        Add("WgOrg.TokensLinkLead", "Tokenverbruik en toewijzing per vestiging vind je bij Tokens.", "Token usage and allocation per branch is under Tokens.", "Zużycie i przydział tokenów: Tokens.", "Consumul și alocarea: Tokenuri.", "استهلاك الرموز والتخصيص تحت الرموز.");
        Add("WgOrg.TokensLink", "Naar verbruik per vestiging", "Go to usage per branch", "Zużycie per placówka", "Consum pe filială", "إلى الاستهلاك لكل فرع");
        Add("WgOrg.Expand", "Uitklappen", "Expand", "Rozwiń", "Extinde", "توسيع");
        Add("WgOrg.Collapse", "Inklappen", "Collapse", "Zwiń", "Restrânge", "طي");
        Add("WgOrg.KvkNumber", "KVK-nummer", "KvK number", "Numer KVK", "Număr KVK", "رقم KVK");
        Add("WgOrg.KvkDemoHint", "Demo KVK: 12345678, 11223344, …", "Demo KvK: 12345678, 11223344, …", "Przykładowe KVK: 12345678, 11223344, …", "Exemple KVK: 12345678, 11223344, …", "تجريبي: 12345678, 11223344, …");
        Add("WgOrg.KvkSearch", "Zoek vestigingen", "Search establishments", "Szukaj placówek", "Caută unități", "بحث عن الفروع");
        Add("WgOrg.KvkInUse", "Al geregistreerd", "Already registered", "Już zarejestrowana", "Deja înregistrată", "مسجّل مسبقاً");
        Add("WgOrg.KvkEmpty", "Geen vestigingen gevonden.", "No establishments found.", "Nie znaleziono placówek.", "Nicio unitate găsită.", "لم يُعثر على فروع.");
        Add("WgOrg.BranchAdded", "Vestiging toegevoegd.", "Branch added.", "Dodano placówkę.", "Filială adăugată.", "تمت إضافة الفرع.");
        Add("WgOrg.RegionBranches", "Vestigingen in deze regio", "Branches in this region", "Placówki w regionie", "Filiale în regiune", "فروع في هذه المنطقة");
        Add("WgOrg.RegionNameRequired", "Naam is verplicht.", "Name is required.", "Nazwa jest wymagana.", "Numele este obligatoriu.", "الاسم مطلوب.");
        Add("WgOrg.RegionSaved", "Regio opgeslagen.", "Region saved.", "Zapisano region.", "Regiune salvată.", "تم حفظ المنطقة.");
        Add("WgOrg.RegionDeleted", "Regio verwijderd. Vestigingen vallen terug op ‘Zonder regio’.", "Region deleted. Branches fall back to ‘No region’.", "Usunięto region. Placówki wracają do ‘Bez regionu’.", "Regiune ștearsă. Filialele revin la ‘Fără regiune’.", "حُذفت المنطقة. تعود الفروع إلى «بدون منطقة».");
        Add("WgOrg.RegionsMoved", "Regio’s beheer je in Vestigingen & regio’s.", "Manage regions under Branches & regions.", "Regionami zarządzasz w Placówki i regiony.", "Regiunile se gestionează la Filiale și regiuni.", "تُدار المناطق تحت الفروع والمناطق.");

        Add("WgTeam.Lead", "Wie heeft toegang, met welke rol en voor welke vestigingen.", "Who has access, with which role and for which branches.", "Kto ma dostęp, z jaką rolą i do jakich placówek.", "Cine are acces, cu ce rol și pentru ce filiale.", "من لديه وصول، بأي دور ولأي فروع.");
        Add("WgTeam.Search", "Zoek op naam of e-mail", "Search by name or email", "Szukaj po nazwisku lub e-mailu", "Caută după nume sau e-mail", "ابحث بالاسم أو البريد");
        Add("WgTeam.Empty", "Nog geen teamleden.", "No team members yet.", "Brak członków zespołu.", "Niciun membru încă.", "لا أعضاء بعد.");
        Add("WgTeam.Col.Name", "Naam", "Name", "Nazwa", "Nume", "الاسم");
        Add("WgTeam.Col.Role", "Rol", "Role", "Rola", "Rolul", "الدور");
        Add("WgTeam.Col.Scope", "Bereik", "Scope", "Zakres", "Domeniu", "النطاق");
        Add("WgTeam.Col.Status", "Status", "Status", "Status", "Status", "الحالة");
        Add("WgTeam.Col.Active", "Actief", "Active", "Aktywny", "Activ", "نشط");
        Add("WgTeam.Status.Active", "Actief", "Active", "Aktywny", "Activ", "نشط");
        Add("WgTeam.Status.Inactive", "Gedeactiveerd", "Deactivated", "Dezaktywowany", "Dezactivat", "مُعطَّل");
        Add("WgTeam.Filter.AllRoles", "Alle rollen", "All roles", "Wszystkie role", "Toate rolurile", "كل الأدوار");
        Add("WgTeam.Filter.AllStatuses", "Alle statussen", "All statuses", "Wszystkie statusy", "Toate statusurile", "كل الحالات");
        Add("WgTeam.Filter.Branch", "Vestiging", "Branch", "Placówka", "Filială", "الفرع");
        Add("WgTeam.Scope.AllBranches", "Alle vestigingen", "All branches", "Wszystkie placówki", "Toate filialele", "كل الفروع");
        Add("WgTeam.Scope.Region", "Regio {0}", "Region {0}", "Region {0}", "Regiunea {0}", "منطقة {0}");
        Add("WgTeam.Scope.RegionUnknown", "Regio", "Region", "Region", "Regiune", "منطقة");
        Add("WgTeam.Active.Never", "Nog niet ingelogd", "Not logged in yet", "Jeszcze nie zalogowany", "Niciodată autentificat", "لم يسجّل الدخول بعد");
        Add("WgTeam.Active.Minutes", "{0} min geleden", "{0} min ago", "{0} min temu", "acum {0} min", "منذ {0} د");
        Add("WgTeam.Active.Hours", "{0} uur geleden", "{0} h ago", "{0} godz. temu", "acum {0} h", "منذ {0} س");
        Add("WgTeam.Active.Days", "{0} dagen geleden", "{0} days ago", "{0} dni temu", "acum {0} zile", "منذ {0} يوم");
        Add("WgTeam.Action.EditRoleScope", "Rol of bereik wijzigen", "Change role or scope", "Zmień rolę lub zakres", "Schimbă rolul sau domeniul", "تغيير الدور أو النطاق");
        Add("WgTeam.Action.Deactivate", "Deactiveren", "Deactivate", "Dezaktywuj", "Dezactivează", "تعطيل");
        Add("WgTeam.Action.Activate", "Activeren", "Activate", "Aktywuj", "Activează", "تفعيل");
        Add("WgTeam.DeactivateTitle", "Gebruiker deactiveren?", "Deactivate user?", "Dezaktywować użytkownika?", "Dezactivezi utilizatorul?", "تعطيل المستخدم؟");
        Add("WgTeam.DeactivateBody", "{0} verliest toegang tot de organisatie.", "{0} loses access to the organisation.", "{0} traci dostęp do organizacji.", "{0} pierde accesul la organizație.", "يفقد {0} الوصول إلى المنظمة.");
        Add("WgTeam.Saved", "Gebruiker opgeslagen.", "User saved.", "Zapisano użytkownika.", "Utilizator salvat.", "تم حفظ المستخدم.");
        Add("WgTeam.Activated", "Gebruiker geactiveerd.", "User activated.", "Aktywowano użytkownika.", "Utilizator activat.", "تم تفعيل المستخدم.");
        Add("WgTeam.Deactivated", "Gebruiker gedeactiveerd.", "User deactivated.", "Dezaktywowano użytkownika.", "Utilizator dezactivat.", "تم تعطيل المستخدم.");
        Add("WgTeam.RolesHelp.Title", "Wat mag elke rol?", "What may each role do?", "Co może każda rola?", "Ce poate fiecare rol?", "ماذا يحق لكل دور؟");
        Add("WgTeam.Role.Bm.Title", "Bedrijfsmanager", "Company manager", "Menedżer firmy", "Manager de firmă", "مدير الشركة");
        Add("WgTeam.Role.Bm.Body", "Alles voor alle vestigingen: vacatures goedkeuren, tokens kopen en verdelen, facturen, team en bedrijfsprofiel.", "Everything for all branches: approve vacancies, buy and allocate tokens, invoices, team and company profile.", "Wszystko dla wszystkich placówek: zatwierdzanie ofert, tokeny, faktury, zespół i profil.", "Totul pentru toate filialele: aprobare posturi, tokenuri, facturi, echipă și profil.", "كل شيء لكل الفروع: اعتماد الوظائف والرموز والفواتير والفريق وملف الشركة.");
        Add("WgTeam.Role.Rm.Title", "Regiomanager", "Regional manager", "Menedżer regionu", "Manager regional", "مدير المنطقة");
        Add("WgTeam.Role.Rm.Body", "Kijkt mee in de vestigingen van één regio. Alleen lezen: geen wijzigingen, geen tokens kopen.", "Views the branches of one region. Read only: no changes, no token purchases.", "Podgląd placówek jednego regionu. Tylko odczyt: bez zmian i zakupów tokenów.", "Vede filialele unei regiuni. Doar citire: fără modificări, fără cumpărare tokenuri.", "يعرض فروع منطقة واحدة. للقراءة فقط: بلا تعديلات وبلا شراء رموز.");
        Add("WgTeam.Role.Vm.Title", "Vestigingsmanager", "Branch manager", "Menedżer placówki", "Manager de filială", "مدير الفرع");
        Add("WgTeam.Role.Vm.Body", "Alle rechten, maar alleen voor de eigen vestiging: vacatures, sollicitaties, tokens en profiel.", "Full rights, but only for their own branch: vacancies, applications, tokens and profile.", "Pełne prawa tylko dla własnej placówki: oferty, aplikacje, tokeny i profil.", "Drepturi complete doar pentru filiala proprie: posturi, aplicații, tokenuri și profil.", "صلاحيات كاملة لكن لفرعه فقط: الوظائف والطلبات والرموز والملف.");

        Add("WgInvite.Title", "Iemand uitnodigen", "Invite someone", "Zaproś kogoś", "Invită pe cineva", "دعوة شخص");
        Add("WgInvite.Lead", "Eén plek voor alle uitnodigingen in je organisatie.", "One place for all invitations in your organisation.", "Jedno miejsce na wszystkie zaproszenia.", "Un singur loc pentru toate invitațiile.", "مكان واحد لكل الدعوات في منظمتك.");
        Add("WgInvite.Email", "E-mailadres", "Email address", "Adres e-mail", "Adresă e-mail", "البريد الإلكتروني");
        Add("WgInvite.Name", "Naam", "Name", "Imię i nazwisko", "Nume", "الاسم");
        Add("WgInvite.Role", "Rol", "Role", "Rola", "Rolul", "الدور");
        Add("WgInvite.Branch", "Vestiging", "Branch", "Placówka", "Filială", "الفرع");
        Add("WgInvite.Region", "Regio", "Region", "Region", "Regiune", "المنطقة");
        Add("WgInvite.SelectBranch", "Kies een vestiging", "Choose a branch", "Wybierz placówkę", "Alege o filială", "اختر فرعاً");
        Add("WgInvite.SelectRegion", "Kies een regio", "Choose a region", "Wybierz region", "Alege o regiune", "اختر منطقة");
        Add("WgInvite.Submit", "Uitnodiging versturen", "Send invitation", "Wyślij zaproszenie", "Trimite invitația", "إرسال الدعوة");
        Add("WgInvite.Privacy", "Kandidaatgegevens volgen de privacyregels: naam na accepteren, contactgegevens pas na aanname.", "Candidate data follows privacy rules: name after accept, contact details only after hire.", "Dane kandydata wg prywatności: imię po akceptacji, kontakt po zatrudnieniu.", "Datele candidatului respectă confidențialitatea: nume după acceptare, contact după angajare.", "بيانات المرشح تتبع الخصوصية: الاسم بعد القبول، التواصل بعد التعيين.");
        Add("WgInvite.Success", "Uitnodiging verstuurd.", "Invitation sent.", "Zaproszenie wysłane.", "Invitație trimisă.", "أُرسلت الدعوة.");
        Add("WgInvite.IntermediaryNote", "Rol: Intermediair. Teamleden krijgen alleen toegang tot dit intermediair-account.", "Role: Intermediary. Teammates only get access to this intermediary account.", "Rola: pośrednik. Dostęp tylko do tego konta.", "Rol: intermediar. Acces doar la acest cont.", "الدور: وسيط. يصل الزملاء فقط إلى حساب الوسيط هذا.");
        Add("WgInvite.Validation.Email", "Vul een geldig e-mailadres in.", "Enter a valid email address.", "Podaj prawidłowy e-mail.", "Introdu un e-mail valid.", "أدخل بريداً صالحاً.");
        Add("WgInvite.Validation.Name", "Naam is verplicht.", "Name is required.", "Imię jest wymagane.", "Numele este obligatoriu.", "الاسم مطلوب.");
        Add("WgInvite.Validation.Branch", "Kies een vestiging.", "Choose a branch.", "Wybierz placówkę.", "Alege o filială.", "اختر فرعاً.");
        Add("WgInvite.Validation.Region", "Kies een regio.", "Choose a region.", "Wybierz region.", "Alege o regiune.", "اختر منطقة.");
        Add("WgInvite.Validation.Org", "Geen organisatie gevonden.", "No organisation found.", "Nie znaleziono organizacji.", "Nicio organizație găsită.", "لم يُعثر على منظمة.");

        // Bedrijfsprofiel / Koppelingen / Wervingsmateriaal (05b)
        Add("WgTabs.ContactChannels", "Contact & kanalen", "Contact & channels", "Kontakt i kanały", "Contact și canale", "التواصل والقنوات");
        Add("WgTabs.RecruitmentPrefs", "Wervingsvoorkeuren", "Recruitment preferences", "Preferencje rekrutacji", "Preferințe recrutare", "تفضيلات التوظيف");
        Add("WgTabs.Api", "API", "API", "API", "API", "API");
        Add("WgTabs.CsvImport", "CSV-import", "CSV import", "Import CSV", "Import CSV", "استيراد CSV");
        Add("WgProfile.Lead", "Identiteit, contactkanalen, werving en cultuur van je organisatie.", "Identity, contact channels, recruitment and culture of your organisation.", "Tożsamość, kontakt, rekrutacja i kultura organizacji.", "Identitate, canale, recrutare și cultura organizației.", "هوية وقنوات وتوظيف وثقافة منظمتك.");
        Add("WgIntegrations.Lead", "API-sleutels en CSV-import voor vacatures.", "API keys and CSV import for vacancies.", "Klucze API i import CSV ofert.", "Chei API și import CSV pentru posturi.", "مفاتيح API واستيراد CSV للوظائف.");
        Add("WgMaterials.Lead", "Raamflyers, overzicht-PDF en tracking voor werving op locatie.", "Window flyers, overview PDF and tracking for on-site recruitment.", "Ulotki witrynowe, PDF przeglądu i tracking rekrutacji.", "Flyere, PDF de ansamblu și tracking pentru recrutare.", "منشورات الواجهة وPDF التتبع للتوظيف في الموقع.");
        Add("WgMaterials.Raamflyer", "Raamflyer", "Window flyer", "Ulotka witrynowa", "Flyer vitrină", "منشور الواجهة");
        Add("WgMaterials.RaamflyerLead", "Printbare flyer voor in de etalage — A4 of A3, per vestiging of als overzicht.", "Printable flyer for the window — A4 or A3, per branch or as overview.", "Ulotka do wydruku — A4/A3, per placówka lub zbiorczo.", "Flyer printabil — A4/A3, pe filială sau ansamblu.", "منشور للطباعة — A4 أو A3، لكل فرع أو كنظرة عامة.");
        Add("WgMaterials.OverviewTitle", "onze vestigingen", "our branches", "nasze placówki", "filialele noastre", "فروعنا");
        Add("WgMaterials.Tracking", "Trackingcode & flyer", "Tracking code & flyer", "Kod śledzenia i ulotka", "Cod tracking și flyer", "رمز التتبع والمنشور");
        Add("WgMaterials.TrackingLead", "Deel je trackingcode of partnerflyer om bedrijven aan te brengen.", "Share your tracking code or partner flyer to refer companies.", "Udostępnij kod lub ulotkę partnerską.", "Distribuie codul sau flyerul de partener.", "شارك رمز التتبع أو منشور الشريك.");
        Add("WgMaterials.TrackingCode", "Trackingcode", "Tracking code", "Kod śledzenia", "Cod tracking", "رمز التتبع");
        Add("WgMaterials.DownloadFlyer", "Download flyer", "Download flyer", "Pobierz ulotkę", "Descarcă flyerul", "تنزيل المنشور");
        Add("WgMaterials.Copy", "Kopieer", "Copy", "Kopiuj", "Copiază", "نسخ");
        Add("WgMaterials.Copied", "Gekopieerd.", "Copied.", "Skopiowano.", "Copiat.", "تم النسخ.");
        Add("WgSalary.Lead", "CAO-schalen op bedrijfsniveau — vestigingen kiezen hieruit bij vacatureplaatsing.", "Company-level pay scales — branches pick these when posting vacancies.", "Skale płac na poziomie firmy — placówki wybierają je przy ofertach.", "Grile salariale la nivel de firmă — filialele le aleg la publicare.", "جداول أجور على مستوى الشركة — تختارها الفروع عند النشر.");
        Add("WgSalary.New", "Nieuwe tabel", "New table", "Nowa tabela", "Tabel nou", "جدول جديد");
        Add("WgTakeovers.Lead", "Vestigingen waarvoor iemand overname heeft aangevraagd.", "Branches for which someone requested a takeover.", "Placówki z wnioskiem o przejęcie.", "Filiale cu cerere de preluare.", "فروع طُلب الاستحواذ عليها.");
        Add("WgTakeovers.Empty", "Geen openstaande verzoeken.", "No open requests.", "Brak otwartych wniosków.", "Nicio cerere deschisă.", "لا طلبات مفتوحة.");
        Add("WgTakeovers.Approve", "Goedkeuren", "Approve", "Zatwierdź", "Aprobă", "موافقة");
        Add("WgTakeovers.Reject", "Afwijzen", "Reject", "Odrzuć", "Respinge", "رفض");

        // Tokens & facturen (06)
        Add("WgTok.Title", "Tokens & facturen", "Tokens & invoices", "Tokeny i faktury", "Tokenuri și facturi", "الرموز والفواتير");
        Add("WgTok.Lead", "Saldo, verdeling over vestigingen, aankopen en facturen op één plek.", "Balance, distribution across branches, purchases and invoices in one place.", "Saldo, podział na placówki, zakupy i faktury w jednym miejscu.", "Sold, distribuție pe filiale, cumpărări și facturi într-un loc.", "الرصيد والتوزيع على الفروع والمشتريات والفواتير في مكان واحد.");
        Add("WgTok.LeadRm", "Tokenverbruik in je regio — alleen lezen.", "Token usage in your region — read only.", "Zużycie tokenów w regionie — tylko odczyt.", "Consum tokenuri în regiune — doar citire.", "استهلاك الرموز في منطقتك — للقراءة فقط.");
        Add("WgTok.LeadVm", "Saldo van je vestiging en tokenaanvragen.", "Your branch balance and token requests.", "Saldo placówki i wnioski o tokeny.", "Soldul filialei și cererile de tokenuri.", "رصيد فرعك وطلبات الرموز.");
        Add("WgTok.Tab.Overview", "Overzicht", "Overview", "Przegląd", "Prezentare", "نظرة عامة");
        Add("WgTok.Tab.Usage", "Verbruik per vestiging", "Usage per branch", "Zużycie per placówka", "Consum pe filială", "الاستهلاك لكل فرع");
        Add("WgTok.Tab.Mutations", "Mutaties", "Mutations", "Mutacje", "Mutări", "الحركات");
        Add("WgTok.Tab.Invoices", "Facturen", "Invoices", "Faktury", "Facturi", "الفواتير");
        Add("WgTok.AllMutations", "Alle mutaties", "All mutations", "Wszystkie mutacje", "Toate mutările", "كل الحركات");
        Add("WgTok.BuyTokens", "Tokens kopen", "Buy tokens", "Kup tokeny", "Cumpără tokenuri", "شراء رموز");
        Add("WgTok.RequestTokens", "Tokens aanvragen", "Request tokens", "Poproś o tokeny", "Cere tokenuri", "طلب رموز");
        Add("WgTok.Kpi.Central", "Centraal saldo", "Central balance", "Saldo centralne", "Sold central", "الرصيد المركزي");
        Add("WgTok.Kpi.CentralSub", "niet toegewezen: {0}", "unallocated: {0}", "nieprzydzielone: {0}", "nealocate: {0}", "غير مخصص: {0}");
        Add("WgTok.Kpi.Allocated", "Toegewezen aan vestigingen", "Allocated to branches", "Przydzielone placówkom", "Alocate filialelor", "مخصصة للفروع");
        Add("WgTok.Kpi.AllocatedSub", "over {0} vestigingen", "across {0} branches", "w {0} placówkach", "pe {0} filiale", "على {0} فروع");
        Add("WgTok.Kpi.Used", "Verbruikt (30 dagen)", "Used (30 days)", "Zużyte (30 dni)", "Consumate (30 zile)", "المستهلك (30 يوماً)");
        Add("WgTok.Kpi.UsedSub", "vorige 30 dagen: {0}", "previous 30 days: {0}", "poprzednie 30 dni: {0}", "ultimele 30 zile: {0}", "الـ 30 يوماً السابقة: {0}");
        Add("WgTok.Kpi.Reserved", "Gereserveerd voor aanvragen", "Reserved for requests", "Zarezerwowane na wnioski", "Rezervate pentru cereri", "محجوز للطلبات");
        Add("WgTok.Kpi.ReservedSub", "{0} publicatieaanvragen", "{0} publish requests", "{0} wnioski o publikację", "{0} cereri de publicare", "{0} طلبات نشر");
        Add("WgTok.Kpi.BranchBalance", "Saldo vestiging {0}", "Branch balance {0}", "Saldo placówki {0}", "Sold filiala {0}", "رصيد الفرع {0}");
        Add("WgTok.Kpi.BranchBalanceSub", "toegewezen door de bedrijfsmanager", "allocated by the company manager", "przydzielone przez menedżera firmy", "alocate de managerul de firmă", "مخصصة من مدير الشركة");
        Add("WgTok.Kpi.RegionUsage", "Tokenverbruik regio", "Region token usage", "Zużycie tokenów regionu", "Consum tokenuri regiune", "استهلاك رموز المنطقة");
        Add("WgTok.UsageTitle", "Verbruik per vestiging", "Usage per branch", "Zużycie per placówka", "Consum pe filială", "الاستهلاك لكل فرع");
        Add("WgTok.UsageOther", "Overige {0} vestigingen", "Other {0} branches", "Pozostałe {0} placówki", "Alte {0} filiale", "{0} فروع أخرى");
        Add("WgTok.UsageFull", "Alles bekijken", "View all", "Zobacz wszystko", "Vezi tot", "عرض الكل");
        Add("WgTok.Col.Branch", "Vestiging", "Branch", "Placówka", "Filială", "الفرع");
        Add("WgTok.Col.Allocated", "Toegewezen", "Allocated", "Przydzielone", "Alocate", "مخصص");
        Add("WgTok.Col.Used", "Verbruikt", "Used", "Zużyte", "Consumate", "مستهلك");
        Add("WgTok.Col.Remaining", "Over", "Left", "Pozostało", "Rămase", "متبقي");
        Add("WgTok.Allocate", "Verdelen", "Allocate", "Przydziel", "Alocă", "توزيع");
        Add("WgTok.AllocateTitle", "Tokens verdelen", "Allocate tokens", "Przydziel tokeny", "Alocă tokenuri", "توزيع الرموز");
        Add("WgTok.AllocateAmount", "Aantal", "Amount", "Ilość", "Cantitate", "الكمية");
        Add("WgTok.AllocateImpact", "Centraal saldo na verdelen: {0}", "Central balance after allocation: {0}", "Saldo centralne po przydziale: {0}", "Sold central după alocare: {0}", "الرصيد المركزي بعد التوزيع: {0}");
        Add("WgTok.AllocateSubmit", "Toewijzen", "Allocate", "Przydziel", "Alocă", "تخصيص");
        Add("WgTok.BuyTitle", "Tokens kopen", "Buy tokens", "Kup tokeny", "Cumpără tokenuri", "شراء رموز");
        Add("WgTok.WhatCosts", "Wat kost wat?", "What costs what?", "Co ile kosztuje?", "Ce costă ce?", "ماذا يكلف ماذا؟");
        Add("WgTok.BuyButton", "{0} tokens kopen · € {1} excl. btw", "Buy {0} tokens · € {1} excl. VAT", "Kup {0} tokenów · € {1} bez VAT", "Cumpără {0} tokenuri · € {1} fără TVA", "اشترِ {0} رمزاً · € {1} بدون ضريبة");
        Add("WgTok.PerToken", "€ {0} per token", "€ {0} each", "€ {0} za token", "€ {0} per token", "€ {0} لكل رمز");
        Add("WgTok.RecentInvoices", "Recente facturen", "Recent invoices", "Ostatnie faktury", "Facturi recente", "فواتير حديثة");
        Add("WgTok.AllInvoices", "Alle facturen", "All invoices", "Wszystkie faktury", "Toate facturile", "كل الفواتير");
        Add("WgTok.Col.Invoice", "Factuur", "Invoice", "Faktura", "Factură", "فاتورة");
        Add("WgTok.Col.Description", "Omschrijving", "Description", "Opis", "Descriere", "الوصف");
        Add("WgTok.Col.AmountIncl", "Bedrag incl. btw", "Amount incl. VAT", "Kwota z VAT", "Sumă cu TVA", "المبلغ شامل الضريبة");
        Add("WgTok.Col.Status", "Status", "Status", "Status", "Status", "الحالة");
        Add("WgTok.Col.Date", "Datum", "Date", "Data", "Data", "التاريخ");
        Add("WgTok.Col.Mutation", "Mutatie", "Mutation", "Mutacja", "Mutare", "الحركة");
        Add("WgTok.Col.BalanceAfter", "Saldo na", "Balance after", "Saldo po", "Sold după", "الرصيد بعده");
        Add("WgTok.Col.By", "Door", "By", "Przez", "De", "بواسطة");
        Add("WgTok.InvoicePack", "{0} tokens", "{0}-token pack", "{0} tokenów", "{0} tokenuri", "{0} رموز");
        Add("WgTok.Download", "Download", "Download PDF", "Pobierz", "Descarcă", "تنزيل");
        Add("WgTok.BillingPrefs", "Factuurgegevens", "Billing details", "Dane fakturowe", "Date facturare", "بيانات الفوترة");
        Add("WgTok.BillingPrefsLead", "Voorkeursbetaalmethode voor tokenaankopen.", "Preferred payment method for token purchases.", "Preferowana metoda płatności za tokeny.", "Metoda preferată de plată pentru tokenuri.", "طريقة الدفع المفضلة لشراء الرموز.");
        Add("WgTok.PaymentMethod", "Betaalmethode", "Payment method", "Metoda płatności", "Metoda de plată", "طريقة الدفع");
        Add("WgTok.Management", "Tokens beheren", "Token management", "Zarządzanie tokenami", "Administrare tokenuri", "إدارة الرموز");
        Add("WgTok.ManagementCentral", "Centraal (aanbevolen)", "Central (recommended)", "Centralnie (zalecane)", "Central (recomandat)", "مركزي (موصى به)");
        Add("WgTok.ManagementPerBranch", "Per vestiging", "Per branch", "Per placówka", "Pe filială", "لكل فرع");
        Add("WgTok.ManagementConfirm", "Tokens centraal of per vestiging beheren verandert wie mag inkopen en hoe de pot werkt.", "Managing tokens centrally or per branch changes who can buy and how the pot works.", "Zmiana zarządzania tokenami wpływa na zakupy i pulę.", "Schimbarea administrării tokenurilor afectează cumpărăturile și fondul.", "تغيير إدارة الرموز يؤثر على الشراء والصندوق.");
        Add("WgTok.Period30", "30 dagen", "30 days", "30 dni", "30 zile", "30 يوماً");
        Add("WgTok.Period90", "90 dagen", "90 days", "90 dni", "90 zile", "90 يوماً");
        Add("WgTok.ExportCsv", "CSV exporteren", "Export CSV", "Eksportuj CSV", "Export CSV", "تصدير CSV");
        Add("WgTok.RequestTitle", "Tokens aanvragen", "Request tokens", "Poproś o tokeny", "Cere tokenuri", "طلب رموز");
        Add("WgTok.RequestReason", "Reden", "Reason", "Powód", "Motiv", "السبب");
        Add("WgTok.RequestNote", "Toelichting (optioneel)", "Note (optional)", "Uwagi (opcjonalnie)", "Notă (opțional)", "ملاحظة (اختياري)");
        Add("WgTok.RequestImpact", "De bedrijfsmanager krijgt je aanvraag in Te doen.", "The company manager gets your request in To-do.", "Menedżer firmy otrzyma wniosek w Do zrobienia.", "Managerul de firmă primește cererea în De făcut.", "يصل طلبك إلى مدير الشركة في المهام.");
        Add("WgTok.RequestSubmit", "Aanvraag versturen", "Send request", "Wyślij wniosek", "Trimite cererea", "إرسال الطلب");
        Add("WgTok.RequestSent", "Aanvraag verstuurd.", "Request sent.", "Wniosek wysłany.", "Cerere trimisă.", "أُرسل الطلب.");
        Add("WgTok.MyRequests", "Mijn aanvragen", "My requests", "Moje wnioski", "Cererile mele", "طلباتي");
        Add("WgTok.OpenRequests", "Openstaande aanvragen", "Open requests", "Otwarte wnioski", "Cereri deschise", "طلبات مفتوحة");
        Add("WgTok.Approve", "Toewijzen", "Allocate", "Przydziel", "Alocă", "تخصيص");
        Add("WgTok.Reject", "Afwijzen", "Reject", "Odrzuć", "Respinge", "رفض");
        Add("WgTok.Withdraw", "Intrekken", "Withdraw", "Wycofaj", "Retrage", "سحب");
        Add("WgTok.Reason.Publiceren", "Publiceren", "Publish", "Publikacja", "Publicare", "نشر");
        Add("WgTok.Reason.Verlengen", "Verlengen", "Extend", "Przedłużenie", "Prelungire", "تمديد");
        Add("WgTok.Reason.Uitlichten", "Uitlichten", "Feature", "Wyróżnienie", "Evidențiere", "إبراز");
        Add("WgTok.Reason.Kandidaatinzichten", "Kandidaatinzichten", "Candidate insights", "Wnioski o kandydatach", "Perspective candidați", "رؤى المرشحين");
        Add("WgTok.Reason.Overig", "Overig", "Other", "Inne", "Altele", "أخرى");
        Add("WgTok.Status.Open", "Open", "Open", "Otwarty", "Deschis", "مفتوح");
        Add("WgTok.Status.Toegewezen", "Toegewezen", "Allocated", "Przydzielony", "Alocat", "مخصص");
        Add("WgTok.Status.Afgewezen", "Afgewezen", "Rejected", "Odrzucony", "Respins", "مرفوض");
        Add("WgTok.Status.Ingetrokken", "Ingetrokken", "Withdrawn", "Wycofany", "Retras", "مسحوب");
        Add("WgTok.Partner.Lead", "Partnerprogramma: tracking, referrals en commissie-overzicht.", "Partner program: tracking, referrals and commission overview.", "Program partnerski: tracking, polecenia i prowizje.", "Program partener: tracking, recomandări și comisioane.", "برنامج الشريك: التتبع والإحالات والعمولات.");
        Add("WgTok.Partner.Referrals", "Referral-overzicht", "Referral overview", "Przegląd poleceń", "Prezentare recomandări", "نظرة على الإحالات");
        Add("WgTok.EmptyUsage", "Nog geen vestigingen met tokenverbruik.", "No branches with token usage yet.", "Brak placówek ze zużyciem.", "Nicio filială cu consum.", "لا فروع باستهلاك بعد.");
        Add("WgTok.EmptyMutations", "Geen mutaties gevonden.", "No mutations found.", "Brak mutacji.", "Nicio mutare găsită.", "لا حركات.");
        Add("WgTok.EmptyInvoices", "Nog geen facturen.", "No invoices yet.", "Brak faktur.", "Nicio factură încă.", "لا فواتير بعد.");
        Add("WgTodo.Kind.TokenRequests", "Tokenaanvragen", "Token requests", "Wnioski o tokeny", "Cereri tokenuri", "طلبات الرموز");
        Add("WgTodo.TokenRequests.TitleOne", "{0} vraagt {1} tokens aan", "{0} requests {1} tokens", "{0} prosi o {1} tokenów", "{0} cere {1} tokenuri", "{0} يطلب {1} رمزاً");
        Add("WgTodo.TokenRequests.TitleMany", "{0} openstaande tokenaanvragen", "{0} open token requests", "{0} otwartych wniosków o tokeny", "{0} cereri de tokenuri deschise", "{0} طلبات رموز مفتوحة");
        Add("WgTodo.TokenRequests.Meta", "Wijs tokens toe of wijs de aanvraag af.", "Allocate tokens or reject the request.", "Przydziel tokeny lub odrzuć wniosek.", "Alocă tokenuri sau respinge cererea.", "خصّص الرموز أو ارفض الطلب.");
        Add("WgTodo.InsightsRequests.TitleOne", "{0} vraagt Kandidaatinzichten aan", "{0} requests Candidate insights", "{0} prosi o wglądy w kandydatów", "{0} cere perspective candidați", "{0} يطلب رؤى المرشحين");
        Add("WgTodo.InsightsRequests.TitleMany", "{0} openstaande inzichten-aanvragen", "{0} open insights requests", "{0} otwartych wniosków o wglądy", "{0} cereri de perspective deschise", "{0} طلبات رؤى مفتوحة");
        Add("WgTodo.InsightsRequests.Meta", "Ontgrendel of wijs de aanvraag af.", "Unlock or reject the request.", "Odblokuj lub odrzuć wniosek.", "Deblochează sau respinge cererea.", "افتح أو ارفض الطلب.");

        Add("WgVac.ContactFromProfile", "Contactgegevens komen uit het bedrijfsprofiel.", "Contact details come from the company profile.", "Dane kontaktowe pochodzą z profilu firmy.", "Datele de contact vin din profilul firmei.", "بيانات التواصل من ملف الشركة.");
        Add("WgTok.PurchaseAgree", "Ik ga akkoord met de aankoop. Prepaid, geen automatische verlenging.", "I agree to the purchase. Prepaid, no automatic renewal.", "Akceptuję zakup. Prepaid, bez automatycznego odnawiania.", "Sunt de acord cu cumpărarea. Prepaid, fără reînnoire automată.", "أوافق على الشراء. مسبق الدفع، بلا تجديد تلقائي.");
    }
}
