// <auto-generated />
using System;
using Jobsy.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jobsy.Infrastructure.Data.Migrations
{
    [DbContext(typeof(JobsyDbContext))]
    [Migration("20260727140841_AddSearchImpressionsAndSiteVisits")]
    partial class AddSearchImpressionsAndSiteVisits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jobsy.Core.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateAddress")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("CandidateCity")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CandidateEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("CandidateUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsentAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConsentVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<int>("EstimatedTravelMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("PreferencesSummary")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("PreferredTransport")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CandidateUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("VacancyId", "CandidateEmail")
                        .IsUnique();

                    b.HasIndex("VacancyId", "CandidateUserId")
                        .IsUnique()
                        .HasFilter("\"CandidateUserId\" IS NOT NULL");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.CommissionLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountExVat")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("SalesManagerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SelfBillingInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourcePaymentId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("SourceTokenCheckoutId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasFilter("\"Kind\" = 0 AND \"CompanyId\" IS NOT NULL");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SalesManagerUserId");

                    b.HasIndex("SelfBillingInvoiceId");

                    b.HasIndex("SourcePaymentId")
                        .IsUnique()
                        .HasFilter("\"SourcePaymentId\" IS NOT NULL");

                    b.HasIndex("SourceTokenCheckoutId")
                        .IsUnique()
                        .HasFilter("\"SourceTokenCheckoutId\" IS NOT NULL");

                    b.ToTable("CommissionLedgerEntries");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("FirstYearStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FirstYearSupplierSlot")
                        .HasColumnType("integer");

                    b.Property<bool>("HasReceivedWelcomeToken")
                        .HasColumnType("boolean");

                    b.Property<string>("KvkEstablishmentId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("KvkNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentCompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReferredBySalesManagerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirstYearSupplierSlot")
                        .IsUnique()
                        .HasFilter("\"FirstYearSupplierSlot\" IS NOT NULL");

                    b.HasIndex("KvkEstablishmentId")
                        .IsUnique();

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("ParentCompanyId");

                    b.HasIndex("ReferredBySalesManagerUserId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.CompanyRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ActivationToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("ConsentAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConsentVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBranchCompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedOrganizationCompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EstablishmentAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("EstablishmentName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("KvkEstablishmentId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("KvkNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("SalesManagerTrackingCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActivationToken")
                        .IsUnique();

                    b.HasIndex("ContactEmail");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedBranchCompanyId");

                    b.HasIndex("CreatedOrganizationCompanyId");

                    b.HasIndex("CreatedUserId");

                    b.ToTable("CompanyRegistrations");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.CompanySalaryRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeYears")
                        .HasColumnType("integer");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SalaryTableId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SalaryTableId");

                    b.ToTable("CompanySalaryRates");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.CompanySalaryTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemWml")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "IsSystemWml")
                        .IsUnique()
                        .HasFilter("\"IsSystemWml\" = TRUE");

                    b.ToTable("CompanySalaryTables");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.CompanySalaryTableAllowedBranch", b =>
                {
                    b.Property<Guid>("SalaryTableId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.HasKey("SalaryTableId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanySalaryTableAllowedBranches");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.CompanySalaryTableChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("SalaryTableId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SalaryTableId");

                    b.ToTable("CompanySalaryTableChangeLogs");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.EarlyAdapterRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MonthlyGrantTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("PurchaseDiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.ToTable("EarlyAdapterRules");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.EstablishmentTakeoverRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetCompanyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("Status");

                    b.HasIndex("TargetCompanyId");

                    b.ToTable("EstablishmentTakeoverRequests");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.IntegrationCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ClientSecret")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastPingAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastPingMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool?>("LastPingOk")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("IntegrationCredentials");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.LocalAuthCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("LocalAuthCredentials");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.MinimumWageRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeYears")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("AgeYears");

                    b.ToTable("MinimumWageRates");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.PlatformFeatureSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AuthenticatorEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ExposeRegistrationActivationLinks")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicWebBaseUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("VacancyContentModerationEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("PlatformFeatureSettings");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.PlatformLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.ToTable("PlatformLogs");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.PushBomPricingTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostTokens")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxCandidates")
                        .HasColumnType("integer");

                    b.Property<int>("MinCandidates")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MinCandidates", "MaxCandidates");

                    b.ToTable("PushBomPricingTiers");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.PushBomSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MaxTravelMinutes")
                        .HasColumnType("integer");

                    b.Property<double>("RadiusKm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PushBomSettings");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("OrganizationCompanyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationCompanyId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.RegionCompany", b =>
                {
                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.HasKey("RegionId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("RegionCompanies");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.SalesManagerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("AgreementSignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AgreementVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Country")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Iban")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("KvkNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("OnboardingCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TrackingCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("TrackingCode")
                        .IsUnique()
                        .HasFilter("\"TrackingCode\" IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SalesManagerProfiles");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.SelfBillingInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SalesManagerAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SalesManagerCompanyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SalesManagerKvkNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SalesManagerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("SalesManagerVatNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubtotalExVat")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TotalInclVat")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("SalesManagerUserId");

                    b.ToTable("SelfBillingInvoices");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.SelfBillingInvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountExVat")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("SelfBillingInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceLedgerEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SelfBillingInvoiceId");

                    b.ToTable("SelfBillingInvoiceLines");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.SiteVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnonymousKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousKey");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("SiteVisits");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.SupplierOnboardingCheckout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountEuro")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CreditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("SupplierOnboardingCheckouts");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.TokenPricing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PackSize")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceEuro")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PackSize")
                        .IsUnique();

                    b.ToTable("TokenPricings");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.TokenPurchaseCheckout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountEuro")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CreditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PackSize")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("TokenPurchaseCheckouts");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.TokenSpendCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostTokens")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Reason")
                        .IsUnique();

                    b.ToTable("TokenSpendCosts");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.TokenTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("BranchCompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<decimal>("NewBalance")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<decimal>("OldBalance")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VacancyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("BranchCompanyId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("VacancyId");

                    b.ToTable("TokenTransactions");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsentVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Point>("HomeLocation")
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEarlyAdapter")
                        .HasColumnType("boolean");

                    b.Property<bool>("OpenForWork")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferencesJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TermsAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("HomeLocation");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("HomeLocation"), "GIST");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.UserCompany", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("UserCompanies");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.Vacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("ExtensionCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("HourlyWage")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<int>("MaxApplications")
                        .HasColumnType("integer");

                    b.Property<bool>("RequestedExtend")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequestedHighlight")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequestedPushBom")
                        .HasColumnType("boolean");

                    b.Property<int>("RequiredTransport")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SalaryTableId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("WorkTypes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("SalaryTableId");

                    b.ToTable("Vacancies");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.VacancyClick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnonymousKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("VacancyId");

                    b.ToTable("VacancyClicks");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.VacancyLike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("VacancyId", "UserId")
                        .IsUnique();

                    b.ToTable("VacancyLikes");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.VacancySearchImpression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnonymousKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("VacancyId");

                    b.ToTable("VacancySearchImpressions");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.VacancyShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("VacancyId");

                    b.ToTable("VacancyShares");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.Application", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.User", "CandidateUser")
                        .WithMany()
                        .HasForeignKey("CandidateUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jobsy.Core.Entities.Vacancy", "Vacancy")
                        .WithMany("Applications")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateUser");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.CommissionLedgerEntry", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jobsy.Core.Entities.User", "SalesManagerUser")
                        .WithMany()
                        .HasForeignKey("SalesManagerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jobsy.Core.Entities.SelfBillingInvoice", "SelfBillingInvoice")
                        .WithMany("LinkedLedgerEntries")
                        .HasForeignKey("SelfBillingInvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("SalesManagerUser");

                    b.Navigation("SelfBillingInvoice");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.Company", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.Company", "ParentCompany")
                        .WithMany("ChildCompanies")
                        .HasForeignKey("ParentCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Jobsy.Core.Entities.User", "ReferredBySalesManagerUser")
                        .WithMany()
                        .HasForeignKey("ReferredBySalesManagerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentCompany");

                    b.Navigation("ReferredBySalesManagerUser");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.CompanyRegistration", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.Company", "CreatedBranchCompany")
                        .WithMany()
                        .HasForeignKey("CreatedBranchCompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jobsy.Core.Entities.Company", "CreatedOrganizationCompany")
                        .WithMany()
                        .HasForeignKey("CreatedOrganizationCompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jobsy.Core.Entities.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBranchCompany");

                    b.Navigation("CreatedOrganizationCompany");

                    b.Navigation("CreatedUser");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.CompanySalaryRate", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.CompanySalaryTable", "SalaryTable")
                        .WithMany("Rates")
                        .HasForeignKey("SalaryTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalaryTable");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.CompanySalaryTable", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.Company", "Company")
                        .WithMany("SalaryTables")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.CompanySalaryTableAllowedBranch", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jobsy.Core.Entities.CompanySalaryTable", "SalaryTable")
                        .WithMany("AllowedBranches")
                        .HasForeignKey("SalaryTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("SalaryTable");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.CompanySalaryTableChangeLog", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.CompanySalaryTable", "SalaryTable")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("SalaryTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalaryTable");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.EstablishmentTakeoverRequest", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.User", "DecidedByUser")
                        .WithMany()
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jobsy.Core.Entities.CompanyRegistration", "Registration")
                        .WithMany("TakeoverRequests")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jobsy.Core.Entities.Company", "TargetCompany")
                        .WithMany()
                        .HasForeignKey("TargetCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DecidedByUser");

                    b.Navigation("Registration");

                    b.Navigation("TargetCompany");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.LocalAuthCredential", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.Region", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.Company", "OrganizationCompany")
                        .WithMany()
                        .HasForeignKey("OrganizationCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganizationCompany");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.RegionCompany", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.Company", "Company")
                        .WithMany("RegionMemberships")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jobsy.Core.Entities.Region", "Region")
                        .WithMany("Companies")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.SalesManagerProfile", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Jobsy.Core.Entities.SalesManagerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.SelfBillingInvoice", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.User", "SalesManagerUser")
                        .WithMany()
                        .HasForeignKey("SalesManagerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesManagerUser");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.SelfBillingInvoiceLine", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.SelfBillingInvoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("SelfBillingInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.SiteVisit", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.SupplierOnboardingCheckout", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.TokenPurchaseCheckout", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.TokenTransaction", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jobsy.Core.Entities.Company", "BranchCompany")
                        .WithMany()
                        .HasForeignKey("BranchCompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jobsy.Core.Entities.Company", "Company")
                        .WithMany("TokenTransactions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jobsy.Core.Entities.Vacancy", "Vacancy")
                        .WithMany()
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");

                    b.Navigation("BranchCompany");

                    b.Navigation("Company");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.User", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.Company", "Company")
                        .WithMany("PrimaryUsers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.UserCompany", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.Company", "Company")
                        .WithMany("UserMemberships")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jobsy.Core.Entities.User", "User")
                        .WithMany("CompanyMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.Vacancy", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.Company", "Company")
                        .WithMany("Vacancies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jobsy.Core.Entities.CompanySalaryTable", "SalaryTable")
                        .WithMany("Vacancies")
                        .HasForeignKey("SalaryTableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("SalaryTable");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.VacancyClick", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jobsy.Core.Entities.Vacancy", "Vacancy")
                        .WithMany("Clicks")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.VacancyLike", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jobsy.Core.Entities.Vacancy", "Vacancy")
                        .WithMany("Likes")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.VacancySearchImpression", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jobsy.Core.Entities.Vacancy", "Vacancy")
                        .WithMany("SearchImpressions")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.VacancyShare", b =>
                {
                    b.HasOne("Jobsy.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jobsy.Core.Entities.Vacancy", "Vacancy")
                        .WithMany("Shares")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.Company", b =>
                {
                    b.Navigation("ChildCompanies");

                    b.Navigation("PrimaryUsers");

                    b.Navigation("RegionMemberships");

                    b.Navigation("SalaryTables");

                    b.Navigation("TokenTransactions");

                    b.Navigation("UserMemberships");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.CompanyRegistration", b =>
                {
                    b.Navigation("TakeoverRequests");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.CompanySalaryTable", b =>
                {
                    b.Navigation("AllowedBranches");

                    b.Navigation("ChangeLogs");

                    b.Navigation("Rates");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.Region", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.SelfBillingInvoice", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("LinkedLedgerEntries");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.User", b =>
                {
                    b.Navigation("CompanyMemberships");
                });

            modelBuilder.Entity("Jobsy.Core.Entities.Vacancy", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Clicks");

                    b.Navigation("Likes");

                    b.Navigation("SearchImpressions");

                    b.Navigation("Shares");
                });
#pragma warning restore 612, 618
        }
    }
}
