using Jobsy.Core.Rules;

namespace Jobsy.Core.Careers;

public static class CareerDreamCatalog
{
    public sealed record Entry(
        string Key,
        string Title,
        string Level,
        string Werkveld,
        string[] Aliases,
        string[] OccupationKeys);

    public static IReadOnlyList<Entry> All { get; } = Build();

    private static readonly Dictionary<string, Entry> ByKey =
        All.ToDictionary(e => e.Key, StringComparer.OrdinalIgnoreCase);

    private static readonly Dictionary<string, Entry> ByFoldedLookup = BuildFoldedLookup();

    public static Entry? FindByKey(string key)
    {
        if (string.IsNullOrWhiteSpace(key))
        {
            return null;
        }

        return ByKey.TryGetValue(key.Trim(), out var entry) ? entry : null;
    }

    public static Entry? FindByTitleOrAlias(string title)
    {
        if (string.IsNullOrWhiteSpace(title))
        {
            return null;
        }

        var folded = CareerOccupationKeys.Fold(title);
        return folded.Length == 0
            ? null
            : ByFoldedLookup.TryGetValue(folded, out var entry) ? entry : null;
    }

    public static IReadOnlyList<Entry> Search(string q, int max = 8)
    {
        if (string.IsNullOrWhiteSpace(q))
        {
            return [];
        }

        var folded = CareerOccupationKeys.Fold(q);
        if (folded.Length == 0)
        {
            return [];
        }

        var limit = Math.Clamp(max, 1, 40);
        var scored = new List<(Entry Entry, int Rank, int Len)>();

        foreach (var entry in All)
        {
            var titleFold = CareerOccupationKeys.Fold(entry.Title);
            var aliasFolds = entry.Aliases.Select(CareerOccupationKeys.Fold).ToArray();

            var prefix = titleFold.StartsWith(folded, StringComparison.Ordinal)
                         || aliasFolds.Any(a => a.StartsWith(folded, StringComparison.Ordinal));
            var contains = !prefix
                           && (titleFold.Contains(folded, StringComparison.Ordinal)
                               || aliasFolds.Any(a => a.Contains(folded, StringComparison.Ordinal)));

            if (!prefix && !contains)
            {
                continue;
            }

            var entryBoost = string.Equals(entry.Level, "Entry", StringComparison.Ordinal) ? 0 : 1;
            var rank = prefix ? entryBoost : 10 + entryBoost;
            scored.Add((entry, rank, titleFold.Length));
        }

        return scored
            .OrderBy(x => x.Rank)
            .ThenBy(x => x.Len)
            .ThenBy(x => x.Entry.Title, StringComparer.OrdinalIgnoreCase)
            .Select(x => x.Entry)
            .Take(limit)
            .ToList();
    }

    private static Dictionary<string, Entry> BuildFoldedLookup()
    {
        var map = new Dictionary<string, Entry>(StringComparer.Ordinal);
        foreach (var entry in All)
        {
            AddFold(map, entry.Title, entry);
            foreach (var alias in entry.Aliases)
            {
                AddFold(map, alias, entry);
            }
        }

        return map;
    }

    private static void AddFold(Dictionary<string, Entry> map, string raw, Entry entry)
    {
        var folded = CareerOccupationKeys.Fold(raw);
        if (folded.Length > 0)
        {
            map.TryAdd(folded, entry);
        }
    }

    private static Entry E(
        string key,
        string title,
        string level,
        string werkveld,
        string[] aliases,
        string[] occupationKeys)
        => new(key, title, level, werkveld, aliases, occupationKeys);

    private static IReadOnlyList<Entry> Build() =>
    [
        E("orderpicker", "Orderpicker", "Entry", "logistiek",
            ["order picker", "orderverzamelaar", "pick and pack"],
            ["orderpick", "magazijn", "logistiek", "pick"]),
        E("productiemedewerker", "Productiemedewerker", "Entry", "productie",
            ["productiewerk", "fabrieksmedewerker", "operator productie"],
            ["productie", "fabriek", "assemblage", "lijn"]),
        E("heftruckchauffeur", "Heftruckchauffeur", "Entry", "logistiek",
            ["heftruckchauffeur", "vorkheftruckchauffeur", "reachtruckchauffeur"],
            ["heftruck", "vorkheftruck", "magazijn", "logistiek"]),
        E("schoonmaker", "Schoonmaker", "Entry", "faciliteit",
            ["schoonmaakmedewerker", "interieurverzorger", "reiniger"],
            ["schoonmaak", "faciliteit", "interieur", "reiniging"]),
        E("magazijnmedewerker", "Magazijnmedewerker", "Entry", "logistiek",
            ["warehouse medewerker", "magazijn hulp", "logistiek medewerker"],
            ["magazijn", "logistiek", "warehouse", "expeditie"]),
        E("zorghulp", "Zorghulp", "Entry", "zorg",
            ["zorgassistente", "thuiszorghulp", "assistent zorg"],
            ["zorghulp", "zorg", "thuiszorg", "ondersteuning"]),
        E("helpende-zorg-en-welzijn", "Helpende zorg en welzijn", "Mbo2", "zorg",
            ["helpende", "helpende zorg", "HZW"],
            ["helpende", "zorg", "welzijn", "vvt"]),
        E("verzorgende-ig", "Verzorgende IG", "Mbo3", "zorg",
            ["verzorgende", "VIG", "verzorgende individuele gezondheidszorg"],
            ["verzorgende", "vig", "zorg", "verpleging"]),
        E("kok", "Kok", "Mbo2", "horeca",
            ["keukenhulp", "commis", "chef kok"],
            ["kok", "keuken", "horeca", "koken"]),
        E("bezorger", "Bezorger", "Entry", "transport",
            ["maaltijdbezorger", "pakketbezorger", "koerier"],
            ["bezorgen", "koerier", "pakket", "delivery"]),
        E("chauffeur-c", "Chauffeur C", "Mbo2", "transport",
            ["vrachtwagenchauffeur C", "chauffeur rijbewijs C"],
            ["chauffeur", "vrachtwagen", "rijbewijs", "transport"]),
        E("chauffeur-ce", "Chauffeur CE", "Mbo3", "transport",
            ["vrachtwagenchauffeur CE", "chauffeur met aanhanger"],
            ["chauffeur", "vrachtwagen", "ce", "transport"]),
        E("kassamedewerker", "Kassamedewerker", "Entry", "retail",
            ["kassière", "kassier", "cashier"],
            ["kassa", "winkel", "retail", "klant"]),
        E("tuinder", "Tuinder", "Entry", "groen",
            ["tuinbouwer", "glastuinbouwer"],
            ["tuinder", "tuinbouw", "groente", "plant"]),
        E("kasmedewerker", "Kasmedewerker", "Entry", "groen",
            ["glastuinbouwmedewerker", "kasarbeider", "kassenwerker"],
            ["kas", "glastuinbouw", "planten", "oogst"]),
        E("vakkenvuller", "Vakkenvuller", "Entry", "retail",
            ["vulploeg", "schappen vullen"],
            ["vakkenvullen", "winkel", "schappen", "retail"]),
        E("inpakker", "Inpakker", "Entry", "logistiek",
            ["verpakker", "packaging medewerker"],
            ["inpakken", "verpakken", "magazijn", "productie"]),
        E("assemblagemedewerker", "Assemblagemedewerker", "Entry", "productie",
            ["assembleur", "montage medewerker"],
            ["assemblage", "montage", "productie", "fabriek"]),
        E("afwasser", "Afwasser", "Entry", "horeca",
            ["keukenhulp afwas", "dishwasher"],
            ["afwas", "keuken", "horeca", "spoelkeuken"]),
        E("serveerder", "Serveerder", "Entry", "horeca",
            ["bediening", "ober", "serveerster"],
            ["bediening", "horeca", "restaurant", "gastvrijheid"]),
        E("barista", "Barista", "Entry", "horeca",
            ["koffiemedewerker", "cafémedewerker"],
            ["barista", "koffie", "café", "horeca"]),
        E("winkelmedewerker", "Winkelmedewerker", "Entry", "retail",
            ["verkoopmedewerker", "sales assistant"],
            ["winkel", "verkoop", "retail", "klant"]),
        E("postbezorger", "Postbezorger", "Entry", "transport",
            ["brievenbesteller", "postbode"],
            ["post", "bezorgen", "pakket", "distributie"]),
        E("fietsbezorger", "Fietsbezorger", "Entry", "transport",
            ["fietskoerier", "bike courier"],
            ["fiets", "bezorgen", "koerier", "delivery"]),
        E("glazenwasser", "Glazenwasser", "Entry", "faciliteit",
            ["raamwasser", "gevelreiniger"],
            ["glazenwassen", "ramen", "reiniging", "faciliteit"]),
        E("kamerbediende", "Kamerbediende", "Entry", "horeca",
            ["houskeeping", "kamerverzorging", "huishouding hotel"],
            ["kamer", "hotel", "schoonmaak", "horeca"]),
        E("facilitaire-medewerker", "Facilitaire medewerker", "Entry", "faciliteit",
            ["facility medewerker", "gebouwbeheerder assistent"],
            ["faciliteit", "gebouw", "onderhoud", "service"]),
        E("algemeen-medewerker", "Algemeen medewerker", "Entry", "productie",
            ["allround medewerker", "handyman assistent", "klusser"],
            ["algemeen", "allround", "productie", "hulp"]),
        E("recyclagemedewerker", "Recyclagemedewerker", "Entry", "milieu",
            ["sorteerder afval", "kringloopmedewerker"],
            ["recyclage", "afval", "sorteren", "milieu"]),
        E("afvalinzamelaar", "Afvalinzamelaar", "Entry", "milieu",
            ["vuilnisman", "vuilnisophaler", "reinigingsmedewerker"],
            ["afval", "inzameling", "reiniging", "milieu"]),
        E("wasstraatmedewerker", "Wasstraatmedewerker", "Entry", "automotive",
            ["autowasser", "carwash medewerker"],
            ["wasstraat", "auto", "reiniging", "carwash"]),
        E("host-hostess", "Host / hostess", "Entry", "horeca",
            ["hostess", "gastvrouw", "gastheer"],
            ["host", "hostess", "receptie", "gastvrijheid"]),
        E("callcentermedewerker", "Callcentermedewerker", "Entry", "klantenservice",
            ["klantenservicemedewerker", "telefoonmedewerker"],
            ["callcenter", "klantenservice", "telefoon", "support"]),
        E("parkeercontroleur", "Parkeercontroleur", "Entry", "handhaving",
            ["parkeerwacht", "boa parkeren"],
            ["parkeren", "controle", "handhaving", "boa"]),
        E("keukenhulp", "Keukenhulp", "Entry", "horeca",
            ["keukenassistent", "kitchen assistant"],
            ["keuken", "hulp", "horeca", "voorbereiding"]),
        E("bouwplaatsmedewerker", "Bouwplaatsmedewerker", "Entry", "bouw",
            ["bouwhelper", "opperman"],
            ["bouw", "bouwplaats", "hulp", "sjouwen"]),
        E("stratenmaker", "Stratenmaker", "Mbo2", "bouw",
            ["bestrating", "tegelzetter buiten"],
            ["stratenmaker", "bestrating", "bouw", "wegen"]),
        E("metselaar", "Metselaar", "Mbo2", "bouw",
            ["metselaar bouw", "steenmetselaar"],
            ["metselaar", "bouw", "stenen", "muur"]),
        E("timmerman", "Timmerman", "Mbo2", "bouw",
            ["timmervrouw", "houtbewerker"],
            ["timmerman", "hout", "bouw", "kozijn"]),
        E("schilder", "Schilder", "Mbo2", "bouw",
            ["huisschilder", "verver"],
            ["schilder", "verf", "bouw", "afwerking"]),
        E("dakdekker", "Dakdekker", "Mbo3", "bouw",
            ["dakdekker bitumen", "dakwerker"],
            ["dak", "dakdekker", "bouw", "bitumen"]),
        E("loodgieter", "Loodgieter", "Mbo3", "techniek",
            ["installatiemonteur sanitair", "sanitair monteur"],
            ["loodgieter", "sanitair", "installatie", "water"]),
        E("elektricien", "Elektricien", "Mbo3", "techniek",
            ["elektromonteur", "elektra monteur"],
            ["elektricien", "elektro", "installatie", "stroom"]),
        E("installatiemonteur", "Installatiemonteur", "Mbo3", "techniek",
            ["werktuigkundige installatie", "cv monteur"],
            ["installatie", "monteur", "techniek", "cv"]),
        E("automonteur", "Automonteur", "Mbo3", "automotive",
            ["autotechnicus", "personenautomonteur"],
            ["auto", "monteur", "garage", "apk"]),
        E("fietsenmaker", "Fietsenmaker", "Mbo2", "techniek",
            ["fietsenmonteur", "tweewielertechnicus"],
            ["fiets", "reparatie", "monteur", "tweewieler"]),
        E("lasser", "Lasser", "Mbo3", "techniek",
            ["lasser constructie", "MIG lasser"],
            ["lassen", "metaal", "constructie", "techniek"]),
        E("cnc-operator", "CNC-operator", "Mbo3", "techniek",
            ["cnc machinist", "verspaner"],
            ["cnc", "verspanen", "metaal", "machine"]),
        E("procesoperator", "Procesoperator", "Mbo3", "productie",
            ["operator procesindustrie", "procestechnoloog mbo"],
            ["proces", "operator", "industrie", "productie"]),
        E("kwaliteitscontroleur", "Kwaliteitscontroleur", "Mbo3", "productie",
            ["qc medewerker", "kwaliteitsmedewerker"],
            ["kwaliteit", "controle", "productie", "inspectie"]),
        E("logistiek-medewerker", "Logistiek medewerker", "Mbo2", "logistiek",
            ["logistiek assistent", "expeditiemedewerker"],
            ["logistiek", "expeditie", "magazijn", "transport"]),
        E("planner-logistiek", "Planner logistiek", "Mbo4", "logistiek",
            ["transportplanner", "routeplanner"],
            ["planner", "logistiek", "transport", "planning"]),
        E("teamleider-logistiek", "Teamleider logistiek", "Mbo4", "logistiek",
            ["magazijnchef", "supervisor logistiek"],
            ["teamleider", "logistiek", "magazijn", "leiding"]),
        E("expeditiemedewerker", "Expeditiemedewerker", "Entry", "logistiek",
            ["verzender", "shipping medewerker"],
            ["expeditie", "verzending", "logistiek", "pakket"]),
        E("inkoper", "Inkoper", "Mbo4", "administratie",
            ["inkoopmedewerker", "buyer"],
            ["inkoop", "leverancier", "contract", "administratie"]),
        E("verkoper", "Verkoper", "Mbo2", "retail",
            ["commercieel medewerker", "sales medewerker"],
            ["verkoop", "commercieel", "klant", "sales"]),
        E("filiaalmanager", "Filiaalmanager", "Mbo4", "retail",
            ["winkelmanager", "store manager"],
            ["filiaal", "manager", "winkel", "leiding"]),
        E("receptionist", "Receptionist", "Mbo2", "administratie",
            ["balie medewerker", "receptiemedewerker"],
            ["receptie", "balie", "telefoon", "ontvangst"]),
        E("administratief-medewerker", "Administratief medewerker", "Mbo2", "administratie",
            ["office assistent", "secretariaatsmedewerker"],
            ["administratie", "kantoor", "secretariaat", "office"]),
        E("secretaresse", "Secretaresse", "Mbo3", "administratie",
            ["managementassistent", "directiesecretaresse"],
            ["secretariaat", "agenda", "kantoor", "assistent"]),
        E("boekhouder", "Boekhouder", "Mbo4", "administratie",
            ["financieel administratief", "assistant accountant"],
            ["boekhouding", "financieel", "administratie", "cijfers"]),
        E("accountant", "Accountant", "Hbo", "administratie",
            ["registeraccountant", "AA accountant"],
            ["accountant", "audit", "financieel", "jaarrekening"]),
        E("hr-adviseur", "HR-adviseur", "Hbo", "hr",
            ["personeelsadviseur", "HR business partner"],
            ["hr", "personeel", "werving", "arbeidsvoorwaarden"]),
        E("payroll-medewerker", "Payroll medewerker", "Mbo4", "hr",
            ["salarisadministratie", "payroll officer"],
            ["payroll", "salaris", "loon", "administratie"]),
        E("verpleegkundige", "Verpleegkundige", "Hbo", "zorg",
            ["HBO-V", "wijkverpleegkundige", "verpleger"],
            ["verpleegkundige", "verpleging", "zorg", "patient"]),
        E("verpleegkundige-mbo", "Verpleegkundige MBO", "Mbo4", "zorg",
            ["mbo-verpleegkundige", "niveau 4 verpleegkundige"],
            ["verpleegkundige", "mbo", "zorg", "kliniek"]),
        E("doktersassistent", "Doktersassistent", "Mbo4", "zorg",
            ["huisartsenassistent", "praktijkassistent"],
            ["doktersassistent", "huisarts", "praktijk", "zorg"]),
        E("tandartsassistent", "Tandartsassistent", "Mbo4", "zorg",
            ["mondzorgassistent", "dental assistant"],
            ["tandarts", "mondzorg", "assistent", "praktijk"]),
        E("apothekersassistent", "Apothekersassistent", "Mbo4", "zorg",
            ["apotheekmedewerker", "farmamedewerker"],
            ["apotheek", "medicijn", "assistent", "farmacie"]),
        E("fysiotherapeut", "Fysiotherapeut", "Hbo", "zorg",
            ["fysio", "manueel therapeut"],
            ["fysiotherapie", "revalidatie", "beweging", "zorg"]),
        E("ergotherapeut", "Ergotherapeut", "Hbo", "zorg",
            ["ergotherapie"],
            ["ergotherapie", "revalidatie", "zorg", "zelfredzaamheid"]),
        E("logopedist", "Logopedist", "Hbo", "zorg",
            ["spraaktherapeut"],
            ["logopedie", "spraak", "taal", "zorg"]),
        E("diëtist", "Diëtist", "Hbo", "zorg",
            ["voedingsdeskundige"],
            ["dieet", "voeding", "zorg", "advies"]),
        E("verloskundige", "Verloskundige", "Hbo", "zorg",
            ["vroedvrouw", "vroedman"],
            ["verloskunde", "zwangerschap", "bevalling", "zorg"]),
        E("apotheker", "Apotheker", "Wo", "zorg",
            ["ziekenhuisapotheker", "openbaar apotheker"],
            ["apotheker", "farmacie", "medicijn", "zorg"]),
        E("huisarts", "Huisarts", "Wo", "zorg",
            ["dokter", "arts huisartsgeneeskunde"],
            ["huisarts", "dokter", "geneeskunde", "praktijk"]),
        E("tandarts", "Tandarts", "Wo", "zorg",
            ["mondzorgverlener"],
            ["tandarts", "mondzorg", "gebit", "praktijk"]),
        E("psycholoog", "Psycholoog", "Wo", "zorg",
            ["gz-psycholoog", "klinisch psycholoog"],
            ["psychologie", "therapie", "ggz", "zorg"]),
        E("sociaal-werker", "Sociaal werker", "Hbo", "welzijn",
            ["maatschappelijk werker", "social worker"],
            ["sociaal", "welzijn", "hulpverlening", "maatschappelijk"]),
        E("jeugdhulpverlener", "Jeugdhulpverlener", "Hbo", "welzijn",
            ["jeugdzorgwerker", "jeugdcoach"],
            ["jeugd", "hulpverlening", "welzijn", "gezin"]),
        E("activiteitenbegeleider", "Activiteitenbegeleider", "Mbo4", "welzijn",
            ["dagbesteding begeleider", "activiteitenbegeleiding"],
            ["activiteiten", "begeleiding", "welzijn", "dagbesteding"]),
        E("woonbegeleider", "Woonbegeleider", "Mbo4", "welzijn",
            ["begeleid wonen", "ambulant begeleider"],
            ["wonen", "begeleiding", "welzijn", "zorg"]),
        E("pedagogisch-medewerker", "Pedagogisch medewerker", "Mbo3", "onderwijs",
            ["kinderopvang medewerker", "pm kinderopvang"],
            ["pedagogisch", "kinderopvang", "kinderen", "opvang"]),
        E("onderwijsassistent", "Onderwijsassistent", "Mbo4", "onderwijs",
            ["klassenassistent", "onderwijs ondersteuner"],
            ["onderwijs", "assistent", "klas", "school"]),
        E("leerkracht", "Leerkracht", "Hbo", "onderwijs",
            ["docent basisonderwijs", "juf", "meester", "leraar basisschool"],
            ["leerkracht", "basisonderwijs", "pabo", "school"]),
        E("docent-vo", "Docent voortgezet onderwijs", "Hbo", "onderwijs",
            ["leraar middelbare school", "vakdocent"],
            ["docent", "voortgezet", "onderwijs", "school"]),
        E("intern-begeleider", "Intern begeleider", "Hbo", "onderwijs",
            ["IB-er", "zorgcoördinator school"],
            ["intern", "begeleider", "onderwijs", "zorg"]),
        E("kapper", "Kapper", "Mbo2", "uiterlijke-verzorging",
            ["haarstylist", "barber", "coupeuse"],
            ["kapper", "haar", "salon", "styling"]),
        E("schoonheidsspecialist", "Schoonheidsspecialist", "Mbo3", "uiterlijke-verzorging",
            ["beautyspecialist", "huidtherapeut mbo"],
            ["schoonheid", "huid", "salon", "behandeling"]),
        E("nagelstylist", "Nagelstylist", "Mbo2", "uiterlijke-verzorging",
            ["nail artist", "manicure"],
            ["nagel", "styling", "salon", "beauty"]),
        E("software-developer", "Software developer", "Hbo", "ict",
            ["programmeur", "software engineer", "developer"],
            ["software", "programmeren", "code", "development"]),
        E("webdeveloper", "Webdeveloper", "Mbo4", "ict",
            ["frontend developer", "webprogrammeur"],
            ["web", "frontend", "html", "development"]),
        E("applicatiebeheerder", "Applicatiebeheerder", "Mbo4", "ict",
            ["application manager", "functioneel beheerder"],
            ["applicatie", "beheer", "ict", "support"]),
        E("systeembeheerder", "Systeembeheerder", "Mbo4", "ict",
            ["netwerkbeheerder", "IT-beheerder"],
            ["systeem", "netwerk", "server", "ict"]),
        E("helpdeskmedewerker", "Helpdeskmedewerker", "Mbo3", "ict",
            ["IT-support", "servicedesk medewerker"],
            ["helpdesk", "support", "ict", "servicedesk"]),
        E("data-analist", "Data-analist", "Hbo", "ict",
            ["data analyst", "business intelligence analist"],
            ["data", "analyse", "rapportage", "bi"]),
        E("cybersecurity-specialist", "Cybersecurity specialist", "Hbo", "ict",
            ["security analist", "infosec specialist"],
            ["security", "cyber", "netwerk", "veiligheid"]),
        E("ux-designer", "UX-designer", "Hbo", "ict",
            ["interaction designer", "user experience designer"],
            ["ux", "design", "gebruiker", "interface"]),
        E("grafisch-ontwerper", "Grafisch ontwerper", "Mbo4", "creatief",
            ["vormgever", "graphic designer"],
            ["grafisch", "design", "vormgeving", "layout"]),
        E("fotograaf", "Fotograaf", "Mbo4", "creatief",
            ["beeldmaker", "commercial fotograaf"],
            ["foto", "beeld", "camera", "studio"]),
        E("videograaf", "Videograaf", "Mbo4", "creatief",
            ["cameraman", "video editor"],
            ["video", "camera", "montage", "media"]),
        E("contentmaker", "Contentmaker", "Mbo4", "marketing",
            ["content creator", "social media maker"],
            ["content", "social", "media", "creatie"]),
        E("marketeer", "Marketeer", "Hbo", "marketing",
            ["marketingmedewerker", "online marketeer"],
            ["marketing", "campagne", "communicatie", "online"]),
        E("communicatieadviseur", "Communicatieadviseur", "Hbo", "marketing",
            ["woordvoerder", "pr adviseur"],
            ["communicatie", "pr", "media", "advies"]),
        E("journalist", "Journalist", "Hbo", "media",
            ["verslaggever", "redacteur"],
            ["journalistiek", "nieuws", "schrijven", "media"]),
        E("eventmanager", "Eventmanager", "Hbo", "events",
            ["evenementenorganisator", "event planner"],
            ["event", "organisatie", "evenement", "planning"]),
        E("horecamedewerker", "Horecamedewerker", "Entry", "horeca",
            ["horecahulp", "allround horeca"],
            ["horeca", "bediening", "keuken", "gastvrijheid"]),
        E("restaurantmanager", "Restaurantmanager", "Mbo4", "horeca",
            ["zaakvoerder restaurant", "horecamanager"],
            ["restaurant", "manager", "horeca", "leiding"]),
        E("bakker", "Bakker", "Mbo2", "voeding",
            ["brood bakker", "banketbakker assistent"],
            ["bakker", "brood", "banket", "oven"]),
        E("banketbakker", "Banketbakker", "Mbo3", "voeding",
            ["patissier", "gebakkoker"],
            ["banket", "gebak", "patisserie", "zoet"]),
        E("slager", "Slager", "Mbo2", "voeding",
            ["beenhouwer", "vleesbewerker"],
            ["slager", "vlees", "winkel", "ambacht"]),
        E("groente-fruithandelaar", "Groente- en fruithandelaar", "Mbo2", "voeding",
            ["groenteboer", "fruitverkoper"],
            ["groente", "fruit", "handel", "winkel"]),
        E("hovenier", "Hovenier", "Mbo2", "groen",
            ["tuinman", "groenvoorziener"],
            ["hovenier", "tuin", "groen", "planten"]),
        E("groenvoorziener", "Groenvoorziener", "Mbo2", "groen",
            ["parkmedewerker", "gemeentegroen"],
            ["groen", "park", "onderhoud", "buiten"]),
        E("boomverzorger", "Boomverzorger", "Mbo3", "groen",
            ["boomchirurg", "arboret"],
            ["boom", "snoeien", "groen", "klimmen"]),
        E("dierenverzorger", "Dierenverzorger", "Mbo3", "dieren",
            ["dierentuinverzorger", "asielmedewerker"],
            ["dieren", "verzorging", "asiel", "stal"]),
        E("dierenartsassistent", "Dierenartsassistent", "Mbo4", "dieren",
            ["paraveterinair", "vet assistent"],
            ["dierenarts", "assistent", "dier", "praktijk"]),
        E("dierenarts", "Dierenarts", "Wo", "dieren",
            ["veterinair", "vet"],
            ["dierenarts", "dier", "geneeskunde", "praktijk"]),
        E("beveiliger", "Beveiliger", "Mbo2", "veiligheid",
            ["security medewerker", "objectbeveiliger"],
            ["beveiliging", "security", "toegang", "surveillance"]),
        E("boa", "BOA", "Mbo3", "handhaving",
            ["buitengewoon opsporingsambtenaar", "handhaver"],
            ["boa", "handhaving", "opsporing", "toezicht"]),
        E("politieagent", "Politieagent", "Mbo4", "veiligheid",
            ["agent", "wijkagent"],
            ["politie", "agent", "veiligheid", "opsporing"]),
        E("brandweerman", "Brandweerman / -vrouw", "Mbo3", "veiligheid",
            ["brandweer", "brandweervrouw"],
            ["brandweer", "blussen", "hulpverlening", "veiligheid"]),
        E("ambulanceverpleegkundige", "Ambulanceverpleegkundige", "Mbo4", "zorg",
            ["ambulancebroeder", "paramedicus ambulance"],
            ["ambulance", "spoed", "verpleging", "zorg"]),
        E("chauffeur-taxi", "Taxichauffeur", "Entry", "transport",
            ["taxi chauffeur", "personenvervoerder"],
            ["taxi", "chauffeur", "vervoer", "klant"]),
        E("buschauffeur", "Buschauffeur", "Mbo2", "transport",
            ["stadsbuschauffeur", "touringchauffeur"],
            ["bus", "chauffeur", "ov", "passagiers"]),
        E("machinist", "Machinist", "Mbo3", "transport",
            ["treinmachinist", "railmachinist"],
            ["machinist", "trein", "rail", "vervoer"]),
        E("conducteur", "Conducteur", "Mbo2", "transport",
            ["treinconducteur", "hoofdconducteur"],
            ["conducteur", "trein", "ov", "controle"]),
        E("piloot", "Piloot", "Wo", "luchtvaart",
            ["verkeersvlieger", "gezagvoerder"],
            ["piloot", "vliegen", "cockpit", "luchtvaart"]),
        E("cabinemedewerker", "Cabinemedewerker", "Mbo3", "luchtvaart",
            ["stewardess", "cabin crew", "purser"],
            ["cabine", "vlucht", "luchtvaart", "passagiers"]),
        E("grondafhandelaar", "Grondafhandelaar", "Entry", "luchtvaart",
            ["ramp agent", "platformmedewerker luchthaven"],
            ["grond", "luchthaven", "bagage", "afhandeling"]),
        E("vliegtuigmonteur", "Vliegtuigmonteur", "Mbo4", "luchtvaart",
            ["avionica monteur", "aircraft mechanic"],
            ["vliegtuig", "monteur", "luchtvaart", "onderhoud"]),
        E("makelaar", "Makelaar", "Mbo4", "vastgoed",
            ["vastgoedmakelaar", "woningmakelaar"],
            ["makelaar", "woning", "vastgoed", "verkoop"]),
        E("vastgoedbeheerder", "Vastgoedbeheerder", "Hbo", "vastgoed",
            ["property manager", "woonconsulent"],
            ["vastgoed", "beheer", "huur", "woning"]),
        E("juridisch-medewerker", "Juridisch medewerker", "Mbo4", "juridisch",
            ["paralegal", "juridisch assistent"],
            ["juridisch", "recht", "dossier", "wet"]),
        E("advocaat", "Advocaat", "Wo", "juridisch",
            ["jurist advocaat", "raadsman"],
            ["advocaat", "recht", "proces", "advies"]),
        E("notaris", "Notaris", "Wo", "juridisch",
            ["kandidaat-notaris"],
            ["notaris", "akte", "recht", "vastgoed"]),
        E("rechter", "Rechter", "Wo", "juridisch",
            ["raadsheer", "kantonrechter"],
            ["rechter", "rechtspraak", "vonnis", "recht"]),
        E("ambtenaar", "Ambtenaar", "Hbo", "overheid",
            ["beleidsmedewerker", "overheidsmedewerker"],
            ["ambtenaar", "beleid", "overheid", "bestuur"]),
        E("beleidsadviseur", "Beleidsadviseur", "Hbo", "overheid",
            ["policy advisor", "strategisch adviseur"],
            ["beleid", "advies", "overheid", "strategie"]),
        E("projectleider", "Projectleider", "Hbo", "management",
            ["projectmanager", "projectcoördinator"],
            ["project", "leiding", "planning", "coordinatie"]),
        E("teamleider", "Teamleider", "Mbo4", "management",
            ["teamchef", "supervisor"],
            ["teamleider", "leiding", "team", "coaching"]),
        E("ondernemer", "Ondernemer", "Hbo", "ondernemerschap",
            ["zzp-er", "bedrijfseigenaar", "startup oprichter"],
            ["ondernemen", "bedrijf", "zzp", "eigen"]),
        E("personal-trainer", "Personal trainer", "Mbo4", "sport",
            ["fitnesscoach", "PT"],
            ["fitness", "training", "sport", "coaching"]),
        E("sportinstructeur", "Sportinstructeur", "Mbo3", "sport",
            ["sportcoach", "bewegingsagoog mbo"],
            ["sport", "instructie", "les", "beweging"]),
        E("fysiotherapie-assistent", "Fysiotherapie-assistent", "Mbo4", "zorg",
            ["fysio-assistent"],
            ["fysio", "assistent", "revalidatie", "zorg"]),
        E("laborant", "Laborant", "Mbo4", "lab",
            ["analist laboratorium", "labmedewerker"],
            ["lab", "analyse", "monster", "onderzoek"]),
        E("onderzoeker", "Onderzoeker", "Wo", "onderzoek",
            ["wetenschappelijk medewerker", "research associate"],
            ["onderzoek", "wetenschap", "analyse", "publicatie"]),
        E("ingenieur", "Ingenieur", "Hbo", "techniek",
            ["werktuigbouwkundig ingenieur", "technisch ingenieur"],
            ["ingenieur", "techniek", "ontwerp", "engineering"]),
        E("civiel-ingenieur", "Civiel ingenieur", "Hbo", "bouw",
            ["civiele techniek", "weg- en waterbouw"],
            ["civiel", "bouw", "infrastructuur", "techniek"]),
        E("architect", "Architect", "Wo", "bouw",
            ["bouwkundig architect", "interieurarchitect"],
            ["architectuur", "ontwerp", "bouw", "gebouw"]),
        E("bouwkundige", "Bouwkundige", "Hbo", "bouw",
            ["bouwkundig tekenaar", "BIM modelleur"],
            ["bouwkunde", "tekenen", "bouw", "constructie"]),
        E("werkvoorbereider", "Werkvoorbereider", "Mbo4", "bouw",
            ["calculator bouw", "uitvoerder assistent"],
            ["werkvoorbereiding", "bouw", "planning", "calculatie"]),
        E("uitvoerder-bouw", "Uitvoerder bouw", "Mbo4", "bouw",
            ["bouwuitvoerder", "projectuitvoerder"],
            ["uitvoerder", "bouw", "bouwplaats", "leiding"]),
        E("montage-monteur", "Montagemonteur", "Mbo2", "techniek",
            ["monteur montage", "servicemonteur assistent"],
            ["montage", "monteur", "installatie", "techniek"]),
        E("servicemonteur", "Servicemonteur", "Mbo3", "techniek",
            ["storingsmonteur", "onderhoudsmonteur"],
            ["service", "monteur", "storing", "onderhoud"]),
        E("koeltechnicus", "Koeltechnicus", "Mbo3", "techniek",
            ["airco monteur", "koudetechniek"],
            ["koel", "airco", "techniek", "installatie"]),
        E("zonnepaneelmonteur", "Zonnepaneelmonteur", "Mbo3", "techniek",
            ["solar monteur", "pv-installateur"],
            ["zonnepaneel", "solar", "duurzaam", "installatie"]),
        E("duurzaamheidsadviseur", "Duurzaamheidsadviseur", "Hbo", "milieu",
            ["energieadviseur", "sustainability consultant"],
            ["duurzaam", "energie", "milieu", "advies"]),
        E("milieukundige", "Milieukundige", "Hbo", "milieu",
            ["milieuadviseur", "environmental specialist"],
            ["milieu", "duurzaam", "onderzoek", "advies"]),
        E("logistiek-supervisor", "Logistiek supervisor", "Mbo4", "logistiek",
            ["shiftleader magazijn", "ploegleider logistiek"],
            ["supervisor", "logistiek", "ploeg", "magazijn"]),
        E("inkoopassistent", "Inkoopassistent", "Mbo3", "administratie",
            ["inkoopmedewerker junior"],
            ["inkoop", "bestelling", "leverancier", "administratie"]),
        E("debiteurenadministratie", "Debiteurenadministrateur", "Mbo3", "administratie",
            ["debiteuren medewerker", "accounts receivable"],
            ["debiteuren", "factuur", "administratie", "betaling"]),
        E("crediteurenadministratie", "Crediteurenadministrateur", "Mbo3", "administratie",
            ["crediteuren medewerker", "accounts payable"],
            ["crediteuren", "inkoopfactuur", "administratie", "betaling"]),
        E("customer-success", "Customer success medewerker", "Hbo", "klantenservice",
            ["customer success manager", "klantbeheerder"],
            ["customer", "klant", "succes", "retentie"]),
        E("accountmanager", "Accountmanager", "Hbo", "sales",
            ["relatiebeheerder", "key account manager"],
            ["account", "verkoop", "relatie", "klant"]),
        E("inside-sales", "Inside sales medewerker", "Mbo4", "sales",
            ["binnendienst verkoper", "telesales"],
            ["sales", "binnendienst", "verkoop", "telefoon"]),
        E("buitendienst-verkoper", "Buitendienstverkoper", "Mbo4", "sales",
            ["field sales", "rayonmanager"],
            ["buitendienst", "verkoop", "bezoek", "relatie"]),
        E("recruitment-adviseur", "Recruitment adviseur", "Hbo", "hr",
            ["recruiter", "wervingsadviseur"],
            ["recruitment", "werving", "selectie", "hr"]),
        E("loopbaancoach", "Loopbaancoach", "Hbo", "hr",
            ["carrièrecoach", "outplacement coach"],
            ["loopbaan", "coaching", "carriere", "advies"]),
        E("trainer", "Trainer", "Hbo", "onderwijs",
            ["cursusleider", "bedrijfstrainer"],
            ["training", "opleiding", "les", "coaching"]),
        E("bibliothecaris", "Bibliothecaris", "Hbo", "cultuur",
            ["informatiespecialist", "mediaconsulent"],
            ["bibliotheek", "informatie", "boeken", "media"]),
        E("archivaris", "Archivaris", "Hbo", "cultuur",
            ["documentalist", "archiefmedewerker"],
            ["archief", "documenten", "bewaring", "onderzoek"]),
        E("museummedewerker", "Museummedewerker", "Mbo3", "cultuur",
            ["rondleider museum", "publieksbegeleider"],
            ["museum", "publiek", "cultuur", "rondleiding"]),
        E("acteur", "Acteur", "Hbo", "creatief",
            ["actrice", "toneelspeler"],
            ["acteur", "toneel", "film", "spel"]),
        E("muzikant", "Muzikant", "Hbo", "creatief",
            ["muziekdocent", "artiest muziek"],
            ["muziek", "optreden", "instrument", "artiest"]),
        E("dansdocent", "Dansdocent", "Hbo", "creatief",
            ["dansleraar", "choreograaf docent"],
            ["dans", "les", "beweging", "choreografie"]),
        E("vertaler", "Vertaler", "Hbo", "talen",
            ["tolk", "vertaalspecialist"],
            ["vertalen", "taal", "tekst", "tolken"]),
        E("tolk", "Tolk", "Hbo", "talen",
            ["gebarentolk", "conferentietolk"],
            ["tolken", "taal", "gesprek", "communicatie"]),
        E("chauffeur-bestelwagen", "Bestelwagenchauffeur", "Entry", "transport",
            ["bestelautochauffeur", "busje chauffeur"],
            ["bestelwagen", "chauffeur", "distributie", "bezorgen"]),
        E("magazijnmanager", "Magazijnmanager", "Mbo4", "logistiek",
            ["warehouse manager", "hoofd magazijn"],
            ["magazijn", "manager", "logistiek", "leiding"]),
        E("kwaliteitsmanager", "Kwaliteitsmanager", "Hbo", "productie",
            ["QA manager", "kwaliteitscoördinator"],
            ["kwaliteit", "manager", "proces", "audit"]),
        E("productiemanager", "Productiemanager", "Hbo", "productie",
            ["plant manager", "fabrieksleider"],
            ["productie", "manager", "fabriek", "leiding"]),
        E("onderhoudstechnicus", "Onderhoudstechnicus", "Mbo4", "techniek",
            ["maintenance engineer mbo", "technisch onderhoud"],
            ["onderhoud", "techniek", "machine", "storing"]),
        E("mechatronicus", "Mechatronicus", "Mbo4", "techniek",
            ["mechatronica monteur", "robotica monteur"],
            ["mechatronica", "robotica", "techniek", "automatisering"]),
        E("elektrotechnicus", "Elektrotechnicus", "Mbo4", "techniek",
            ["elektrotechniek", "sterkstroom technicus"],
            ["elektro", "techniek", "installatie", "stroom"]),
        E("werktuigbouwkundige", "Werktuigbouwkundige", "Hbo", "techniek",
            ["mechanical engineer", "werktuigbouw"],
            ["werktuigbouw", "constructie", "machine", "ontwerp"]),
        E("chemisch-analist", "Chemisch analist", "Mbo4", "lab",
            ["laboratoriumanalist chemie", "chemisch laborant"],
            ["chemie", "analyse", "lab", "monster"]),
        E("biologisch-medisch-analist", "Biologisch medisch analist", "Mbo4", "lab",
            ["BMA", "klinisch chemisch analist"],
            ["biologisch", "medisch", "lab", "analyse"]),
        E("apothekersassistente-ziekenhuis", "Ziekenhuisapothekersassistent", "Mbo4", "zorg",
            ["ziekenhuisapotheek assistent"],
            ["apotheek", "ziekenhuis", "medicijn", "assistent"]),
        E("operatieassistent", "Operatieassistent", "Mbo4", "zorg",
            ["OK-assistent", "scrub nurse"],
            ["operatie", "ok", "assistent", "chirurgie"]),
        E("anesthesiemedewerker", "Anesthesiemedewerker", "Mbo4", "zorg",
            ["anesthesieassistent"],
            ["anesthesie", "operatie", "zorg", "assistent"]),
        E("radiodiagnostisch-laborant", "Radiodiagnostisch laborant", "Mbo4", "zorg",
            ["MBRT", "röntgenlaborant"],
            ["radiologie", "rontgen", "beeldvorming", "zorg"]),
        E("mondhygienist", "Mondhygiënist", "Hbo", "zorg",
            ["mondzorgkundige"],
            ["mondhygiene", "tandvlees", "preventie", "mondzorg"]),
        E("orthopedagoog", "Orthopedagoog", "Wo", "onderwijs",
            ["gedragswetenschapper onderwijs"],
            ["orthopedagogiek", "gedrag", "kinderen", "onderwijs"]),
        E("schoolleider", "Schoolleider", "Hbo", "onderwijs",
            ["directeur school", "rector"],
            ["schoolleider", "directie", "onderwijs", "leiding"]),
        E("conciërge", "Conciërge", "Entry", "faciliteit",
            ["schoolconciërge", "portier"],
            ["concierge", "gebouw", "toegang", "onderhoud"]),
        E("schoonmaakleider", "Schoonmaakleider", "Mbo3", "faciliteit",
            ["ploegleider schoonmaak", "schoonmaakcoördinator"],
            ["schoonmaak", "leiding", "faciliteit", "team"]),
        E("cateringmedewerker", "Cateringmedewerker", "Entry", "horeca",
            ["cateraar", "buffetmedewerker"],
            ["catering", "eten", "buffet", "horeca"]),
        E("sommelier", "Sommelier", "Mbo4", "horeca",
            ["wijnadviseur", "wijnkelner"],
            ["wijn", "sommelier", "horeca", "advies"]),
        E("barista-trainer", "Barista trainer", "Mbo3", "horeca",
            ["koffietrainer"],
            ["barista", "training", "koffie", "horeca"]),
        E("hotelreceptionist", "Hotelreceptionist", "Mbo3", "horeca",
            ["front office hotel", "hotelbalie"],
            ["hotel", "receptie", "checkin", "gastvrijheid"]),
        E("reisadviseur", "Reisadviseur", "Mbo4", "toerisme",
            ["reisbureau medewerker", "travel consultant"],
            ["reis", "vakantie", "boeking", "advies"]),
        E("tourguide", "Tourguide", "Mbo3", "toerisme",
            ["rondleider", "gids"],
            ["tour", "gids", "toerisme", "rondleiding"]),
        E("callcenter-teamleider", "Callcenter teamleider", "Mbo4", "klantenservice",
            ["supervisor klantenservice"],
            ["callcenter", "teamleider", "klantenservice", "leiding"]),
        E("compliance-officer", "Compliance officer", "Hbo", "juridisch",
            ["compliance adviseur", "integrity officer"],
            ["compliance", "regelgeving", "risico", "audit"]),
        E("financial-controller", "Financial controller", "Hbo", "administratie",
            ["controller", "business controller"],
            ["controller", "financieel", "rapportage", "budget"]),
        E("actuaris", "Actuaris", "Wo", "administratie",
            ["actuarieel analist"],
            ["actuaris", "verzekering", "risico", "cijfers"]),
        E("econoom", "Econoom", "Wo", "onderzoek",
            ["economisch analist"],
            ["economie", "analyse", "beleid", "onderzoek"]),
        E("statisticus", "Statisticus", "Wo", "onderzoek",
            ["statistisch analist", "data scientist wo"],
            ["statistiek", "data", "analyse", "onderzoek"]),
        E("software-architect", "Software architect", "Hbo", "ict",
            ["solution architect", "technisch architect"],
            ["architectuur", "software", "ontwerp", "systeem"]),
        E("devops-engineer", "DevOps engineer", "Hbo", "ict",
            ["platform engineer", "sre"],
            ["devops", "cloud", "ci", "infrastructuur"]),
        E("tester", "Softwaretester", "Mbo4", "ict",
            ["QA tester", "testanalist"],
            ["test", "kwaliteit", "software", "bug"]),
        E("scrum-master", "Scrum master", "Hbo", "ict",
            ["agile coach", "delivery lead"],
            ["scrum", "agile", "team", "facilitatie"]),
        E("product-owner", "Product owner", "Hbo", "ict",
            ["productmanager digitaal"],
            ["product", "backlog", "stakeholder", "agile"]),
        E("business-analist", "Business analist", "Hbo", "ict",
            ["informatieanalist", "requirements analist"],
            ["business", "analyse", "proces", "requirements"]),
        E("erp-consultant", "ERP-consultant", "Hbo", "ict",
            ["SAP consultant", "functioneel consultant"],
            ["erp", "sap", "proces", "implementatie"]),
        E("netwerkengineer", "Netwerkengineer", "Hbo", "ict",
            ["netwerkspecialist", "network engineer"],
            ["netwerk", "router", "firewall", "infrastructuur"]),
        E("cloud-engineer", "Cloud engineer", "Hbo", "ict",
            ["cloud architect junior", "azure engineer"],
            ["cloud", "azure", "aws", "infrastructuur"]),
        E("ai-specialist", "AI-specialist", "Wo", "ict",
            ["machine learning engineer", "data scientist AI"],
            ["ai", "machinelearning", "model", "data"]),
        E("game-developer", "Game developer", "Hbo", "ict",
            ["gamedev", "spelontwikkelaar"],
            ["game", "unity", "programmeren", "spel"]),
        E("technisch-tekenaar", "Technisch tekenaar", "Mbo4", "techniek",
            ["CAD tekenaar", "constructietekenaar"],
            ["tekenen", "cad", "ontwerp", "techniek"]),
        E("landmeter", "Landmeter", "Hbo", "bouw",
            ["geodeet", "landmeetkundige"],
            ["landmeten", "meting", "kaart", "grond"]),
        E("wegenwachter", "Wegenwachter", "Mbo3", "automotive",
            ["pechhulp monteur", "ANWB monteur"],
            ["wegenwacht", "pechhulp", "auto", "hulp"]),
        E("bandenspecialist", "Bandenspecialist", "Mbo2", "automotive",
            ["bandenmonteur", "bandenservice"],
            ["banden", "auto", "montage", "garage"]),
        E("schadehersteller", "Schadehersteller", "Mbo3", "automotive",
            ["autoschade hersteller", "plaatwerker auto"],
            ["schade", "auto", "plaatwerk", "spuiten"]),
        E("lasser-pijp", "Pijplasser", "Mbo3", "techniek",
            ["pipe welder", "leidinglasser"],
            ["pijp", "lassen", "leiding", "metaal"]),
        E("kraanmachinist", "Kraanmachinist", "Mbo3", "bouw",
            ["hijskraanmachinist", "torenkraanmachinist"],
            ["kraan", "hijsen", "bouw", "machinist"]),
        E("grondwerker", "Grondwerker", "Entry", "bouw",
            ["graafmachinemedewerker", "civiel hulp"],
            ["grondwerk", "bouw", "graaf", "infrastructuur"]),
        E("isolatiemonteur", "Isolatiemonteur", "Mbo2", "bouw",
            ["spouwmuurisolateur", "dakisolatiemonteur"],
            ["isolatie", "duurzaam", "bouw", "energie"]),
        E("tegelzetter", "Tegelzetter", "Mbo2", "bouw",
            ["tegeltimmerman", "vloerlegger tegels"],
            ["tegel", "badkamer", "vloer", "bouw"]),
        E("stukadoor", "Stukadoor", "Mbo2", "bouw",
            ["pleisteraar", "afwerker muren"],
            ["stucwerk", "pleister", "muur", "bouw"]),
        E("vloerlegger", "Vloerlegger", "Mbo2", "bouw",
            ["parketlegger", "laminaatlegger"],
            ["vloer", "parket", "laminaat", "bouw"]),
        E("interieurbouwer", "Interieurbouwer", "Mbo3", "bouw",
            ["meubelmaker interieur", "keukenmonteur"],
            ["interieur", "meubel", "hout", "montage"]),
        E("meubelmaker", "Meubelmaker", "Mbo3", "creatief",
            ["houtbewerker meubel", "cabinetmaker"],
            ["meubel", "hout", "ambacht", "maatwerk"]),
        E("modeverkoper", "Modeverkoper", "Entry", "retail",
            ["kledingverkoper", "fashion advisor"],
            ["mode", "kleding", "verkoop", "winkel"]),
        E("visagist", "Visagist", "Mbo3", "uiterlijke-verzorging",
            ["make-up artist", "makeup artist"],
            ["makeup", "visagie", "beauty", "styling"]),
        E("stylist", "Stylist", "Mbo4", "creatief",
            ["personal shopper", "modeadviseur"],
            ["styling", "mode", "advies", "look"]),
        E("juwelier", "Juwelier", "Mbo3", "retail",
            ["goudsmid verkoper", "sieradenverkoper"],
            ["juweel", "sieraad", "goud", "verkoop"]),
        E("opticien", "Opticien", "Mbo4", "zorg",
            ["brillenadviseur", "optiekmedewerker"],
            ["opticien", "bril", "zicht", "advies"]),
        E("horlogemaker", "Horlogemaker", "Mbo3", "techniek",
            ["uurwerkmaker", "horloge hersteller"],
            ["horloge", "reparatie", "precisie", "ambacht"]),
        E("bloemist", "Bloemist", "Mbo2", "retail",
            ["bloemenverkoper", "florist"],
            ["bloem", "boeket", "winkel", "styling"]),
        E("dierenwinkelmedewerker", "Dierenwinkelmedewerker", "Entry", "retail",
            ["petshop medewerker"],
            ["dieren", "winkel", "voeding", "advies"]),
        E("supermarktmanager", "Supermarktmanager", "Mbo4", "retail",
            ["store manager supermarket", "filiaalmanager supermarkt"],
            ["supermarkt", "manager", "retail", "leiding"]),
        E("vers-medewerker", "Versmedewerker", "Entry", "retail",
            ["slagerij medewerker supermarkt", "afdeling vers"],
            ["vers", "vlees", "kaas", "supermarkt"]),
        E("bakkerij-medewerker", "Bakkerijmedewerker", "Entry", "retail",
            ["broodafdeling medewerker"],
            ["bakkerij", "brood", "winkel", "vers"]),
        E("magazijn-orderpicker-koude", "Orderpicker koel/vries", "Entry", "logistiek",
            ["koude orderpicker", "vrieshuis medewerker"],
            ["orderpick", "koel", "vries", "magazijn"]),
        E("reachtruckchauffeur", "Reachtruckchauffeur", "Entry", "logistiek",
            ["reachtruck operator"],
            ["reachtruck", "heftruck", "magazijn", "logistiek"]),
        E("douane-declarant", "Douane-declarant", "Mbo4", "logistiek",
            ["customs declarant", "invoeradviseur"],
            ["douane", "import", "export", "documenten"]),
        E("forwarder", "Expediteur", "Mbo4", "logistiek",
            ["freight forwarder", "expediteur internationaal"],
            ["expeditie", "internationaal", "vracht", "logistiek"]),
        E("havenarbeider", "Havenarbeider", "Entry", "logistiek",
            ["stevedore", "terminal medewerker"],
            ["haven", "container", "terminal", "laden"]),
        E("kraanmachinist-haven", "Havenkraanmachinist", "Mbo3", "logistiek",
            ["containerkraanmachinist"],
            ["kraan", "haven", "container", "hijsen"]),
        E("scheepvaartmedewerker", "Scheepvaartmedewerker", "Mbo3", "transport",
            ["matroos binnenvaart", "binnenvaartschipper assistent"],
            ["schip", "binnenvaart", "varen", "transport"]),
        E("schipper", "Schipper", "Mbo4", "transport",
            ["binnenvaartschipper", "kapitein binnenvaart"],
            ["schipper", "binnenvaart", "varen", "leiding"]),
        E("visagie-docent", "Visagiedocent", "Hbo", "onderwijs",
            ["makeup docent"],
            ["visagie", "les", "beauty", "onderwijs"]),
        E("zorgcoördinator", "Zorgcoördinator", "Hbo", "zorg",
            ["zorgregisseur", "casemanager zorg"],
            ["zorg", "coordinatie", "casemanagement", "keten"]),
        E("praktijkopleider", "Praktijkopleider", "Mbo4", "onderwijs",
            ["werkplekopleider", "BPV-begeleider"],
            ["praktijk", "opleiding", "begeleiding", "leerling"]),
        E("stagebegeleider", "Stagebegeleider", "Hbo", "onderwijs",
            ["stagecoördinator"],
            ["stage", "begeleiding", "onderwijs", "student"]),
        E("thuiszorgmedewerker", "Thuiszorgmedewerker", "Mbo2", "zorg",
            ["wijkzorg medewerker", "thuisbegeleider"],
            ["thuiszorg", "wijk", "zorg", "client"]),
        E("huishoudelijke-hulp", "Huishoudelijke hulp", "Entry", "zorg",
            ["alpha hulp", "huishoudelijke zorg"],
            ["huishouden", "hulp", "thuiszorg", "schoonmaak"]),
        E("gastouder", "Gastouder", "Mbo2", "onderwijs",
            ["kinderopvang thuis", "gastouderopvang"],
            ["gastouder", "kinderen", "opvang", "thuis"]),
        E("naschoolse-opvang", "Medewerker buitenschoolse opvang", "Mbo3", "onderwijs",
            ["BSO-medewerker", "naschoolse opvang"],
            ["bso", "opvang", "kinderen", "naschools"]),
        E("leerlingbegeleider", "Leerlingbegeleider", "Hbo", "onderwijs",
            ["decaan", "mentor specialist"],
            ["leerling", "begeleiding", "school", "advies"]),
        E("studieadviseur", "Studieadviseur", "Hbo", "onderwijs",
            ["studiecoach", "student counselor"],
            ["studie", "advies", "student", "coach"]),
        E("hr-medewerker", "HR-medewerker", "Mbo4", "hr",
            ["personeelsmedewerker", "HR assistant"],
            ["hr", "personeel", "administratie", "werving"]),
        E("office-manager", "Office manager", "Mbo4", "administratie",
            ["kantoormanager", "bedrijfsbureau manager"],
            ["office", "kantoor", "organisatie", "leiding"]),
        E("notulist", "Notulist", "Mbo3", "administratie",
            ["vergaderverslaglegger"],
            ["notulen", "vergadering", "verslag", "administratie"]),
        E("postkamer-medewerker", "Postkamermedewerker", "Entry", "administratie",
            ["postverwerker", "mailroom"],
            ["post", "mail", "distributie", "kantoor"]),
        E("archiefmedewerker", "Archiefmedewerker", "Mbo2", "administratie",
            ["documentbeheerder", "dossierbeheerder"],
            ["archief", "dossier", "document", "beheer"]),
        E("telefonist", "Telefonist", "Entry", "klantenservice",
            ["centrale telefonist", "switchboard"],
            ["telefoon", "centrale", "doorverbinden", "balie"]),
        E("klachtenbehandelaar", "Klachtenbehandelaar", "Mbo3", "klantenservice",
            ["klachtenmedewerker", "complaints officer"],
            ["klacht", "service", "oplossing", "klant"]),
        E("incassomedewerker", "Incassomedewerker", "Mbo3", "administratie",
            ["debiteurenbewaker", "incasso specialist"],
            ["incasso", "vordering", "betaling", "debiteur"]),
        E("verzekeringsadviseur", "Verzekeringsadviseur", "Mbo4", "financieel",
            ["assurantieadviseur", "polisadviseur"],
            ["verzekering", "advies", "polis", "schade"]),
        E("hypotheekadviseur", "Hypotheekadviseur", "Hbo", "financieel",
            ["hypotheekconsultant", "woningfinanciering"],
            ["hypotheek", "woning", "financiering", "advies"]),
        E("bankmedewerker", "Bankmedewerker", "Mbo4", "financieel",
            ["balie bank", "particulier bankadviseur"],
            ["bank", "klant", "financieel", "advies"]),
        E("vermogensadviseur", "Vermogensadviseur", "Hbo", "financieel",
            ["private banker", "beleggingsadviseur"],
            ["vermogen", "belegging", "advies", "financieel"]),
        E("fiscalist", "Fiscalist", "Wo", "financieel",
            ["belastingadviseur", "tax advisor"],
            ["fiscaal", "belasting", "advies", "wet"]),
        E("notarisklerk", "Notarisklerk", "Mbo4", "juridisch",
            ["notarisassistent", "kandidaat-notarisklerk"],
            ["notaris", "akte", "dossier", "juridisch"]),
        E("gerechtsdeurwaarder", "Gerechtsdeurwaarder", "Hbo", "juridisch",
            ["deurwaarder"],
            ["deurwaarder", "exploot", "incasso", "recht"]),
        E("mediator", "Mediator", "Hbo", "juridisch",
            ["conflictbemiddelaar", "familymediator"],
            ["mediatie", "bemiddeling", "conflict", "gesprek"]),
        E("veiligheidskundige", "Veiligheidskundige", "Hbo", "veiligheid",
            ["HVK", "arbeidsveiligheidsadviseur"],
            ["veiligheid", "arbeid", "risico", "advies"]),
        E("arbo-adviseur", "Arbo-adviseur", "Hbo", "veiligheid",
            ["arbeidsomstandigheden adviseur", "preventiemedewerker senior"],
            ["arbo", "gezondheid", "veiligheid", "werk"]),
        E("preventiemedewerker", "Preventiemedewerker", "Mbo3", "veiligheid",
            ["RI&E medewerker", "bedrijfshulpverlener coördinator"],
            ["preventie", "arbo", "risico", "veiligheid"]),
        E("bhv-er", "Bedrijfshulpverlener", "Entry", "veiligheid",
            ["BHV", "ehbo bedrijf"],
            ["bhv", "ehbo", "evacuatie", "veiligheid"]),
        E("milieucoördinator", "Milieucoördinator", "Hbo", "milieu",
            ["milieubeheerder", "environmental coordinator"],
            ["milieu", "coordinatie", "vergunning", "duurzaam"]),
        E("afvalcoördinator", "Afvalcoördinator", "Mbo4", "milieu",
            ["waste coordinator", "afvalbeheerder"],
            ["afval", "recycling", "coordinatie", "milieu"]),
        E("energiecoach", "Energiecoach", "Mbo4", "milieu",
            ["energieadviseur woning", "isolaatiecoach"],
            ["energie", "besparing", "woning", "advies"]),
        E("installatieverantwoordelijke", "Installatieverantwoordelijke", "Hbo", "techniek",
            ["IV-er", "elektrische installatie verantwoordelijke"],
            ["installatie", "verantwoordelijk", "elektro", "veiligheid"]),
        E("werkplaatschef", "Werkplaatschef", "Mbo4", "automotive",
            ["garagechef", "service advisor hoofd"],
            ["werkplaats", "garage", "leiding", "auto"]),
        E("apkinspecteur", "APK-keurmeester", "Mbo3", "automotive",
            ["apk keurder", "keurmeester auto"],
            ["apk", "keuring", "auto", "veiligheid"]),
        E("bandenmontage", "Bandenmonteur", "Entry", "automotive",
            ["bandenvulser", "tyre fitter"],
            ["band", "montage", "auto", "garage"]),
        E("wasploegleider", "Wasploegleider", "Mbo2", "automotive",
            ["carwash teamleider"],
            ["wasstraat", "leiding", "team", "reiniging"]),
        E("landbouwmedewerker", "Landbouwmedewerker", "Entry", "groen",
            ["agrarisch medewerker", "boerderijhulp"],
            ["landbouw", "boerderij", "oogst", "agrarisch"]),
        E("trekkerchauffeur", "Trekkerchauffeur", "Entry", "groen",
            ["tractorist", "landbouwmachinist"],
            ["trekker", "tractor", "landbouw", "machinist"]),
        E("melkveehouder", "Melkveehouder", "Mbo4", "groen",
            ["veehouder melk", "boer melkvee"],
            ["melkvee", "boerderij", "koe", "agrarisch"]),
        E("akkerbouwer", "Akkerbouwer", "Mbo4", "groen",
            ["akkerbouw ondernemer", "graanboer"],
            ["akkerbouw", "gewas", "oogst", "agrarisch"]),
        E("visser", "Visser", "Mbo2", "voeding",
            ["vissersmaat", "kottermatroos"],
            ["vis", "visserij", "schip", "zee"]),
        E("visverwerker", "Visverwerker", "Entry", "voeding",
            ["visfileerder", "visfabriek medewerker"],
            ["vis", "verwerking", "filet", "productie"]),
        E("vleesverwerker", "Vleesverwerker", "Entry", "voeding",
            ["slachterij medewerker", "vleesbewerker fabriek"],
            ["vlees", "verwerking", "slachterij", "productie"]),
        E("kwaliteitsmedewerker-voeding", "Kwaliteitsmedewerker voeding", "Mbo3", "voeding",
            ["food quality medewerker", "HACCP medewerker"],
            ["kwaliteit", "voeding", "haccp", "controle"]),
        E("voedingsmiddelentechnoloog", "Voedingsmiddelentechnoloog", "Hbo", "voeding",
            ["food technologist", "productontwikkelaar voeding"],
            ["voeding", "technologie", "product", "ontwikkeling"]),
        E("inkoper-vers", "Inkoper vers", "Mbo4", "voeding",
            ["vers inkoper", "produce buyer"],
            ["inkoop", "vers", "groente", "fruit"]),
        E("cateringmanager", "Cateringmanager", "Mbo4", "horeca",
            ["hoofd catering", "contractcatering manager"],
            ["catering", "manager", "horeca", "leiding"]),
        E("restaurantchef", "Restaurantchef", "Mbo4", "horeca",
            ["chef-kok", "keuken chef"],
            ["chef", "keuken", "restaurant", "leiding"]),
        E("patissier", "Pâtissier", "Mbo4", "horeca",
            ["dessertchef", "banketchef"],
            ["patisserie", "dessert", "gebak", "keuken"]),
        E("sommelier-junior", "Junior sommelier", "Mbo3", "horeca",
            ["wijnmedewerker"],
            ["wijn", "service", "horeca", "advies"]),
        E("zaalmanager", "Zaalmanager", "Mbo4", "horeca",
            ["floormanager", "restaurant zaalleider"],
            ["zaal", "bediening", "horeca", "leiding"]),
        E("banqueting-medewerker", "Banquetingmedewerker", "Entry", "horeca",
            ["feestbediening", "banket bediening"],
            ["banqueting", "feest", "bediening", "horeca"]),
        E("congresmedewerker", "Congresmedewerker", "Mbo3", "events",
            ["meeting planner assistent", "zaalsteward"],
            ["congres", "meeting", "event", "facilitatie"]),
        E("podiumtechnicus", "Podiumtechnicus", "Mbo3", "events",
            ["lichttechnicus", "geluidstechnicus"],
            ["podium", "licht", "geluid", "techniek"]),
        E("decorbouwer", "Decorbouwer", "Mbo3", "creatief",
            ["setbouwer", "toneelbouwer"],
            ["decor", "bouw", "toneel", "hout"]),
        E("kostuummaker", "Kostuummaker", "Mbo3", "creatief",
            ["kleermaker theater", "costumier"],
            ["kostuum", "naaien", "theater", "stof"]),
        E("kleermaker", "Kleermaker", "Mbo3", "creatief",
            ["maatkleding maker", "tailor"],
            ["kleermaker", "naaien", "maatwerk", "kleding"]),
        E("modeontwerper", "Modeontwerper", "Hbo", "creatief",
            ["fashion designer", "kledingontwerper"],
            ["mode", "ontwerp", "collectie", "kleding"]),
        E("interieurstylist", "Interieurstylist", "Mbo4", "creatief",
            ["interieuradviseur", "woningstylist"],
            ["interieur", "styling", "woning", "advies"]),
        E("tuinontwerper", "Tuinontwerper", "Hbo", "groen",
            ["garden designer", "landschapsontwerper junior"],
            ["tuin", "ontwerp", "groen", "landschap"]),
        E("landschapsarchitect", "Landschapsarchitect", "Wo", "groen",
            ["landschapsontwerper"],
            ["landschap", "architectuur", "groen", "ontwerp"]),
        E("stedenbouwkundige", "Stedenbouwkundige", "Wo", "bouw",
            ["urban planner", "planoloog"],
            ["stedenbouw", "planning", "ruimte", "beleid"]),
        E("planoloog", "Planoloog", "Hbo", "overheid",
            ["ruimtelijke ordening adviseur"],
            ["planologie", "ruimte", "beleid", "ordening"]),
        E("verkeerskundige", "Verkeerskundige", "Hbo", "overheid",
            ["mobiliteitsadviseur", "verkeersadviseur"],
            ["verkeer", "mobiliteit", "wegen", "advies"]),
        E("waterbeheerder", "Waterbeheerder", "Hbo", "milieu",
            ["waterschapsmedewerker", "hydroloog junior"],
            ["water", "beheer", "dijken", "milieu"]),
        E("boswachter", "Boswachter", "Mbo4", "groen",
            ["natuurbeheerder", "ranger"],
            ["bos", "natuur", "beheer", "toezicht"]),
        E("natuurbeheerder", "Natuurbeheerder", "Hbo", "groen",
            ["ecologisch beheerder", "terreineigenaar beheer"],
            ["natuur", "beheer", "ecologie", "gebied"]),
        E("ecoloog", "Ecoloog", "Wo", "onderzoek",
            ["veldbioloog", "milieubioloog"],
            ["ecologie", "natuur", "onderzoek", "soorten"]),
        E("bioloog", "Bioloog", "Wo", "onderzoek",
            ["onderzoeksbioloog"],
            ["biologie", "onderzoek", "lab", "veld"]),
        E("scheikundige", "Scheikundige", "Wo", "onderzoek",
            ["chemicus", "onderzoeker chemie"],
            ["chemie", "onderzoek", "lab", "stof"]),
        E("natuurkundige", "Natuurkundige", "Wo", "onderzoek",
            ["fysicus", "onderzoeker fysica"],
            ["natuurkunde", "onderzoek", "fysica", "analyse"]),
        E("wiskundige", "Wiskundige", "Wo", "onderzoek",
            ["mathematicus", "kwantitatief onderzoeker"],
            ["wiskunde", "model", "analyse", "onderzoek"]),
        E("historicus", "Historicus", "Wo", "onderzoek",
            ["geschiedkundige", "erfgoedonderzoeker"],
            ["geschiedenis", "onderzoek", "archief", "erfgoed"]),
        E("antropoloog", "Antropoloog", "Wo", "onderzoek",
            ["cultureel antropoloog"],
            ["antropologie", "cultuur", "onderzoek", "veld"]),
        E("socioloog", "Socioloog", "Wo", "onderzoek",
            ["maatschappijonderzoeker"],
            ["sociologie", "onderzoek", "maatschappij", "data"]),
        E("politicoloog", "Politicoloog", "Wo", "onderzoek",
            ["politiek analist"],
            ["politiek", "onderzoek", "beleid", "analyse"]),
        E("filosoof", "Filosoof", "Wo", "onderzoek",
            ["wijsgerig onderzoeker"],
            ["filosofie", "ethiek", "denken", "onderzoek"]),
        E("theoloog", "Theoloog", "Wo", "zorg",
            ["geestelijk verzorger", "pastor"],
            ["theologie", "geestelijk", "zorg", "zingeving"]),
        E("imam", "Imam", "Hbo", "zorg",
            ["geestelijk begeleider islam"],
            ["imam", "geestelijk", "begeleiding", "gemeenschap"]),
        E("voorganger", "Voorganger", "Hbo", "zorg",
            ["predikant", "pastor kerk"],
            ["voorganger", "kerk", "geestelijk", "gemeenschap"]),
    ];
}
