using System.Globalization;
using System.Text;
using Jobsy.Core.Localization;
using Jobsy.Core.Rules;

namespace Jobsy.Core.Careers;

/// <summary>
/// Plain-language breakdown of one job-fit percent. Built from <see cref="CareerCompassBuilder.MatchMath"/>,
/// the same path as the number on screen. Never generated by a model.
/// </summary>
public sealed class FitPercentExplanation
{
    public const string SourceName = "O*NET 31.0";
    public const string EscoVersion = "ESCO v1.2.1";

    private FitPercentExplanation(
        string title,
        decimal percent,
        decimal weightSum,
        decimal productSum,
        IReadOnlyList<ProfileMatchTerm> terms,
        string escoId,
        IReadOnlyList<string> onetCodes,
        string confidence,
        string education,
        bool hasEducationGate,
        bool extraTraining,
        bool aboveLevel,
        bool officeSwap)
    {
        Title = title;
        Percent = percent;
        WeightSum = weightSum;
        ProductSum = productSum;
        Terms = terms;
        EscoId = escoId;
        OnetCodes = onetCodes;
        Confidence = confidence;
        Education = education;
        HasEducationGate = hasEducationGate;
        ExtraTraining = extraTraining;
        AboveLevel = aboveLevel;
        OfficeSwap = officeSwap;
    }

    public string Title { get; }
    public decimal Percent { get; }
    public decimal WeightSum { get; }
    public decimal ProductSum { get; }
    public IReadOnlyList<ProfileMatchTerm> Terms { get; }
    public string EscoId { get; }
    public IReadOnlyList<string> OnetCodes { get; }
    public string Confidence { get; }
    public string Education { get; }
    public bool HasEducationGate { get; }
    public bool ExtraTraining { get; }
    public bool AboveLevel { get; }
    public bool OfficeSwap { get; }

    public string Equation
        => WeightSum <= 0m
            ? CareerCompassBuilder.FormatPercent(Percent)
            : $"{Num(ProductSum)} / {Num(WeightSum)} = {CareerCompassBuilder.FormatPercent(Percent)}";

    /// <summary>
    /// Explanation for a catalogue title that has a shown percent. Null when that title has no percent.
    /// <paramref name="education"/> does not change the number. It only fills the filter paragraph.
    /// </summary>
    public static FitPercentExplanation? Build(string title, RiasecScores scores, string? education = null)
    {
        var occupation = OccupationCatalog.Shared.Resolve(title);
        if (occupation is not { IsListable: true, Oi: { Count: 6 } oi })
        {
            return null;
        }

        var math = CareerCompassBuilder.MatchMath(oi, scores);
        var gate = CareerEducationGate.MaxIscoLevel(education);
        var shownEducation = (education ?? "").Trim();
        var hasGate = gate.HasGate && shownEducation.Length > 0;
        var extra = hasGate && CareerEducationGate.NeedsExtraTraining(occupation.IscoLevel, gate);
        var above = hasGate && !CareerEducationGate.Passes(occupation.IscoLevel, gate);
        var swap = hasGate
                   && gate.SubstituteLowerOffice
                   && OccupationCatalog.Shared.LevelSwaps.Any(item =>
                       string.Equals(item.FromId, occupation.Id, StringComparison.OrdinalIgnoreCase));

        return new FitPercentExplanation(
            occupation.Nl,
            math.Percent,
            math.WeightSum,
            math.ProductSum,
            math.Terms,
            occupation.Id,
            occupation.Onet,
            occupation.Confidence,
            shownEducation,
            hasGate,
            extra,
            above,
            swap);
    }

    public static RiasecScores? TryScores(string? fingerprint)
    {
        if (string.IsNullOrWhiteSpace(fingerprint))
        {
            return null;
        }

        var parts = fingerprint.Split('|');
        if (parts.Length != 6)
        {
            return null;
        }

        var values = new int?[6];
        for (var i = 0; i < 6; i++)
        {
            if (!int.TryParse(parts[i], NumberStyles.Integer, CultureInfo.InvariantCulture, out var value))
            {
                return null;
            }

            values[i] = value;
        }

        return TryScores(values[0], values[1], values[2], values[3], values[4], values[5]);
    }

    public static RiasecScores? TryScores(int? realistic, int? investigative, int? artistic, int? social, int? enterprising, int? conventional)
    {
        var scores = new RiasecScores(realistic, investigative, artistic, social, enterprising, conventional);
        return scores.IsComplete ? scores : null;
    }

    public static string ButtonLabel(string? lang, string title)
    {
        var name = title.Trim();
        return JobsyLanguages.Normalize(lang) switch
        {
            "en" => $"How the percentage for {name} was calculated",
            "pl" => $"Jak obliczono procent dla {name}",
            "ro" => $"Cum a fost calculat procentul pentru {name}",
            "ar" => $"كيف حُسبَت النسبة لـ {name}",
            _ => $"Uitleg van het percentage voor {name}"
        };
    }

    public static string CloseLabel(string? lang) => JobsyLanguages.Normalize(lang) switch
    {
        "en" => "Close",
        "pl" => "Zamknij",
        "ro" => "Închide",
        "ar" => "إغلاق",
        _ => "Sluiten"
    };

    public static string PanelTitle(string? lang) => JobsyLanguages.Normalize(lang) switch
    {
        "en" => "How this percentage was calculated",
        "pl" => "Jak obliczono ten procent",
        "ro" => "Cum a fost calculat acest procent",
        "ar" => "كيف حُسبَت هذه النسبة",
        _ => "Hoe dit percentage is berekend"
    };

    public static string Render(FitPercentExplanation explain, string? lang)
        => string.Join("\n", Lines(explain, lang));

    public static IReadOnlyList<string> Lines(FitPercentExplanation explain, string? lang)
    {
        var code = JobsyLanguages.Normalize(lang);
        var lines = new List<string>
        {
            Intro(code, explain.Title),
            ScoresHeading(code)
        };
        foreach (var term in explain.Terms.Where(term => term.Weight > 0m))
        {
            lines.Add(ScoreLine(code, term));
        }

        lines.Add(ProfileHeading(code));
        foreach (var term in explain.Terms)
        {
            lines.Add(ProfileLine(code, term));
        }

        lines.Add(SourceLine(code, explain));
        lines.Add(ConfidenceLine(code, explain.Confidence));
        lines.Add(Formula(code));
        lines.Add(FilledHeading(code));
        foreach (var term in explain.Terms.Where(term => term.Weight > 0m))
        {
            lines.Add($"{Num(term.Weight, code)} × {term.Score} = {Num(term.Product, code)}");
        }

        lines.Add(EquationFor(explain, code));
        if (explain.HasEducationGate)
        {
            lines.Add(EducationLine(code, explain.Education));
            if (explain.ExtraTraining)
            {
                lines.Add(ExtraLine(code));
            }

            if (explain.AboveLevel)
            {
                lines.Add(AboveLine(code));
            }

            if (explain.OfficeSwap)
            {
                lines.Add(SwapLine(code));
            }
        }

        return lines;
    }

    /// <summary>Short PDF note. Same numbers as <see cref="Render"/>, without the full worked lines.</summary>
    public static string Footnote(IReadOnlyList<FitPercentExplanation> items, string? lang)
    {
        if (items.Count == 0)
        {
            return FormulaOnly(lang);
        }

        var code = JobsyLanguages.Normalize(lang);
        var sb = new StringBuilder();
        sb.Append(FormulaOnly(code));
        if (items.Any(item => item.HasEducationGate))
        {
            sb.Append(' ');
            sb.Append(EducationUnchanged(code));
        }

        foreach (var item in items)
        {
            sb.AppendLine();
            sb.Append(JobLine(code, item));
        }

        return sb.ToString().Trim();
    }

    /// <summary>Formula in words when the PDF has percents but no stored scores to fill in.</summary>
    public static string FormulaOnly(string? lang) => JobsyLanguages.Normalize(lang) switch
    {
        "en" => "The percentage is a weighted average of your scores. A direction counts more when this job asks for it more. Source: O*NET 31.0. Subtract 1 from the O*NET number. That is the weight. Add weight times your score, divide by the sum of the weights, and round to 2 decimals.",
        "pl" => "Procent to średnia ważona twoich wyników. Kierunek liczy się bardziej, gdy zawód bardziej go wymaga. Źródło: O*NET 31.0. Odejmij 1 od liczby O*NET. To jest waga. Suma waga × twój wynik, podzielona przez sumę wag, zaokrąglona do 2 miejsc.",
        "ro" => "Procentul este o medie ponderată a scorurilor tale. O direcție contează mai mult când meseria o cere mai mult. Sursă: O*NET 31.0. Scazi 1 din numărul O*NET. Asta este ponderea. Suma pondere × scorul tău, împărțită la suma ponderilor, rotunjită la 2 zecimale.",
        "ar" => "النسبة هي متوسط مرجّح لدرجاتك. الاتجاه الذي تطلبه المهنة أكثر له وزن أكبر. المصدر: O*NET 31.0. نطرح 1 من رقم O*NET. هذا هو الوزن. مجموع الوزن × درجتك، مقسوماً على مجموع الأوزان، مع التقريب إلى منزلتين.",
        _ => "Het percentage is een gewogen gemiddelde van jouw scores. Een richting telt zwaarder als dit beroep die meer vraagt. Bron: O*NET 31.0. We trekken 1 af van het O*NET-getal. Dat is het gewicht. Som van gewicht × jouw score, gedeeld door de som van de gewichten, afgerond op 2 decimalen."
    };

    public static string Num(decimal value)
        => value.ToString("0.##", CultureInfo.InvariantCulture);

    public static string Num(decimal value, string? lang)
    {
        var code = JobsyLanguages.Normalize(lang);
        return code is "nl" or "pl" or "ro"
            ? value.ToString("0.##", CultureInfo.GetCultureInfo("nl-NL"))
            : Num(value);
    }

    private static string EquationFor(FitPercentExplanation explain, string? lang)
        => explain.WeightSum <= 0m
            ? CareerCompassBuilder.FormatPercent(explain.Percent, lang)
            : $"{Num(explain.ProductSum, lang)} / {Num(explain.WeightSum, lang)} = {CareerCompassBuilder.FormatPercent(explain.Percent, lang)}";

    private static string Intro(string lang, string title) => lang switch
    {
        "en" => $"This percentage is for you and for {title}. It uses the same calculation as the number next to the job.",
        "pl" => $"Ten procent jest dla ciebie i dla {title}. Liczymy go tak samo jak liczbę obok zawodu.",
        "ro" => $"Acest procent este pentru tine și pentru {title}. Este aceeași socoteală ca numărul de lângă meserie.",
        "ar" => $"هذه النسبة لك ولهذا العمل: {title}. هي نفس الحساب الذي يعطي الرقم بجانب المهنة.",
        _ => $"Dit percentage is voor jou en voor {title}. Het komt uit dezelfde berekening als het getal naast het beroep."
    };

    private static string ScoresHeading(string lang) => lang switch
    {
        "en" => "Your scores that count:",
        "pl" => "Twoje wyniki, które liczą się:",
        "ro" => "Scorurile tale care contează:",
        "ar" => "درجاتك التي تُحسب:",
        _ => "Jouw scores die meetellen:"
    };

    private static string ScoreLine(string lang, ProfileMatchTerm term)
        => $"{Label(term.Code, lang)} ({Letter(term.Code)}): {term.Score}";

    private static string ProfileHeading(string lang) => lang switch
    {
        "en" => "What this job asks for, from O*NET 31.0:",
        "pl" => "Czego wymaga ten zawód, według O*NET 31.0:",
        "ro" => "Ce cere această meserie, din O*NET 31.0:",
        "ar" => "ما تطلبه هذه المهنة، من O*NET 31.0:",
        _ => "Wat dit beroep vraagt, uit O*NET 31.0:"
    };

    private static string ProfileLine(string lang, ProfileMatchTerm term)
    {
        var name = $"{Label(term.Code, lang)} ({Letter(term.Code)}): {Num(term.Oi)}";
        if (term.Weight <= 0m)
        {
            return lang switch
            {
                "en" => $"{name}. Weight 0, left out.",
                "pl" => $"{name}. Waga 0, nie liczy się.",
                "ro" => $"{name}. Pondere 0, nu intră în calcul.",
                "ar" => $"{name}. الوزن 0، لا يُحسب.",
                _ => $"{name}. Gewicht 0, telt niet mee."
            };
        }

        return lang switch
        {
            "en" => $"{name}. Weight {Num(term.Weight)}.",
            "pl" => $"{name}. Waga {Num(term.Weight)}.",
            "ro" => $"{name}. Pondere {Num(term.Weight)}.",
            "ar" => $"{name}. الوزن {Num(term.Weight)}.",
            _ => $"{name}. Gewicht {Num(term.Weight)}."
        };
    }

    private static string SourceLine(string lang, FitPercentExplanation explain)
    {
        var codes = explain.OnetCodes.Count == 0
            ? ""
            : string.Join(", ", explain.OnetCodes);
        return lang switch
        {
            "en" => codes.Length == 0
                ? $"Source: O*NET 31.0. ESCO v1.2.1, code {explain.EscoId}."
                : $"Source: O*NET 31.0. ESCO v1.2.1, code {explain.EscoId}. O*NET code: {codes}.",
            "pl" => codes.Length == 0
                ? $"Źródło: O*NET 31.0. ESCO v1.2.1, kod {explain.EscoId}."
                : $"Źródło: O*NET 31.0. ESCO v1.2.1, kod {explain.EscoId}. Kod O*NET: {codes}.",
            "ro" => codes.Length == 0
                ? $"Sursă: O*NET 31.0. ESCO v1.2.1, cod {explain.EscoId}."
                : $"Sursă: O*NET 31.0. ESCO v1.2.1, cod {explain.EscoId}. Cod O*NET: {codes}.",
            "ar" => codes.Length == 0
                ? $"المصدر: O*NET 31.0. ESCO v1.2.1، الرمز {explain.EscoId}."
                : $"المصدر: O*NET 31.0. ESCO v1.2.1، الرمز {explain.EscoId}. رمز O*NET: {codes}.",
            _ => codes.Length == 0
                ? $"Bron: O*NET 31.0. ESCO v1.2.1, code {explain.EscoId}."
                : $"Bron: O*NET 31.0. ESCO v1.2.1, code {explain.EscoId}. O*NET-code: {codes}."
        };
    }

    private static string ConfidenceLine(string lang, string confidence) => (lang, confidence) switch
    {
        ("en", "high") => "The link between ESCO and O*NET is high: a precise link.",
        ("en", _) => "The link between ESCO and O*NET is medium: usable, but not the exact same job.",
        ("pl", "high") => "Powiązanie ESCO z O*NET jest wysokie: to dokładne powiązanie.",
        ("pl", _) => "Powiązanie ESCO z O*NET jest średnie: użyteczne, ale nie dokładnie ten sam zawód.",
        ("ro", "high") => "Legătura dintre ESCO și O*NET este mare: o legătură precisă.",
        ("ro", _) => "Legătura dintre ESCO și O*NET este medie: utilă, dar nu exact aceeași meserie.",
        ("ar", "high") => "الربط بين ESCO و O*NET عالٍ: ربط دقيق.",
        ("ar", _) => "الربط بين ESCO و O*NET متوسط: مفيد، لكنه ليس المهنة نفسها بالضبط.",
        (_, "high") => "De koppeling tussen ESCO en O*NET is hoog: een precieze koppeling.",
        _ => "De koppeling tussen ESCO en O*NET is gemiddeld: bruikbaar, maar niet precies hetzelfde beroep."
    };

    private static string Formula(string lang) => lang switch
    {
        "en" => "In words: subtract 1 from each O*NET number. That is the weight. A direction with weight 0 does not count. Then add weight times your score, and divide by the sum of the weights. Round to 2 decimals.",
        "pl" => "Słowami: odejmij 1 od każdej liczby O*NET. To jest waga. Kierunek z wagą 0 nie liczy się. Potem dodaj waga razy twój wynik i podziel przez sumę wag. Zaokrąglij do 2 miejsc.",
        "ro" => "În cuvinte: scazi 1 din fiecare număr O*NET. Asta este ponderea. O direcție cu pondere 0 nu contează. Apoi aduni pondere ori scorul tău și împărți la suma ponderilor. Rotunjești la 2 zecimale.",
        "ar" => "بالكلمات: نطرح 1 من كل رقم O*NET. هذا هو الوزن. الاتجاه ذو الوزن 0 لا يُحسب. ثم نجمع الوزن × درجتك ونقسم على مجموع الأوزان. نقرّب إلى منزلتين.",
        _ => "In woorden: we trekken 1 af van elk O*NET-getal. Dat is het gewicht. Een richting met gewicht 0 telt niet mee. Daarna tellen we gewicht keer jouw score bij elkaar en delen door de som van de gewichten. We ronden af op 2 decimalen."
    };

    private static string FilledHeading(string lang) => lang switch
    {
        "en" => "Filled in with your numbers:",
        "pl" => "Wypełnione twoimi liczbami:",
        "ro" => "Completat cu numerele tale:",
        "ar" => "معبأ بأرقامك:",
        _ => "Ingevuld met jouw getallen:"
    };

    private static string EducationLine(string lang, string education) => lang switch
    {
        "en" => $"Your education ({education}) decides which jobs we show. The percentage stays the same.",
        "pl" => $"Twoje wykształcenie ({education}) decyduje, które zawody pokazujemy. Procent zostaje taki sam.",
        "ro" => $"Studiile tale ({education}) decid ce meserii arătăm. Procentul rămâne același.",
        "ar" => $"تعليمك ({education}) يحدد المهن التي نعرضها. النسبة تبقى كما هي.",
        _ => $"Je opleiding ({education}) bepaalt welke beroepen we tonen. Het percentage blijft hetzelfde."
    };

    private static string EducationUnchanged(string lang) => lang switch
    {
        "en" => "Education does not change the number.",
        "pl" => "Wykształcenie nie zmienia liczby.",
        "ro" => "Studiile nu schimbă numărul.",
        "ar" => "التعليم لا يغيّر الرقم.",
        _ => "De opleiding verandert het getal niet."
    };

    private static string ExtraLine(string lang) => lang switch
    {
        "en" => "This job may need extra training. That note does not change the percentage.",
        "pl" => "Ten zawód może wymagać dodatkowej nauki. Ta uwaga nie zmienia procentu.",
        "ro" => "Această meserie poate cere școlarizare în plus. Nota nu schimbă procentul.",
        "ar" => "قد تحتاج هذه المهنة إلى تدريب إضافي. هذه الملاحظة لا تغيّر النسبة.",
        _ => "Dit beroep kan extra scholing vragen. Die notitie verandert het percentage niet."
    };

    private static string AboveLine(string lang) => lang switch
    {
        "en" => "This job is above your education level. It is not on the main list. The percentage is the same.",
        "pl" => "Ten zawód jest powyżej twojego poziomu wykształcenia. Nie ma go na głównej liście. Procent jest taki sam.",
        "ro" => "Această meserie este peste nivelul studiilor tale. Nu este pe lista principală. Procentul este același.",
        "ar" => "هذه المهنة أعلى من مستوى تعليمك. ليست في القائمة الرئيسية. النسبة هي نفسها.",
        _ => "Dit beroep ligt boven jouw opleidingsniveau. Het staat niet in de hoofdllijst. Het percentage is hetzelfde."
    };

    private static string SwapLine(string lang) => lang switch
    {
        "en" => "For your level we put a simpler office job first. This job stays findable. The percentage does not change.",
        "pl" => "Dla twojego poziomu najpierw pokazujemy prostszą pracę biurową. Ten zawód zostaje do znalezienia. Procent się nie zmienia.",
        "ro" => "Pentru nivelul tău punem întâi o meserie de birou mai simplă. Această meserie rămâne de găsit. Procentul nu se schimbă.",
        "ar" => "لمستواك نضع أولاً عملاً مكتبياً أبسط. هذه المهنة تبقى قابلة للبحث. النسبة لا تتغير.",
        _ => "Voor jouw niveau zetten we eerst een eenvoudiger kantoorberoep. Dit beroep blijft vindbaar. Het percentage verandert niet."
    };

    private static string JobLine(string lang, FitPercentExplanation item)
    {
        var codes = item.OnetCodes.Count == 0 ? "" : string.Join(", ", item.OnetCodes);
        var link = item.Confidence == "high"
            ? lang switch
            {
                "en" => "link high",
                "pl" => "powiązanie wysokie",
                "ro" => "legătură mare",
                "ar" => "ربط عالٍ",
                _ => "koppeling hoog"
            }
            : lang switch
            {
                "en" => "link medium",
                "pl" => "powiązanie średnie",
                "ro" => "legătură medie",
                "ar" => "ربط متوسط",
                _ => "koppeling gemiddeld"
            };
        var codePart = codes.Length == 0
            ? $"ESCO {item.EscoId}"
            : $"ESCO {item.EscoId}. O*NET {codes}";
        var extra = item.ExtraTraining || item.AboveLevel || item.OfficeSwap
            ? " " + EducationUnchanged(lang)
            : "";
        return $"{item.Title}: {item.Equation}. {codePart}. {link}.{extra}";
    }

    private static string Label(string code, string lang) => DimensionLabels.For(code, lang);

    private static string Letter(string code)
        => CareerTestCatalog.HollandLetter.TryGetValue(code, out var letter)
            ? letter.ToString()
            : code;
}
