using Jobsy.Core.Localization;

namespace Jobsy.Core.Passport;

/// <summary>
/// PDF copy for nl, en, pl, ro and ar. One row is one key, so a language cannot be forgotten.
/// Index: 0 nl, 1 en, 2 pl, 3 ro, 4 ar.
/// </summary>
public static class PassportPdfStrings
{
    public static IReadOnlyCollection<string> Keys => Map.Keys;

    public static string T(string? language, string key)
    {
        if (!Map.TryGetValue(key, out var row))
        {
            return key;
        }

        return row[Index(language)];
    }

    public static string F(string? language, string key, params object[] args)
        => string.Format(System.Globalization.CultureInfo.InvariantCulture, T(language, key), args);

    public static bool HasKey(string key) => Map.ContainsKey(key);

    private static int Index(string? language) => JobsyLanguages.Normalize(language) switch
    {
        "en" => 1,
        "pl" => 2,
        "ro" => 3,
        "ar" => 4,
        _ => 0
    };

    private static readonly Dictionary<string, string[]> Map = new(StringComparer.Ordinal)
    {
        ["Title"] = ["DNA-paspoort", "DNA passport", "Paszport DNA", "Pașaport ADN", "جواز الحمض النووي"],
        ["Page1"] = ["Wie je bent", "Who you are", "Kim jesteś", "Cine ești", "من أنت"],
        ["Page2"] = ["Wat je hebt gedaan", "What you have done", "Co już robiłeś", "Ce ai făcut", "ما قمت به"],
        ["Badge"] = ["Lobsy-compleet", "Lobsy complete", "Lobsy kompletne", "Lobsy complet", "لوبسي مكتمل"],
        ["TestsProgress"] = ["{0}/4 DNA-tests afgerond", "{0}/4 DNA tests done", "{0}/4 testy DNA ukończone", "{0}/4 teste ADN gata", "{0}/4 اختبارات الحمض النووي مكتملة"],
        ["OpenForWork"] = ["Open voor werk", "Open for work", "Otwarty na pracę", "Deschis pentru lucru", "متاح للعمل"],
        ["PassportNo"] = ["Paspoortnr. {0}", "Passport no. {0}", "Nr paszportu {0}", "Nr. pașaport {0}", "رقم الجواز {0}"],
        ["Available"] = ["Beschikbaar per", "Available from", "Dostępny od", "Disponibil din", "متاح من"],
        ["Direct"] = ["Direct", "Right away", "Od razu", "Imediat", "فوراً"],
        ["Hours"] = ["{0} uur per week", "{0} hours a week", "{0} godz. tygodniowo", "{0} ore pe săptămână", "{0} ساعة في الأسبوع"],
        ["Shifts"] = ["Diensten", "Shifts", "Zmiany", "Ture", "الورديات"],
        ["ShiftYes"] = ["Ja", "Yes", "Tak", "Da", "نعم"],
        ["ShiftConsult"] = ["In overleg", "To agree", "Do uzgodnienia", "De discutat", "بالاتفاق"],
        ["ShiftNo"] = ["Nee", "No", "Nie", "Nu", "لا"],
        ["Part.Ochtend"] = ["Ocht.", "Morn.", "Rano", "Dim.", "صباح"],
        ["Part.Middag"] = ["Midd.", "Aft.", "Pop.", "Prânz", "ظهر"],
        ["Part.Avond"] = ["Avond", "Eve", "Wiecz.", "Seară", "مساء"],
        ["Part.Nacht"] = ["Nacht", "Night", "Noc", "Noapte", "ليل"],
        ["No.Ochtend"] = ["geen ochtenden", "no mornings", "bez poranków", "fără dimineți", "بدون صباح"],
        ["No.Middag"] = ["geen middagen", "no afternoons", "bez popołudni", "fără prânz", "بدون ظهر"],
        ["No.Avond"] = ["geen avonden", "no evenings", "bez wieczorów", "fără seri", "بدون مساء"],
        ["No.Nacht"] = ["geen nachten", "no nights", "bez nocy", "fără nopți", "بدون ليل"],
        ["Consult.Ochtend"] = ["ochtend in overleg", "morning to agree", "rano do uzgodnienia", "dimineața de discutat", "الصباح بالاتفاق"],
        ["Consult.Middag"] = ["middag in overleg", "afternoon to agree", "popołudnie do uzgodnienia", "prânzul de discutat", "الظهر بالاتفاق"],
        ["Consult.Avond"] = ["avond in overleg", "evening to agree", "wieczór do uzgodnienia", "seara de discutat", "المساء بالاتفاق"],
        ["Consult.Nacht"] = ["nacht in overleg", "night to agree", "noc do uzgodnienia", "noaptea de discutat", "الليل بالاتفاق"],
        ["TimesConsult"] = ["Tijden in overleg", "Times to agree", "Godziny do uzgodnienia", "Ore de discutat", "الأوقات بالاتفاق"],
        ["Transport"] = ["Vervoer", "Transport", "Dojazd", "Transport", "التنقل"],
        ["Licence"] = ["Rijbewijs {0}", "Licence {0}", "Prawo jazdy {0}", "Permis {0}", "رخصة {0}"],
        ["MaxTravel"] = ["max. {0} min reizen", "max. {0} min travel", "maks. {0} min dojazdu", "max. {0} min deplasare", "حد أقصى {0} دقائق"],
        ["OwnCar"] = ["Eigen auto: {0}", "Own car: {0}", "Własne auto: {0}", "Mașină proprie: {0}", "سيارة خاصة: {0}"],
        ["Yes"] = ["ja", "yes", "tak", "da", "نعم"],
        ["No"] = ["nee", "no", "nie", "nu", "لا"],
        ["Contact"] = ["Contact", "Contact", "Kontakt", "Contact", "اتصال"],
        ["WhatsApp"] = ["WhatsApp mag", "WhatsApp is ok", "WhatsApp można", "WhatsApp e ok", "واتساب مسموح"],
        ["Languages"] = ["Talen", "Languages", "Języki", "Limbi", "اللغات"],
        ["Dutch"] = ["Nederlands", "Dutch", "Niderlandzki", "Neerlandeză", "الهولندية"],
        ["WorkPrefs"] = ["Werkvoorkeuren", "Work preferences", "Preferencje pracy", "Preferințe de lucru", "تفضيلات العمل"],
        ["Strengths"] = ["Sterke punten", "Strengths", "Mocne strony", "Puncte forte", "نقاط القوة"],
        ["StrengthSource"] = ["Zelfinzicht uit een afgeronde test · {0}", "From a completed test · {0}", "Z ukończonego testu · {0}", "Dintr-un test terminat · {0}", "من اختبار مكتمل · {0}"],
        ["Seeks"] = ["Zoekt", "Looking for", "Szuka", "Caută", "يبحث عن"],
        ["Experience"] = ["Ervaring", "Experience", "Doświadczenie", "Experiență", "الخبرة"],
        ["Papers"] = ["Papieren", "Papers", "Dokumenty", "Acte", "الأوراق"],
        ["Certificates"] = ["Certificaten", "Certificates", "Certyfikaty", "Certificate", "الشهادات"],
        ["Education"] = ["Opleiding", "Education", "Wykształcenie", "Educație", "التعليم"],
        ["DnaTitle"] = ["Mijn DNA in 4 lagen", "My DNA in 4 layers", "Moje DNA w 4 warstwach", "ADN-ul meu în 4 straturi", "حمضي النووي في 4 طبقات"],
        ["Layer.competence"] = ["Competenties", "Competencies", "Kompetencje", "Competențe", "الكفاءات"],
        ["Layer.career"] = ["Loopbaan", "Career", "Kariera", "Carieră", "المسار"],
        ["Layer.culture"] = ["Werkcultuur", "Work culture", "Kultura pracy", "Cultura muncii", "ثقافة العمل"],
        ["Layer.values"] = ["Waarden", "Values", "Wartości", "Valori", "القيم"],
        ["NotDone"] = ["Nog niet gedaan", "Not done yet", "Jeszcze nie zrobione", "Încă nefăcut", "لم يُنجز بعد"],
        ["Done"] = ["Afgerond", "Done", "Ukończone", "Gata", "مكتمل"],
        ["HowIWork"] = ["Hoe ik graag werk", "How I like to work", "Jak lubię pracować", "Cum îmi place să lucrez", "كيف أحب أن أعمل"],
        ["OwnWords"] = ["In mijn eigen woorden", "In my own words", "Własnymi słowami", "Cu vorbele mele", "بكلماتي"],
        ["Motivation"] = ["Motivatie", "Motivation", "Motywacja", "Motivație", "الدافع"],
        ["Means"] = ["Wat betekent Lobsy-compleet?", "What does Lobsy complete mean?", "Co znaczy Lobsy kompletne?", "Ce înseamnă Lobsy complet?", "ماذا يعني لوبسي مكتمل؟"],
        ["Checked"] = ["Gecontroleerd door Lobsy", "Checked by Lobsy", "Sprawdzone przez Lobsy", "Verificat de Lobsy", "راجعته لوبسي"],
        ["NotChecked"] = ["Niet gecontroleerd", "Not checked", "Niesprawdzone", "Neverificat", "لم يُراجع"],
        ["EmailOk"] = ["E-mail bevestigd", "Email confirmed", "E-mail potwierdzony", "E-mail confirmat", "تم تأكيد البريد"],
        ["PhoneOk"] = ["Telefoon bevestigd", "Phone confirmed", "Telefon potwierdzony", "Telefon confirmat", "تم تأكيد الهاتف"],
        ["NotIdentity"] = ["Identiteit en werkvergunning", "Identity and work permit", "Tożsamość i pozwolenie na pracę", "Identitate și permis de muncă", "الهوية وتصريح العمل"],
        ["NotDiplomas"] = ["Echtheid van diploma's en certificaten", "Whether diplomas and certificates are genuine", "Autentyczność dyplomów i certyfikatów", "Autenticitatea diplomelor și certificatelor", "صحة الشهادات والوثائق"],
        ["NotReferences"] = ["Referenties van vorige werkgevers", "References from previous employers", "Referencje od poprzednich pracodawców", "Referințe de la foști angajatori", "مراجع من أصحاب العمل السابقين"],
        ["FooterPrivacy"] = ["Bewust niet op dit paspoort: geboortedatum, foto, nationaliteit, BSN, gezondheid.", "Left off on purpose: date of birth, photo, nationality, citizen service number, health.", "Świadomie pominięte: data urodzenia, zdjęcie, narodowość, BSN, zdrowie.", "Lăsate deoparte intenționat: data nașterii, foto, naționalitate, BSN, sănătate.", "تُرك عمداً: تاريخ الميلاد، الصورة، الجنسية، رقم الخدمة، الصحة."],
        ["FooterNoScore"] = ["Alleen feiten die jij zelf invulde. Geen score, geen ranking en geen automatische selectie.", "Only facts you entered yourself. No score, no ranking and no automatic selection.", "Tylko fakty, które sam wpisałeś. Bez wyniku, bez rankingu i bez automatycznego wyboru.", "Doar fapte pe care le-ai scris tu. Fără scor, fără clasament și fără selecție automată.", "فقط حقائق كتبتها أنت. بلا درجة، بلا ترتيب وبلا اختيار تلقائي."],
        ["FooterLive"] = ["Bekijk de live versie in Lobsy.", "See the live version in Lobsy.", "Zobacz wersję na żywo w Lobsy.", "Vezi versiunea live în Lobsy.", "انظر النسخة الحية في لوبسي."],
        ["More"] = ["+{0} meer in Lobsy", "+{0} more in Lobsy", "+{0} więcej w Lobsy", "+{0} mai mult în Lobsy", "+{0} المزيد في لوبسي"],
        ["ExperienceCount"] = ["{0} eerdere werkgevers", "{0} earlier employers", "{0} wcześniejszych pracodawców", "{0} angajatori anteriori", "{0} أصحاب عمل سابقين"],
        ["Indoor"] = ["Binnen", "Indoors", "Wewnątrz", "În interior", "في الداخل"],
        ["Outdoor"] = ["Buiten", "Outdoors", "Na zewnątrz", "Afară", "في الخارج"],
        ["Physical"] = ["Fysiek werk", "Physical work", "Praca fizyczna", "Muncă fizică", "عمل بدني"],
        ["Pace"] = ["Tempo", "Pace", "Tempo", "Ritm", "الوتيرة"],
        ["Environment"] = ["Werkomgeving", "Workplace", "Środowisko pracy", "Mediul de lucru", "بيئة العمل"],
        ["Work.Indoor.prefer"] = ["voorkeur", "prefer", "wolę", "prefer", "أفضل"],
        ["Work.Indoor.ok"] = ["prima", "fine", "ok", "ok", "مناسب"],
        ["Work.Indoor.rather-not"] = ["liever niet", "rather not", "raczej nie", "mai degrabă nu", "أفضل ألا"],
        ["Work.Outdoor.prefer"] = ["voorkeur", "prefer", "wolę", "prefer", "أفضل"],
        ["Work.Outdoor.ok"] = ["prima", "fine", "ok", "ok", "مناسب"],
        ["Work.Outdoor.ok-not-frost"] = ["prima, niet bij vorst", "fine, not in frost", "ok, nie przy mrozie", "ok, nu pe ger", "مناسب، ليس في الصقيع"],
        ["Work.Outdoor.rather-not"] = ["liever niet", "rather not", "raczej nie", "mai degrabă nu", "أفضل ألا"],
        ["Work.Physical.light"] = ["licht werk", "light work", "lekka praca", "muncă ușoară", "عمل خفيف"],
        ["Work.Physical.standing"] = ["staand werk", "standing work", "praca na stojąco", "muncă în picioare", "عمل وقوفاً"],
        ["Work.Physical.lifting-15"] = ["tillen tot 15 kg", "lifting up to 15 kg", "dźwiganie do 15 kg", "ridicare până la 15 kg", "رفع حتى 15 كغ"],
        ["Work.Physical.lifting-25"] = ["tillen tot 25 kg", "lifting up to 25 kg", "dźwiganie do 25 kg", "ridicare până la 25 kg", "رفع حتى 25 كغ"],
        ["Work.Pace.norm-ok"] = ["prima", "a normal pace is fine", "normalne tempo jest ok", "ritmul normal e ok", "الوتيرة العادية مناسبة"],
        ["Work.Pace.calm"] = ["rustig tempo", "a calm pace", "spokojne tempo", "ritm calm", "وتيرة هادئة"],
        ["Contract.uitzend"] = ["uitzend", "agency", "agencja", "agenție", "وكالة"],
        ["Contract.vast"] = ["vast", "permanent", "stały", "nedeterminat", "دائم"],
        ["Contract.tijdelijk"] = ["tijdelijk", "temporary", "tymczasowy", "temporar", "مؤقت"],
        ["Contract.seizoen"] = ["seizoen", "seasonal", "sezon", "sezon", "موسمي"],
        ["Contract.oproep"] = ["oproep", "on-call", "na wezwanie", "la chemare", "عند الطلب"],
        ["Contract.geen-voorkeur"] = ["geen voorkeur", "no preference", "bez preferencji", "fără preferință", "بدون تفضيل"],
        ["Dutch.beginner"] = ["Beginner", "Beginner", "Początkujący", "Începător", "مبتدئ"],
        ["Dutch.basis"] = ["Basis", "Basic", "Podstawowy", "De bază", "أساسي"],
        ["Dutch.goed"] = ["Goed", "Good", "Dobry", "Bun", "جيد"],
        ["Dutch.vloeiend"] = ["Vloeiend", "Fluent", "Płynny", "Fluent", "بطلاقة"],
        ["Dutch.moedertaal"] = ["Moedertaal", "Native", "Ojczysty", "Limbă maternă", "لغة أم"],
        ["DutchNote.beginner"] = ["Leert het net (A1–A2).", "Just starting (A1–A2).", "Dopiero się uczy (A1–A2).", "Abia învață (A1–A2).", "يتعلم للتو (A1–A2)."],
        ["DutchNote.basis"] = ["Redt zich in gewone gesprekken (B1).", "Manages in everyday talks (B1).", "Radzi sobie w zwykłych rozmowach (B1).", "Se descurcă în conversații obișnuite (B1).", "يتعامل في المحادثات العادية (B1)."],
        ["DutchNote.goed"] = ["Praat vlot over werk (B2).", "Speaks easily about work (B2).", "Swobodnie mówi o pracy (B2).", "Vorbește lejer despre muncă (B2).", "يتحدث بسهولة عن العمل (B2)."],
        ["DutchNote.vloeiend"] = ["Bijna als een moedertaal (C1).", "Almost like a native speaker (C1).", "Prawie jak język ojczysty (C1).", "Aproape ca limba maternă (C1).", "تقريباً كلغة أم (C1)."],
        ["DutchNote.moedertaal"] = ["Nederlands is de moedertaal.", "Dutch is the native language.", "Niderlandzki to język ojczysty.", "Neerlandeza este limba maternă.", "الهولندية هي اللغة الأم."],
        ["Employer.small-team"] = ["klein, warm team", "small, warm team", "mały, ciepły zespół", "echipă mică și caldă", "فريق صغير ودافئ"],
        ["Employer.large-company"] = ["groot bedrijf", "large company", "duża firma", "companie mare", "شركة كبيرة"],
        ["Employer.fixed-workplace"] = ["vaste werkplek", "fixed workplace", "stałe miejsce pracy", "loc de muncă fix", "مكان عمل ثابت"],
        ["Employer.learn-on-the-job"] = ["leren op de werkvloer", "learn on the job", "nauka w pracy", "învățare la locul de muncă", "التعلم في العمل"],
        ["Employer.dutch-support"] = ["hulp met Nederlands", "help with Dutch", "pomoc z niderlandzkim", "ajutor cu neerlandeza", "مساعدة في الهولندية"],
        ["Employer.growth"] = ["kans om door te groeien", "chance to grow", "szansa na rozwój", "șansă de creștere", "فرصة للتطور"],
        ["Employer.close-to-home"] = ["dicht bij huis", "close to home", "blisko domu", "aproape de casă", "قريب من المنزل"],
        ["Employer.variety"] = ["veel afwisseling", "lots of variety", "dużo różnorodności", "multă varietate", "تنوع كبير"],
        ["Transport.Fiets"] = ["fiets", "bike", "rower", "bicicletă", "دراجة"],
        ["Transport.E-bike"] = ["e-bike", "e-bike", "e-bike", "e-bike", "دراجة كهربائية"],
        ["Transport.Auto"] = ["auto", "car", "auto", "mașină", "سيارة"],
        ["Transport.OV"] = ["ov", "public transport", "komunikacja", "transport public", "مواصلات"],
        ["Transport.Lopend"] = ["lopend", "walking", "pieszo", "pe jos", "مشياً"],
        ["Lang.nl"] = ["Nederlands", "Dutch", "Niderlandzki", "Neerlandeză", "الهولندية"],
        ["Lang.en"] = ["Engels", "English", "Angielski", "Engleză", "الإنجليزية"],
        ["Lang.pl"] = ["Pools", "Polish", "Polski", "Poloneză", "البولندية"],
        ["Lang.ro"] = ["Roemeens", "Romanian", "Rumuński", "Română", "الرومانية"],
        ["Lang.ar"] = ["Arabisch", "Arabic", "Arabski", "Arabă", "العربية"],
        ["Lang.de"] = ["Duits", "German", "Niemiecki", "Germană", "الألمانية"],
        ["Lang.fr"] = ["Frans", "French", "Francuski", "Franceză", "الفرنسية"],
        ["Lang.tr"] = ["Turks", "Turkish", "Turecki", "Turcă", "التركية"],
        ["Lang.uk"] = ["Oekraïens", "Ukrainian", "Ukraiński", "Ucraineană", "الأوكرانية"],
        ["Lang.es"] = ["Spaans", "Spanish", "Hiszpański", "Spaniolă", "الإسبانية"],
        ["Lang.so"] = ["Somalisch", "Somali", "Somalijski", "Somaleză", "الصومالية"],
        ["Lang.ti"] = ["Tigrinya", "Tigrinya", "Tigrinia", "Tigrinya", "التغرينية"],
        ["Lang.fa"] = ["Perzisch", "Persian", "Perski", "Persană", "الفارسية"],
        ["StoryTitle"] = ["Mijn verhaal", "My story", "Moja historia", "Povestea mea", "قصتي"],
        ["TraitsTitle"] = ["Jouw sterkste eigenschappen", "Your strongest traits", "Twoje najmocniejsze cechy", "Cele mai puternice trăsături", "أقوى صفاتك"],
        ["HomeTitle"] = ["Hier voel je je thuis", "Where you feel at home", "Tu czujesz się dobrze", "Aici te simți acasă", "هنا تشعر بالراحة"],
        ["ValuesTitle"] = ["Wat je belangrijk vindt", "What matters to you", "Co jest dla ciebie ważne", "Ce contează pentru tine", "ما يهمك"],
        ["RadarTitle"] = ["Jouw DNA in één oogopslag", "Your DNA at a glance", "Twoje DNA w skrócie", "ADN-ul tău dintr-o privire", "حمضك النووي بنظرة"],
        ["RadarNote"] = ["Uit je DNA-tests. Sterkte in woorden, geen ranking.", "From your DNA tests. Strength in words, no ranking.", "Z testów DNA. Siła w słowach, bez rankingu.", "Din testele ADN. Putere în cuvinte, fără clasament.", "من اختبارات الحمض النووي. القوة في كلمات، بلا ترتيب."],
        ["JobsTitle"] = ["Werk dat bij je past", "Work that fits you", "Praca, która do ciebie pasuje", "Muncă ce ți se potrivește", "عمل يناسبك"],
        ["JobWhySelf"] = ["Deze rol gaf je zelf op.", "You entered this role yourself.", "Tę rolę wpisałeś sam.", "Acest rol l-ai scris tu.", "كتبت هذا الدور بنفسك."],
        ["DidThis"] = ["Je deed dit werk al.", "You already did this work.", "Robiłeś już tę pracę.", "Ai făcut deja această muncă.", "قمت بهذا العمل من قبل."],
        ["PracticalTitle"] = ["Praktisch", "Practical", "Praktycznie", "Practic", "عملي"],
        ["Page2Hint"] = ["Blad 2 = werkervaring en referenties", "Page 2 = experience and references", "Strona 2 = doświadczenie i referencje", "Pagina 2 = experiență și referințe", "الصفحة 2 = الخبرة والمراجع"],
        ["WorkExperience"] = ["Werkervaring", "Work experience", "Doświadczenie zawodowe", "Experiență de muncă", "خبرة العمل"],
        ["PapersTitle"] = ["Opleiding en papieren", "Education and papers", "Wykształcenie i dokumenty", "Educație și acte", "التعليم والأوراق"],
        ["ReferencesTitle"] = ["Wat referenties zeggen", "What references say", "Co mówią referencje", "Ce spun referințele", "ماذا تقول المراجع"],
        ["NoReferences"] = ["Nog geen gedeelde referentie.", "No shared reference yet.", "Nie ma jeszcze udostępnionej referencji.", "Nicio referință partajată încă.", "لا توجد مرجعية مشاركة بعد."],
        ["NoExperience"] = ["Je hebt nog geen werkervaring ingevuld.", "You have not entered work experience yet.", "Nie wpisałeś jeszcze doświadczenia.", "Nu ai completat încă experiența.", "لم تكتب خبرة عمل بعد."],
        ["NoPapers"] = ["Je hebt nog geen opleiding of papieren ingevuld.", "You have not entered education or papers yet.", "Nie wpisałeś jeszcze wykształcenia ani dokumentów.", "Nu ai completat încă educația sau actele.", "لم تكتب تعليماً أو أوراقاً بعد."],
        ["DirectionTitle"] = ["Richting / droombaan", "Direction / dream job", "Kierunek / praca marzeń", "Direcție / jobul visat", "الاتجاه / وظيفة الحلم"],
        ["StepDone"] = ["gedaan", "done", "zrobione", "făcut", "تم"],
        ["StepNow"] = ["nu", "now", "teraz", "acum", "الآن"],
        ["StepLater"] = ["later", "later", "później", "mai târziu", "لاحقاً"],
        ["ShareCta"] = ["Deel alleen als jij dat wilt", "Share only if you want to", "Udostępniaj tylko jeśli chcesz", "Împărtășește doar dacă vrei", "شارك فقط إذا أردت"],
        ["ShareCtaTail"] = ["geen scores · geen ranking", "no scores · no ranking", "bez wyników · bez rankingu", "fără scoruri · fără clasament", "بلا درجات · بلا ترتيب"],
        ["CheckedTitle"] = ["Wat Lobsy checkte", "What Lobsy checked", "Co sprawdziło Lobsy", "Ce a verificat Lobsy", "ما راجعته لوبسي"],
        ["NotOnPassport"] = ["Bewust niet hierop", "Left off on purpose", "Świadomie pominięte", "Lăsat deoparte intenționat", "تُرك عمداً"],
        ["NotBirth"] = ["Geboortedatum, foto, BSN", "Date of birth, photo, citizen number", "Data urodzenia, zdjęcie, numer", "Data nașterii, foto, număr", "تاريخ الميلاد والصورة والرقم"],
        ["NotHealth"] = ["Gezondheid", "Health", "Zdrowie", "Sănătate", "الصحة"],
        ["NotScores"] = ["Scores of ranking", "Scores or ranking", "Wyniki lub ranking", "Scoruri sau clasament", "درجات أو ترتيب"],
        ["NotAi"] = ["Automatische selectie", "Automatic selection", "Automatyczny wybór", "Selecție automată", "اختيار تلقائي"],
        ["DnaChecked"] = ["DNA-tests ({0}/4)", "DNA tests ({0}/4)", "Testy DNA ({0}/4)", "Teste ADN ({0}/4)", "اختبارات ({0}/4)"],
        ["RefsShared"] = ["Referenties die jij deelt", "References you choose to share", "Referencje, które udostępniasz", "Referințe pe care le împărtășești", "مراجع تختار مشاركتها"],
        ["IdNotChecked"] = ["ID en diploma's niet gecontroleerd", "ID and diplomas are not checked", "Dowód i dyplomy nie są sprawdzane", "Actul și diplomele nu sunt verificate", "الهوية والشهادات غير مراجعة"],
        ["AvailableChip"] = ["Beschikbaar", "Available", "Dostępny", "Disponibil", "متاح"],
        ["NowWord"] = ["nu", "now", "teraz", "acum", "الآن"],
        ["FooterOne"] = ["Geen scores of ranking. Feiten uit tests en wat jij invulde.", "No scores or ranking. Facts from tests and what you entered.", "Bez wyników i rankingu. Fakty z testów i tego, co wpisałeś.", "Fără scoruri sau clasament. Fapte din teste și ce ai scris tu.", "بلا درجات أو ترتيب. حقائق من الاختبارات وما كتبته."],
        ["SeeksLine"] = ["Zoekt: {0}", "Looking for: {0}", "Szuka: {0}", "Caută: {0}", "يبحث عن: {0}"],
        ["StoryWorks"] = ["Ik werk bij {0} als {1}.", "I work at {0} as {1}.", "Pracuję w {0} jako {1}.", "Lucrez la {0} ca {1}.", "أعمل في {0} بصفة {1}."],
        ["StoryWorksPlace"] = ["Ik werk bij {0}.", "I work at {0}.", "Pracuję w {0}.", "Lucrez la {0}.", "أعمل في {0}."],
        ["StoryWorked"] = ["Ik werkte bij {0} als {1}.", "I worked at {0} as {1}.", "Pracowałem w {0} jako {1}.", "Am lucrat la {0} ca {1}.", "عملت في {0} بصفة {1}."],
        ["StoryWorkedPlace"] = ["Ik werkte bij {0}.", "I worked at {0}.", "Pracowałem w {0}.", "Am lucrat la {0}.", "عملت في {0}."],
        ["StoryEducation"] = ["Opleiding: {0}.", "Education: {0}.", "Wykształcenie: {0}.", "Educație: {0}.", "التعليم: {0}."],
        ["StoryPapers"] = ["Papieren: {0}.", "Papers: {0}.", "Dokumenty: {0}.", "Acte: {0}.", "الأوراق: {0}."],
        ["StorySeeks"] = ["Ik zoek werk als {0}.", "I am looking for work as {0}.", "Szukam pracy jako {0}.", "Caut lucru ca {0}.", "أبحث عن عمل بصفة {0}."],
        ["StoryHours"] = ["Ik kan {0} werken.", "I can work {0}.", "Mogę pracować {0}.", "Pot lucra {0}.", "يمكنني العمل {0}."],
        ["StoryRegion"] = ["Ik zoek werk in {0}.", "I am looking for work in {0}.", "Szukam pracy w {0}.", "Caut lucru în {0}.", "أبحث عن عمل في {0}."],
        ["TraitFallback"] = ["Dit kwam naar voren in je test.", "This came up in your test.", "To wyszło w twoim teście.", "A ieșit din testul tău.", "ظهر هذا في اختبارك."],
        ["Home.Indoor.prefer"] = ["Liever binnen werken", "Prefers working indoors", "Woli pracę w środku", "Preferă munca în interior", "يفضل العمل في الداخل"],
        ["Home.Indoor.ok"] = ["Binnen werken is prima", "Working indoors is fine", "Praca w środku jest w porządku", "Munca în interior e în regulă", "العمل في الداخل مناسب"],
        ["Home.Indoor.rather-not"] = ["Liever niet de hele dag binnen", "Rather not indoors all day", "Raczej nie cały dzień w środku", "Mai degrabă nu toată ziua în interior", "يفضل ألا يبقى طوال اليوم في الداخل"],
        ["Home.Outdoor.prefer"] = ["Graag buiten werken", "Likes working outdoors", "Lubię pracę na zewnątrz", "Îi place munca afară", "يحب العمل في الخارج"],
        ["Home.Outdoor.ok"] = ["Buiten werken is prima", "Working outdoors is fine", "Praca na zewnątrz jest w porządku", "Munca afară e în regulă", "العمل في الخارج مناسب"],
        ["Home.Outdoor.ok-not-frost"] = ["Buiten is prima, niet bij vorst", "Outdoors is fine, not in frost", "Na zewnątrz w porządku, nie przy mrozie", "Afară e în regulă, nu pe ger", "الخارج مناسب وليس في الصقيع"],
        ["Home.Outdoor.rather-not"] = ["Liever niet buiten", "Rather not outdoors", "Raczej nie na zewnątrz", "Mai degrabă nu afară", "يفضل ألا يعمل في الخارج"],
        ["Home.Physical.light"] = ["Licht werk", "Light work", "Lekka praca", "Muncă ușoară", "عمل خفيف"],
        ["Home.Physical.standing"] = ["Staand werk is prima", "Standing work is fine", "Praca na stojąco jest w porządku", "Munca în picioare e în regulă", "العمل وقوفاً مناسب"],
        ["Home.Physical.lifting-15"] = ["Tillen tot 15 kg is prima", "Lifting up to 15 kg is fine", "Dźwiganie do 15 kg jest w porządku", "Ridicarea până la 15 kg e în regulă", "رفع حتى 15 كغ مناسب"],
        ["Home.Physical.lifting-25"] = ["Tillen tot 25 kg is prima", "Lifting up to 25 kg is fine", "Dźwiganie do 25 kg jest w porządku", "Ridicarea până la 25 kg e în regulă", "رفع حتى 25 كغ مناسب"],
        ["Home.Pace.norm-ok"] = ["Een normaal tempo is prima", "A normal pace is fine", "Normalne tempo jest w porządku", "Un ritm normal e în regulă", "الوتيرة العادية مناسبة"],
        ["Home.Pace.calm"] = ["Een rustig tempo", "A calm pace", "Spokojne tempo", "Un ritm calm", "وتيرة هادئة"]
    };
}
