using Jobsy.Core.Enums;

namespace Jobsy.Api.Models;

public record CreateVacancyRequest(
    Guid CompanyId,
    string Title,
    string Description,
    decimal HourlyWage,
    DateOnly StartDate,
    DateOnly EndDate,
    TransportMode RequiredTransport,
    string[] WorkTypes,
    string? ImageUrl = null,
    string? VideoUrl = null,
    Guid? SalaryTableId = null,
    string? RequiredDrivingLicense = null,
    string? RequiredEducation = null,
    int? MinimumEmployers = null,
    bool OverrideContactPreference = false,
    bool DirectContactEnabled = false,
    bool ContactPreferMail = false,
    bool ContactPreferPhone = false,
    bool ContactPreferWhatsApp = false,
    decimal? MinHoursPerWeek = null,
    decimal? MaxHoursPerWeek = null,
    bool? FlexibleTimes = null,
    Dictionary<string, string[]>? ScheduleSlots = null,
    bool? LegalWorksAfter19 = null,
    bool? LegalNightShift23To06 = null,
    bool? LegalAdultSupervisorPresent = null,
    bool? LegalHandlesMoneyOrClosing = null,
    bool? LegalHeavyOrHazardousWork = null,
    bool ShowClientAddressOnMap = false,
    VacancyKind Kind = VacancyKind.Regular,
    Guid? ExclusivitySettingId = null,
    Guid? CategoryId = null,
    Dictionary<string, string>? CategoryFields = null);
